int_rules_4_3_2_3 = @theory begin

    #= ::Subsection::Closed:: =#
    #= 4.3.2.3*(g*tan)^p*(a+b*tan)^m*(c+d*tan)^n =#
    @apply_utils Antiderivative((~(g') * tan(~(e') + ~(f') * ~x)) ^ ~(p') * (~a + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~m * (~c + ~(d') * tan(~(e') + ~(f') * ~x)) ^ ~n, ~x) => Unintegrable((~g * tan(~e + ~f * ~x)) ^ ~p * (~a + ~b * tan(~e + ~f * ~x)) ^ ~m * (~c + ~d * tan(~e + ~f * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~m, ~n, ~p], ~x)
    @apply_utils Antiderivative((~(g') * cot(~(e') + ~(f') * ~x)) ^ ~p * (~(a') + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~(m') * (~c + ~(d') * tan(~(e') + ~(f') * ~x)) ^ ~(n'), ~x) => (~g) ^ (~m + ~n) * Antiderivative((~g * cot(~e + ~f * ~x)) ^ ((~p - ~m) - ~n) * (~b + ~a * cot(~e + ~f * ~x)) ^ ~m * (~d + ~c * cot(~e + ~f * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~p], ~x) && (Not(IntegerQ(~p)) && (IntegerQ(~m) && IntegerQ(~n)))
    @apply_utils Antiderivative((~(g') * tan(~(e') + ~(f') * ~x)) ^ ~p * (~(a') + ~(b') * cot(~(e') + ~(f') * ~x)) ^ ~(m') * (~c + ~(d') * cot(~(e') + ~(f') * ~x)) ^ ~(n'), ~x) => (~g) ^ (~m + ~n) * Antiderivative((~g * tan(~e + ~f * ~x)) ^ ((~p - ~m) - ~n) * (~b + ~a * tan(~e + ~f * ~x)) ^ ~m * (~d + ~c * tan(~e + ~f * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~p], ~x) && (Not(IntegerQ(~p)) && (IntegerQ(~m) && IntegerQ(~n)))
    @apply_utils Antiderivative((~(g') * tan(~(e') + ~(f') * ~x) ^ ~q) ^ ~p * (~(a') + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~(m') * (~c + ~(d') * tan(~(e') + ~(f') * ~x)) ^ ~(n'), ~x) => ((~g * tan(~e + ~f * ~x) ^ ~q) ^ ~p / (~g * tan(~e + ~f * ~x)) ^ (~p * ~q)) * Antiderivative((~g * tan(~e + ~f * ~x)) ^ (~p * ~q) * (~a + ~b * tan(~e + ~f * ~x)) ^ ~m * (~c + ~d * tan(~e + ~f * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~m, ~n, ~p, ~q], ~x) && (Not(IntegerQ(~p)) && Not(IntegerQ(~m) && IntegerQ(~n)))
    @apply_utils Antiderivative((~(g') * tan(~(e') + ~(f') * ~x)) ^ ~(p') * (~a + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~(m') * (~c + ~(d') * cot(~(e') + ~(f') * ~x)) ^ ~(n'), ~x) => (~g) ^ ~n * Antiderivative((~g * tan(~e + ~f * ~x)) ^ (~p - ~n) * (~a + ~b * tan(~e + ~f * ~x)) ^ ~m * (~d + ~c * tan(~e + ~f * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~m, ~p], ~x) && IntegerQ(~n)
    @apply_utils Antiderivative(tan(~(e') + ~(f') * ~x) ^ ~(p') * (~a + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~(m') * (~c + ~(d') * cot(~(e') + ~(f') * ~x)) ^ ~n, ~x) => Antiderivative(((~b + ~a * cot(~e + ~f * ~x)) ^ ~m * (~c + ~d * cot(~e + ~f * ~x)) ^ ~n) / cot(~e + ~f * ~x) ^ (~m + ~p), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~n], ~x) && (Not(IntegerQ(~n)) && (IntegerQ(~m) && IntegerQ(~p)))
    @apply_utils Antiderivative((~(g') * tan(~(e') + ~(f') * ~x)) ^ ~p * (~a + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~(m') * (~c + ~(d') * cot(~(e') + ~(f') * ~x)) ^ ~n, ~x) => cot(~e + ~f * ~x) ^ ~p * (~g * tan(~e + ~f * ~x)) ^ ~p * Antiderivative(((~b + ~a * cot(~e + ~f * ~x)) ^ ~m * (~c + ~d * cot(~e + ~f * ~x)) ^ ~n) / cot(~e + ~f * ~x) ^ (~m + ~p), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~n, ~p], ~x) && (Not(IntegerQ(~n)) && (IntegerQ(~m) && Not(IntegerQ(~p))))
    @apply_utils Antiderivative((~(g') * tan(~(e') + ~(f') * ~x)) ^ ~(p') * (~a + ~(b') * tan(~(e') + ~(f') * ~x)) ^ ~m * (~c + ~(d') * cot(~(e') + ~(f') * ~x)) ^ ~n, ~x) => (((~g * tan(~e + ~f * ~x)) ^ ~n * (~c + ~d * cot(~e + ~f * ~x)) ^ ~n) / (~d + ~c * tan(~e + ~f * ~x)) ^ ~n) * Antiderivative((~g * tan(~e + ~f * ~x)) ^ (~p - ~n) * (~a + ~b * tan(~e + ~f * ~x)) ^ ~m * (~d + ~c * tan(~e + ~f * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f, ~g, ~m, ~n, ~p], ~x) && (Not(IntegerQ(~n)) && Not(IntegerQ(~m)))
end
