@testset "6.2.2 (e x)^m (a+b x^n)^p cosh" begin
    (a, b, c, d, x, ) = @variables a b c d x

    #= ::Package:: =#

    #= ::Title:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^n)^p*cosh(c+d*x)=#


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^1)^p*cosh(c+d*x)=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^3*(a + b*x)*cosh(c + d*x), x, 11, (-6*a*cosh(c + d*x))/d^4 - (24*b*x*cosh(c + d*x))/d^4 - (3*a*x^2*cosh(c + d*x))/d^2 - (4*b*x^3*cosh(c + d*x))/d^2 + (24*b*sinh(c + d*x))/d^5 + (6*a*x*sinh(c + d*x))/d^3 + (12*b*x^2*sinh(c + d*x))/d^3 + (a*x^3*sinh(c + d*x))/d + (b*x^4*sinh(c + d*x))/d]
    @test_int [x^2*(a + b*x)*cosh(c + d*x), x, 9, (-6*b*cosh(c + d*x))/d^4 - (2*a*x*cosh(c + d*x))/d^2 - (3*b*x^2*cosh(c + d*x))/d^2 + (2*a*sinh(c + d*x))/d^3 + (6*b*x*sinh(c + d*x))/d^3 + (a*x^2*sinh(c + d*x))/d + (b*x^3*sinh(c + d*x))/d]
    @test_int [x*(a + b*x)*cosh(c + d*x), x, 7, -((a*cosh(c + d*x))/d^2) - (2*b*x*cosh(c + d*x))/d^2 + (2*b*sinh(c + d*x))/d^3 + (a*x*sinh(c + d*x))/d + (b*x^2*sinh(c + d*x))/d]
    @test_int [(a + b*x)*cosh(c + d*x), x, 2, -((b*cosh(c + d*x))/d^2) + ((a + b*x)*sinh(c + d*x))/d]
    @test_int [((a + b*x)*cosh(c + d*x))/x, x, 6, a*cosh(c)*CoshIntegral(d*x) + (b*sinh(c + d*x))/d + a*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x)*cosh(c + d*x))/x^2, x, 9, -((a*cosh(c + d*x))/x) + b*cosh(c)*CoshIntegral(d*x) + a*d*CoshIntegral(d*x)*sinh(c) + a*d*cosh(c)*SinhIntegral(d*x) + b*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x)*cosh(c + d*x))/x^3, x, 11, -(a*cosh(c + d*x))/(2*x^2) - (b*cosh(c + d*x))/x + (a*d^2*cosh(c)*CoshIntegral(d*x))/2 + b*d*CoshIntegral(d*x)*sinh(c) - (a*d*sinh(c + d*x))/(2*x) + b*d*cosh(c)*SinhIntegral(d*x) + (a*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x)*cosh(c + d*x))/x^4, x, 13, -(a*cosh(c + d*x))/(3*x^3) - (b*cosh(c + d*x))/(2*x^2) - (a*d^2*cosh(c + d*x))/(6*x) + (b*d^2*cosh(c)*CoshIntegral(d*x))/2 + (a*d^3*CoshIntegral(d*x)*sinh(c))/6 - (a*d*sinh(c + d*x))/(6*x^2) - (b*d*sinh(c + d*x))/(2*x) + (a*d^3*cosh(c)*SinhIntegral(d*x))/6 + (b*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x)*cosh(c + d*x))/x^5, x, 15, -(a*cosh(c + d*x))/(4*x^4) - (b*cosh(c + d*x))/(3*x^3) - (a*d^2*cosh(c + d*x))/(24*x^2) - (b*d^2*cosh(c + d*x))/(6*x) + (a*d^4*cosh(c)*CoshIntegral(d*x))/24 + (b*d^3*CoshIntegral(d*x)*sinh(c))/6 - (a*d*sinh(c + d*x))/(12*x^3) - (b*d*sinh(c + d*x))/(6*x^2) - (a*d^3*sinh(c + d*x))/(24*x) + (b*d^3*cosh(c)*SinhIntegral(d*x))/6 + (a*d^4*sinh(c)*SinhIntegral(d*x))/24]


    @test_int [x^2*(a + b*x)^2*cosh(c + d*x), x, 14, (-12*a*b*cosh(c + d*x))/d^4 - (24*b^2*x*cosh(c + d*x))/d^4 - (2*a^2*x*cosh(c + d*x))/d^2 - (6*a*b*x^2*cosh(c + d*x))/d^2 - (4*b^2*x^3*cosh(c + d*x))/d^2 + (24*b^2*sinh(c + d*x))/d^5 + (2*a^2*sinh(c + d*x))/d^3 + (12*a*b*x*sinh(c + d*x))/d^3 + (12*b^2*x^2*sinh(c + d*x))/d^3 + (a^2*x^2*sinh(c + d*x))/d + (2*a*b*x^3*sinh(c + d*x))/d + (b^2*x^4*sinh(c + d*x))/d]
    @test_int [x*(a + b*x)^2*cosh(c + d*x), x, 11, (-6*b^2*cosh(c + d*x))/d^4 - (a^2*cosh(c + d*x))/d^2 - (4*a*b*x*cosh(c + d*x))/d^2 - (3*b^2*x^2*cosh(c + d*x))/d^2 + (4*a*b*sinh(c + d*x))/d^3 + (6*b^2*x*sinh(c + d*x))/d^3 + (a^2*x*sinh(c + d*x))/d + (2*a*b*x^2*sinh(c + d*x))/d + (b^2*x^3*sinh(c + d*x))/d]
    @test_int [(a + b*x)^2*cosh(c + d*x), x, 3, (-2*b*(a + b*x)*cosh(c + d*x))/d^2 + (2*b^2*sinh(c + d*x))/d^3 + ((a + b*x)^2*sinh(c + d*x))/d]
    @test_int [((a + b*x)^2*cosh(c + d*x))/x, x, 8, -((b^2*cosh(c + d*x))/d^2) + a^2*cosh(c)*CoshIntegral(d*x) + (2*a*b*sinh(c + d*x))/d + (b^2*x*sinh(c + d*x))/d + a^2*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x)^2*cosh(c + d*x))/x^2, x, 10, -((a^2*cosh(c + d*x))/x) + 2*a*b*cosh(c)*CoshIntegral(d*x) + a^2*d*CoshIntegral(d*x)*sinh(c) + (b^2*sinh(c + d*x))/d + a^2*d*cosh(c)*SinhIntegral(d*x) + 2*a*b*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x)^2*cosh(c + d*x))/x^3, x, 14, -(a^2*cosh(c + d*x))/(2*x^2) - (2*a*b*cosh(c + d*x))/x + b^2*cosh(c)*CoshIntegral(d*x) + (a^2*d^2*cosh(c)*CoshIntegral(d*x))/2 + 2*a*b*d*CoshIntegral(d*x)*sinh(c) - (a^2*d*sinh(c + d*x))/(2*x) + 2*a*b*d*cosh(c)*SinhIntegral(d*x) + b^2*sinh(c)*SinhIntegral(d*x) + (a^2*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x)^2*cosh(c + d*x))/x^4, x, 17, -(a^2*cosh(c + d*x))/(3*x^3) - (a*b*cosh(c + d*x))/x^2 - (b^2*cosh(c + d*x))/x - (a^2*d^2*cosh(c + d*x))/(6*x) + a*b*d^2*cosh(c)*CoshIntegral(d*x) + b^2*d*CoshIntegral(d*x)*sinh(c) + (a^2*d^3*CoshIntegral(d*x)*sinh(c))/6 - (a^2*d*sinh(c + d*x))/(6*x^2) - (a*b*d*sinh(c + d*x))/x + b^2*d*cosh(c)*SinhIntegral(d*x) + (a^2*d^3*cosh(c)*SinhIntegral(d*x))/6 + a*b*d^2*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x)^2*cosh(c + d*x))/x^5, x, 20, -(a^2*cosh(c + d*x))/(4*x^4) - (2*a*b*cosh(c + d*x))/(3*x^3) - (b^2*cosh(c + d*x))/(2*x^2) - (a^2*d^2*cosh(c + d*x))/(24*x^2) - (a*b*d^2*cosh(c + d*x))/(3*x) + (b^2*d^2*cosh(c)*CoshIntegral(d*x))/2 + (a^2*d^4*cosh(c)*CoshIntegral(d*x))/24 + (a*b*d^3*CoshIntegral(d*x)*sinh(c))/3 - (a^2*d*sinh(c + d*x))/(12*x^3) - (a*b*d*sinh(c + d*x))/(3*x^2) - (b^2*d*sinh(c + d*x))/(2*x) - (a^2*d^3*sinh(c + d*x))/(24*x) + (a*b*d^3*cosh(c)*SinhIntegral(d*x))/3 + (b^2*d^2*sinh(c)*SinhIntegral(d*x))/2 + (a^2*d^4*sinh(c)*SinhIntegral(d*x))/24]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^4*cosh(c + d*x))/(a + b*x), x, 15, (-6*cosh(c + d*x))/(b*d^4) - (a^2*cosh(c + d*x))/(b^3*d^2) + (2*a*x*cosh(c + d*x))/(b^2*d^2) - (3*x^2*cosh(c + d*x))/(b*d^2) + (a^4*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^5 - (2*a*sinh(c + d*x))/(b^2*d^3) - (a^3*sinh(c + d*x))/(b^4*d) + (6*x*sinh(c + d*x))/(b*d^3) + (a^2*x*sinh(c + d*x))/(b^3*d) - (a*x^2*sinh(c + d*x))/(b^2*d) + (x^3*sinh(c + d*x))/(b*d) + (a^4*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^5]
    @test_int [(x^3*cosh(c + d*x))/(a + b*x), x, 11, (a*cosh(c + d*x))/(b^2*d^2) - (2*x*cosh(c + d*x))/(b*d^2) - (a^3*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^4 + (2*sinh(c + d*x))/(b*d^3) + (a^2*sinh(c + d*x))/(b^3*d) - (a*x*sinh(c + d*x))/(b^2*d) + (x^2*sinh(c + d*x))/(b*d) - (a^3*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^4]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x), x, 8, -(cosh(c + d*x)/(b*d^2)) + (a^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^3 - (a*sinh(c + d*x))/(b^2*d) + (x*sinh(c + d*x))/(b*d) + (a^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^3]
    @test_int [(x*cosh(c + d*x))/(a + b*x), x, 6, -((a*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^2) + sinh(c + d*x)/(b*d) - (a*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^2]
    @test_int [cosh(c + d*x)/(a + b*x), x, 3, (cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b + (sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b]
    @test_int [cosh(c + d*x)/(x*(a + b*x)), x, 8, (cosh(c)*CoshIntegral(d*x))/a - (cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a + (sinh(c)*SinhIntegral(d*x))/a - (sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x)), x, 12, -(cosh(c + d*x)/(a*x)) - (b*cosh(c)*CoshIntegral(d*x))/a^2 + (b*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^2 + (d*CoshIntegral(d*x)*sinh(c))/a + (d*cosh(c)*SinhIntegral(d*x))/a - (b*sinh(c)*SinhIntegral(d*x))/a^2 + (b*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^2]
    @test_int [cosh(c + d*x)/(x^3*(a + b*x)), x, 17, -cosh(c + d*x)/(2*a*x^2) + (b*cosh(c + d*x))/(a^2*x) + (b^2*cosh(c)*CoshIntegral(d*x))/a^3 + (d^2*cosh(c)*CoshIntegral(d*x))/(2*a) - (b^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^3 - (b*d*CoshIntegral(d*x)*sinh(c))/a^2 - (d*sinh(c + d*x))/(2*a*x) - (b*d*cosh(c)*SinhIntegral(d*x))/a^2 + (b^2*sinh(c)*SinhIntegral(d*x))/a^3 + (d^2*sinh(c)*SinhIntegral(d*x))/(2*a) - (b^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^3]


    @test_int [(x^4*cosh(c + d*x))/(a + b*x)^2, x, 15, (2*a*cosh(c + d*x))/(b^3*d^2) - (2*x*cosh(c + d*x))/(b^2*d^2) - (a^4*cosh(c + d*x))/(b^5*(a + b*x)) - (4*a^3*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^5 + (a^4*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^6 + (2*sinh(c + d*x))/(b^2*d^3) + (3*a^2*sinh(c + d*x))/(b^4*d) - (2*a*x*sinh(c + d*x))/(b^3*d) + (x^2*sinh(c + d*x))/(b^2*d) + (a^4*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^6 - (4*a^3*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^5]
    @test_int [(x^3*cosh(c + d*x))/(a + b*x)^2, x, 12, -(cosh(c + d*x)/(b^2*d^2)) + (a^3*cosh(c + d*x))/(b^4*(a + b*x)) + (3*a^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^4 - (a^3*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^5 - (2*a*sinh(c + d*x))/(b^3*d) + (x*sinh(c + d*x))/(b^2*d) - (a^3*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^5 + (3*a^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^4]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x)^2, x, 10, -((a^2*cosh(c + d*x))/(b^3*(a + b*x))) - (2*a*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^3 + (a^2*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^4 + sinh(c + d*x)/(b^2*d) + (a^2*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^4 - (2*a*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^3]
    @test_int [(x*cosh(c + d*x))/(a + b*x)^2, x, 9, (a*cosh(c + d*x))/(b^2*(a + b*x)) + (cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^2 - (a*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^3 - (a*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^3 + (sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^2]
    @test_int [cosh(c + d*x)/(a + b*x)^2, x, 4, -(cosh(c + d*x)/(b*(a + b*x))) + (d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^2 + (d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^2]
    @test_int [cosh(c + d*x)/(x*(a + b*x)^2), x, 12, cosh(c + d*x)/(a*(a + b*x)) + (cosh(c)*CoshIntegral(d*x))/a^2 - (cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^2 - (d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/(a*b) + (sinh(c)*SinhIntegral(d*x))/a^2 - (d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(a*b) - (sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^2]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x)^2), x, 16, -(cosh(c + d*x)/(a^2*x)) - (b*cosh(c + d*x))/(a^2*(a + b*x)) - (2*b*cosh(c)*CoshIntegral(d*x))/a^3 + (2*b*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^3 + (d*CoshIntegral(d*x)*sinh(c))/a^2 + (d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/a^2 + (d*cosh(c)*SinhIntegral(d*x))/a^2 - (2*b*sinh(c)*SinhIntegral(d*x))/a^3 + (d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^2 + (2*b*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^3]


    @test_int [(x^3*cosh(c + d*x))/(a + b*x)^3, x, 15, (a^3*cosh(c + d*x))/(2*b^4*(a + b*x)^2) - (3*a^2*cosh(c + d*x))/(b^4*(a + b*x)) - (3*a*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^4 - (a^3*d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*b^6) + (3*a^2*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^5 + sinh(c + d*x)/(b^3*d) + (a^3*d*sinh(c + d*x))/(2*b^5*(a + b*x)) + (3*a^2*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^5 - (3*a*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^4 - (a^3*d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*b^6)]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x)^3, x, 14, -(a^2*cosh(c + d*x))/(2*b^3*(a + b*x)^2) + (2*a*cosh(c + d*x))/(b^3*(a + b*x)) + (cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/b^3 + (a^2*d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*b^5) - (2*a*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^4 - (a^2*d*sinh(c + d*x))/(2*b^4*(a + b*x)) - (2*a*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^4 + (sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^3 + (a^2*d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*b^5)]
    @test_int [(x*cosh(c + d*x))/(a + b*x)^3, x, 11, (a*cosh(c + d*x))/(2*b^2*(a + b*x)^2) - cosh(c + d*x)/(b^2*(a + b*x)) - (a*d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*b^4) + (d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/b^3 + (a*d*sinh(c + d*x))/(2*b^3*(a + b*x)) + (d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/b^3 - (a*d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*b^4)]
    @test_int [cosh(c + d*x)/(a + b*x)^3, x, 5, -cosh(c + d*x)/(2*b*(a + b*x)^2) + (d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*b^3) - (d*sinh(c + d*x))/(2*b^2*(a + b*x)) + (d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*b^3)]
    @test_int [cosh(c + d*x)/(x*(a + b*x)^3), x, 17, cosh(c + d*x)/(2*a*(a + b*x)^2) + cosh(c + d*x)/(a^2*(a + b*x)) + (cosh(c)*CoshIntegral(d*x))/a^3 - (cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^3 - (d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*a*b^2) - (d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/(a^2*b) + (d*sinh(c + d*x))/(2*a*b*(a + b*x)) + (sinh(c)*SinhIntegral(d*x))/a^3 - (d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(a^2*b) - (sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^3 - (d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*a*b^2)]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x)^3), x, 21, -(cosh(c + d*x)/(a^3*x)) - (b*cosh(c + d*x))/(2*a^2*(a + b*x)^2) - (2*b*cosh(c + d*x))/(a^3*(a + b*x)) - (3*b*cosh(c)*CoshIntegral(d*x))/a^4 + (3*b*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^4 + (d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*a^2*b) + (d*CoshIntegral(d*x)*sinh(c))/a^3 + (2*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/a^3 - (d*sinh(c + d*x))/(2*a^2*(a + b*x)) + (d*cosh(c)*SinhIntegral(d*x))/a^3 - (3*b*sinh(c)*SinhIntegral(d*x))/a^4 + (2*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^3 + (3*b*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^4 + (d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*a^2*b)]
    @test_int [cosh(c + d*x)/(x^3*(a + b*x)^3), x, 26, -cosh(c + d*x)/(2*a^3*x^2) + (3*b*cosh(c + d*x))/(a^4*x) + (b^2*cosh(c + d*x))/(2*a^3*(a + b*x)^2) + (3*b^2*cosh(c + d*x))/(a^4*(a + b*x)) + (6*b^2*cosh(c)*CoshIntegral(d*x))/a^5 + (d^2*cosh(c)*CoshIntegral(d*x))/(2*a^3) - (6*b^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/a^5 - (d^2*cosh(c - (a*d)/b)*CoshIntegral((a*d)/b + d*x))/(2*a^3) - (3*b*d*CoshIntegral(d*x)*sinh(c))/a^4 - (3*b*d*CoshIntegral((a*d)/b + d*x)*sinh(c - (a*d)/b))/a^4 - (d*sinh(c + d*x))/(2*a^3*x) + (b*d*sinh(c + d*x))/(2*a^3*(a + b*x)) - (3*b*d*cosh(c)*SinhIntegral(d*x))/a^4 + (6*b^2*sinh(c)*SinhIntegral(d*x))/a^5 + (d^2*sinh(c)*SinhIntegral(d*x))/(2*a^3) - (3*b*d*cosh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^4 - (6*b^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/a^5 - (d^2*sinh(c - (a*d)/b)*SinhIntegral((a*d)/b + d*x))/(2*a^3)]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^2)^p*cosh(c+d*x)=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^3*(a + b*x^2)*cosh(c + d*x), x, 12, (-120*b*cosh(c + d*x))/d^6 - (6*a*cosh(c + d*x))/d^4 - (60*b*x^2*cosh(c + d*x))/d^4 - (3*a*x^2*cosh(c + d*x))/d^2 - (5*b*x^4*cosh(c + d*x))/d^2 + (120*b*x*sinh(c + d*x))/d^5 + (6*a*x*sinh(c + d*x))/d^3 + (20*b*x^3*sinh(c + d*x))/d^3 + (a*x^3*sinh(c + d*x))/d + (b*x^5*sinh(c + d*x))/d]
    @test_int [x^2*(a + b*x^2)*cosh(c + d*x), x, 10, (-24*b*x*cosh(c + d*x))/d^4 - (2*a*x*cosh(c + d*x))/d^2 - (4*b*x^3*cosh(c + d*x))/d^2 + (24*b*sinh(c + d*x))/d^5 + (2*a*sinh(c + d*x))/d^3 + (12*b*x^2*sinh(c + d*x))/d^3 + (a*x^2*sinh(c + d*x))/d + (b*x^4*sinh(c + d*x))/d]
    @test_int [x*(a + b*x^2)*cosh(c + d*x), x, 8, (-6*b*cosh(c + d*x))/d^4 - (a*cosh(c + d*x))/d^2 - (3*b*x^2*cosh(c + d*x))/d^2 + (6*b*x*sinh(c + d*x))/d^3 + (a*x*sinh(c + d*x))/d + (b*x^3*sinh(c + d*x))/d]
    @test_int [(a + b*x^2)*cosh(c + d*x), x, 6, (-2*b*x*cosh(c + d*x))/d^2 + (2*b*sinh(c + d*x))/d^3 + (a*sinh(c + d*x))/d + (b*x^2*sinh(c + d*x))/d]
    @test_int [((a + b*x^2)*cosh(c + d*x))/x, x, 7, -((b*cosh(c + d*x))/d^2) + a*cosh(c)*CoshIntegral(d*x) + (b*x*sinh(c + d*x))/d + a*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^2)*cosh(c + d*x))/x^2, x, 7, -((a*cosh(c + d*x))/x) + a*d*CoshIntegral(d*x)*sinh(c) + (b*sinh(c + d*x))/d + a*d*cosh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^2)*cosh(c + d*x))/x^3, x, 10, -(a*cosh(c + d*x))/(2*x^2) + b*cosh(c)*CoshIntegral(d*x) + (a*d^2*cosh(c)*CoshIntegral(d*x))/2 - (a*d*sinh(c + d*x))/(2*x) + b*sinh(c)*SinhIntegral(d*x) + (a*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x^2)*cosh(c + d*x))/x^4, x, 12, -(a*cosh(c + d*x))/(3*x^3) - (b*cosh(c + d*x))/x - (a*d^2*cosh(c + d*x))/(6*x) + b*d*CoshIntegral(d*x)*sinh(c) + (a*d^3*CoshIntegral(d*x)*sinh(c))/6 - (a*d*sinh(c + d*x))/(6*x^2) + b*d*cosh(c)*SinhIntegral(d*x) + (a*d^3*cosh(c)*SinhIntegral(d*x))/6]
    @test_int [((a + b*x^2)*cosh(c + d*x))/x^5, x, 14, -(a*cosh(c + d*x))/(4*x^4) - (b*cosh(c + d*x))/(2*x^2) - (a*d^2*cosh(c + d*x))/(24*x^2) + (b*d^2*cosh(c)*CoshIntegral(d*x))/2 + (a*d^4*cosh(c)*CoshIntegral(d*x))/24 - (a*d*sinh(c + d*x))/(12*x^3) - (b*d*sinh(c + d*x))/(2*x) - (a*d^3*sinh(c + d*x))/(24*x) + (b*d^2*sinh(c)*SinhIntegral(d*x))/2 + (a*d^4*sinh(c)*SinhIntegral(d*x))/24]


    @test_int [x^2*(a + b*x^2)^2*cosh(c + d*x), x, 17, (-720*b^2*x*cosh(c + d*x))/d^6 - (48*a*b*x*cosh(c + d*x))/d^4 - (2*a^2*x*cosh(c + d*x))/d^2 - (120*b^2*x^3*cosh(c + d*x))/d^4 - (8*a*b*x^3*cosh(c + d*x))/d^2 - (6*b^2*x^5*cosh(c + d*x))/d^2 + (720*b^2*sinh(c + d*x))/d^7 + (48*a*b*sinh(c + d*x))/d^5 + (2*a^2*sinh(c + d*x))/d^3 + (360*b^2*x^2*sinh(c + d*x))/d^5 + (24*a*b*x^2*sinh(c + d*x))/d^3 + (a^2*x^2*sinh(c + d*x))/d + (30*b^2*x^4*sinh(c + d*x))/d^3 + (2*a*b*x^4*sinh(c + d*x))/d + (b^2*x^6*sinh(c + d*x))/d]
    @test_int [x*(a + b*x^2)^2*cosh(c + d*x), x, 14, (-120*b^2*cosh(c + d*x))/d^6 - (12*a*b*cosh(c + d*x))/d^4 - (a^2*cosh(c + d*x))/d^2 - (60*b^2*x^2*cosh(c + d*x))/d^4 - (6*a*b*x^2*cosh(c + d*x))/d^2 - (5*b^2*x^4*cosh(c + d*x))/d^2 + (120*b^2*x*sinh(c + d*x))/d^5 + (12*a*b*x*sinh(c + d*x))/d^3 + (a^2*x*sinh(c + d*x))/d + (20*b^2*x^3*sinh(c + d*x))/d^3 + (2*a*b*x^3*sinh(c + d*x))/d + (b^2*x^5*sinh(c + d*x))/d]
    @test_int [(a + b*x^2)^2*cosh(c + d*x), x, 11, (-24*b^2*x*cosh(c + d*x))/d^4 - (4*a*b*x*cosh(c + d*x))/d^2 - (4*b^2*x^3*cosh(c + d*x))/d^2 + (24*b^2*sinh(c + d*x))/d^5 + (4*a*b*sinh(c + d*x))/d^3 + (a^2*sinh(c + d*x))/d + (12*b^2*x^2*sinh(c + d*x))/d^3 + (2*a*b*x^2*sinh(c + d*x))/d + (b^2*x^4*sinh(c + d*x))/d]
    @test_int [((a + b*x^2)^2*cosh(c + d*x))/x, x, 11, (-6*b^2*cosh(c + d*x))/d^4 - (2*a*b*cosh(c + d*x))/d^2 - (3*b^2*x^2*cosh(c + d*x))/d^2 + a^2*cosh(c)*CoshIntegral(d*x) + (6*b^2*x*sinh(c + d*x))/d^3 + (2*a*b*x*sinh(c + d*x))/d + (b^2*x^3*sinh(c + d*x))/d + a^2*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^2)^2*cosh(c + d*x))/x^2, x, 10, -((a^2*cosh(c + d*x))/x) - (2*b^2*x*cosh(c + d*x))/d^2 + a^2*d*CoshIntegral(d*x)*sinh(c) + (2*b^2*sinh(c + d*x))/d^3 + (2*a*b*sinh(c + d*x))/d + (b^2*x^2*sinh(c + d*x))/d + a^2*d*cosh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^2)^2*cosh(c + d*x))/x^3, x, 12, -((b^2*cosh(c + d*x))/d^2) - (a^2*cosh(c + d*x))/(2*x^2) + 2*a*b*cosh(c)*CoshIntegral(d*x) + (a^2*d^2*cosh(c)*CoshIntegral(d*x))/2 - (a^2*d*sinh(c + d*x))/(2*x) + (b^2*x*sinh(c + d*x))/d + 2*a*b*sinh(c)*SinhIntegral(d*x) + (a^2*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x^2)^2*cosh(c + d*x))/x^4, x, 13, -(a^2*cosh(c + d*x))/(3*x^3) - (2*a*b*cosh(c + d*x))/x - (a^2*d^2*cosh(c + d*x))/(6*x) + 2*a*b*d*CoshIntegral(d*x)*sinh(c) + (a^2*d^3*CoshIntegral(d*x)*sinh(c))/6 + (b^2*sinh(c + d*x))/d - (a^2*d*sinh(c + d*x))/(6*x^2) + 2*a*b*d*cosh(c)*SinhIntegral(d*x) + (a^2*d^3*cosh(c)*SinhIntegral(d*x))/6]
    @test_int [((a + b*x^2)^2*cosh(c + d*x))/x^5, x, 17, -(a^2*cosh(c + d*x))/(4*x^4) - (a*b*cosh(c + d*x))/x^2 - (a^2*d^2*cosh(c + d*x))/(24*x^2) + b^2*cosh(c)*CoshIntegral(d*x) + a*b*d^2*cosh(c)*CoshIntegral(d*x) + (a^2*d^4*cosh(c)*CoshIntegral(d*x))/24 - (a^2*d*sinh(c + d*x))/(12*x^3) - (a*b*d*sinh(c + d*x))/x - (a^2*d^3*sinh(c + d*x))/(24*x) + b^2*sinh(c)*SinhIntegral(d*x) + a*b*d^2*sinh(c)*SinhIntegral(d*x) + (a^2*d^4*sinh(c)*SinhIntegral(d*x))/24]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^4*cosh(c + d*x))/(a + b*x^2), x, 14, (-2*x*cosh(c + d*x))/(b*d^2) + ((-a)^(3/2)*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^(5/2)) - ((-a)^(3/2)*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^(5/2)) + (2*sinh(c + d*x))/(b*d^3) - (a*sinh(c + d*x))/(b^2*d) + (x^2*sinh(c + d*x))/(b*d) - ((-a)^(3/2)*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^(5/2)) - ((-a)^(3/2)*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^(5/2))]
    @test_int [(x^3*cosh(c + d*x))/(a + b*x^2), x, 12, -(cosh(c + d*x)/(b*d^2)) - (a*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^2) - (a*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^2) + (x*sinh(c + d*x))/(b*d) + (a*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^2) - (a*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^2)]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x^2), x, 11, (sqrt(-a)*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^(3/2)) - (sqrt(-a)*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^(3/2)) + sinh(c + d*x)/(b*d) - (sqrt(-a)*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^(3/2)) - (sqrt(-a)*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^(3/2))]
    @test_int [(x*cosh(c + d*x))/(a + b*x^2), x, 8, (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b) + (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b) - (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b) + (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b)]
    @test_int [cosh(c + d*x)/(a + b*x^2), x, 8, (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*sqrt(-a)*sqrt(b)) - (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*sqrt(-a)*sqrt(b)) - (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*sqrt(-a)*sqrt(b)) - (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*sqrt(-a)*sqrt(b))]
    @test_int [cosh(c + d*x)/(x*(a + b*x^2)), x, 13, (cosh(c)*CoshIntegral(d*x))/a - (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a) - (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a) + (sinh(c)*SinhIntegral(d*x))/a + (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a) - (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a)]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x^2)), x, 14, -(cosh(c + d*x)/(a*x)) + (sqrt(b)*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*(-a)^(3/2)) - (sqrt(b)*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*(-a)^(3/2)) + (d*CoshIntegral(d*x)*sinh(c))/a + (d*cosh(c)*SinhIntegral(d*x))/a - (sqrt(b)*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*(-a)^(3/2)) - (sqrt(b)*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*(-a)^(3/2))]
    @test_int [cosh(c + d*x)/(x^3*(a + b*x^2)), x, 18, -cosh(c + d*x)/(2*a*x^2) - (b*cosh(c)*CoshIntegral(d*x))/a^2 + (d^2*cosh(c)*CoshIntegral(d*x))/(2*a) + (b*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^2) + (b*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^2) - (d*sinh(c + d*x))/(2*a*x) - (b*sinh(c)*SinhIntegral(d*x))/a^2 + (d^2*sinh(c)*SinhIntegral(d*x))/(2*a) - (b*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^2) + (b*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^2)]


    @test_int [(x^4*cosh(c + d*x))/(a + b*x^2)^2, x, 24, (x*cosh(c + d*x))/(2*b^2) - (x^3*cosh(c + d*x))/(2*b*(a + b*x^2)) + (3*sqrt(-a)*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^(5/2)) - (3*sqrt(-a)*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^(5/2)) - (a*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*b^3) - (a*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*b^3) + sinh(c + d*x)/(b^2*d) + (a*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^3) - (3*sqrt(-a)*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^(5/2)) - (a*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^3) - (3*sqrt(-a)*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^(5/2))]
    @test_int [(x^3*cosh(c + d*x))/(a + b*x^2)^2, x, 20, cosh(c + d*x)/(2*b^2) - (x^2*cosh(c + d*x))/(2*b*(a + b*x^2)) + (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^2) + (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^2) - (sqrt(-a)*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*b^(5/2)) + (sqrt(-a)*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*b^(5/2)) - (sqrt(-a)*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^(5/2)) - (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^2) - (sqrt(-a)*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^(5/2)) + (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^2)]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x^2)^2, x, 17, -(x*cosh(c + d*x))/(2*b*(a + b*x^2)) + (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*sqrt(-a)*b^(3/2)) - (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*sqrt(-a)*b^(3/2)) + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*b^2) + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*b^2) - (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^2) - (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*sqrt(-a)*b^(3/2)) + (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^2) - (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*sqrt(-a)*b^(3/2))]
    @test_int [(x*cosh(c + d*x))/(a + b*x^2)^2, x, 9, -cosh(c + d*x)/(2*b*(a + b*x^2)) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*sqrt(-a)*b^(3/2)) + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*sqrt(-a)*b^(3/2)) - (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*sqrt(-a)*b^(3/2)) - (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*sqrt(-a)*b^(3/2))]
    @test_int [cosh(c + d*x)/(a + b*x^2)^2, x, 18, -cosh(c + d*x)/(4*a*sqrt(b)*(sqrt(-a) - sqrt(b)*x)) + cosh(c + d*x)/(4*a*sqrt(b)*(sqrt(-a) + sqrt(b)*x)) - (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(3/2)*sqrt(b)) + (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(3/2)*sqrt(b)) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*a*b) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*a*b) + (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*a*b) + (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(3/2)*sqrt(b)) - (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*a*b) + (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(3/2)*sqrt(b))]
    @test_int [cosh(c + d*x)/(x*(a + b*x^2)^2), x, 22, cosh(c + d*x)/(2*a*(a + b*x^2)) + (cosh(c)*CoshIntegral(d*x))/a^2 - (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^2) - (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^2) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*(-a)^(3/2)*sqrt(b)) + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*(-a)^(3/2)*sqrt(b)) + (sinh(c)*SinhIntegral(d*x))/a^2 - (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(3/2)*sqrt(b)) + (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^2) - (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(3/2)*sqrt(b)) - (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^2)]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x^2)^2), x, 32, -(cosh(c + d*x)/(a^2*x)) + (sqrt(b)*cosh(c + d*x))/(4*a^2*(sqrt(-a) - sqrt(b)*x)) - (sqrt(b)*cosh(c + d*x))/(4*a^2*(sqrt(-a) + sqrt(b)*x)) - (3*sqrt(b)*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(5/2)) + (3*sqrt(b)*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(5/2)) + (d*CoshIntegral(d*x)*sinh(c))/a^2 + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(4*a^2) + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(4*a^2) + (d*cosh(c)*SinhIntegral(d*x))/a^2 - (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*a^2) + (3*sqrt(b)*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(5/2)) + (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*a^2) + (3*sqrt(b)*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(5/2))]


    @test_int [(x^3*cosh(c + d*x))/(a + b*x^2)^3, x, 27, -(x^2*cosh(c + d*x))/(4*b*(a + b*x^2)^2) - cosh(c + d*x)/(4*b^2*(a + b*x^2)) + (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*b^3) + (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*b^3) - (3*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*sqrt(-a)*b^(5/2)) + (3*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*sqrt(-a)*b^(5/2)) - (d*x*sinh(c + d*x))/(8*b^2*(a + b*x^2)) - (3*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*sqrt(-a)*b^(5/2)) - (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*b^3) - (3*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*sqrt(-a)*b^(5/2)) + (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*b^3)]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x^2)^3, x, 28, -cosh(c + d*x)/(16*a*b^(3/2)*(sqrt(-a) - sqrt(b)*x)) + cosh(c + d*x)/(16*a*b^(3/2)*(sqrt(-a) + sqrt(b)*x)) - (x*cosh(c + d*x))/(4*b*(a + b*x^2)^2) - (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*sqrt(-a)*b^(5/2)) + (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) - (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*sqrt(-a)*b^(5/2)) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*a*b^2) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*a*b^2) - (d*sinh(c + d*x))/(8*b^2*(a + b*x^2)) + (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a*b^2) + (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) - (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*sqrt(-a)*b^(5/2)) - (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a*b^2) + (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) - (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*sqrt(-a)*b^(5/2))]
    @test_int [(x*cosh(c + d*x))/(a + b*x^2)^3, x, 19, -cosh(c + d*x)/(4*b*(a + b*x^2)^2) - (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a*b^2) - (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a*b^2) + (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(3/2)*b^(3/2)) - (d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(3/2)*b^(3/2)) - (d*sinh(c + d*x))/(16*a*b^(3/2)*(sqrt(-a) - sqrt(b)*x)) + (d*sinh(c + d*x))/(16*a*b^(3/2)*(sqrt(-a) + sqrt(b)*x)) + (d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a*b^2) + (d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) - (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a*b^2)]
    @test_int [cosh(c + d*x)/(a + b*x^2)^3, x, 28, -cosh(c + d*x)/(16*(-a)^(3/2)*sqrt(b)*(sqrt(-a) - sqrt(b)*x)^2) - (3*cosh(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) - sqrt(b)*x)) + cosh(c + d*x)/(16*(-a)^(3/2)*sqrt(b)*(sqrt(-a) + sqrt(b)*x)^2) + (3*cosh(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) + sqrt(b)*x)) + (3*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) + (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) - (3*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) - (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) - (3*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*a^2*b) - (3*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*a^2*b) + (d*sinh(c + d*x))/(16*(-a)^(3/2)*b*(sqrt(-a) - sqrt(b)*x)) + (d*sinh(c + d*x))/(16*(-a)^(3/2)*b*(sqrt(-a) + sqrt(b)*x)) + (3*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^2*b) - (3*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) - (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) - (3*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^2*b) - (3*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) - (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2))]
    @test_int [cosh(c + d*x)/(x*(a + b*x^2)^3), x, 41, cosh(c + d*x)/(4*a*(a + b*x^2)^2) + cosh(c + d*x)/(2*a^2*(a + b*x^2)) + (cosh(c)*CoshIntegral(d*x))/a^3 - (cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^3) + (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^2*b) - (cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^3) + (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^2*b) + (5*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(5/2)*sqrt(b)) - (5*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(5/2)*sqrt(b)) + (d*sinh(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) - sqrt(b)*x)) - (d*sinh(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) + sqrt(b)*x)) + (sinh(c)*SinhIntegral(d*x))/a^3 + (5*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) + (sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^3) - (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^2*b) + (5*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) - (sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^3) + (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^2*b)]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x^2)^3), x, 60, -(cosh(c + d*x)/(a^3*x)) - (sqrt(b)*cosh(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) - sqrt(b)*x)^2) + (7*sqrt(b)*cosh(c + d*x))/(16*a^3*(sqrt(-a) - sqrt(b)*x)) + (sqrt(b)*cosh(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) + sqrt(b)*x)^2) - (7*sqrt(b)*cosh(c + d*x))/(16*a^3*(sqrt(-a) + sqrt(b)*x)) + (15*sqrt(b)*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(7/2)) + (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) - (15*sqrt(b)*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(7/2)) - (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) + (d*CoshIntegral(d*x)*sinh(c))/a^3 + (7*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*a^3) + (7*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*a^3) + (d*sinh(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) - sqrt(b)*x)) + (d*sinh(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) + sqrt(b)*x)) + (d*cosh(c)*SinhIntegral(d*x))/a^3 - (7*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^3) - (15*sqrt(b)*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(7/2)) - (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) + (7*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^3) - (15*sqrt(b)*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(7/2)) - (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b))]
    @test_int [cosh(c + d*x)/(x^3*(a + b*x^2)^3), x, 46, -cosh(c + d*x)/(2*a^3*x^2) - (b*cosh(c + d*x))/(4*a^2*(a + b*x^2)^2) - (b*cosh(c + d*x))/(a^3*(a + b*x^2)) - (3*b*cosh(c)*CoshIntegral(d*x))/a^4 + (d^2*cosh(c)*CoshIntegral(d*x))/(2*a^3) + (3*b*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^4) - (d^2*cosh(c + (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^3) + (3*b*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^4) - (d^2*cosh(c - (sqrt(-a)*d)/sqrt(b))*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^3) + (9*sqrt(b)*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sinh(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(7/2)) - (9*sqrt(b)*d*CoshIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sinh(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(7/2)) - (d*sinh(c + d*x))/(2*a^3*x) - (sqrt(b)*d*sinh(c + d*x))/(16*a^3*(sqrt(-a) - sqrt(b)*x)) + (sqrt(b)*d*sinh(c + d*x))/(16*a^3*(sqrt(-a) + sqrt(b)*x)) - (3*b*sinh(c)*SinhIntegral(d*x))/a^4 + (d^2*sinh(c)*SinhIntegral(d*x))/(2*a^3) + (9*sqrt(b)*d*cosh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(7/2)) - (3*b*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^4) + (d^2*sinh(c + (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^3) + (9*sqrt(b)*d*cosh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(7/2)) + (3*b*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^4) - (d^2*sinh(c - (sqrt(-a)*d)/sqrt(b))*SinhIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^3)]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^3)^p*cosh(c+d*x)=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^3*(a + b*x^3)*cosh(c + d*x), x, 13, (-6*a*cosh(c + d*x))/d^4 - (720*b*x*cosh(c + d*x))/d^6 - (3*a*x^2*cosh(c + d*x))/d^2 - (120*b*x^3*cosh(c + d*x))/d^4 - (6*b*x^5*cosh(c + d*x))/d^2 + (720*b*sinh(c + d*x))/d^7 + (6*a*x*sinh(c + d*x))/d^3 + (360*b*x^2*sinh(c + d*x))/d^5 + (a*x^3*sinh(c + d*x))/d + (30*b*x^4*sinh(c + d*x))/d^3 + (b*x^6*sinh(c + d*x))/d]
    @test_int [x^2*(a + b*x^3)*cosh(c + d*x), x, 11, (-120*b*cosh(c + d*x))/d^6 - (2*a*x*cosh(c + d*x))/d^2 - (60*b*x^2*cosh(c + d*x))/d^4 - (5*b*x^4*cosh(c + d*x))/d^2 + (2*a*sinh(c + d*x))/d^3 + (120*b*x*sinh(c + d*x))/d^5 + (a*x^2*sinh(c + d*x))/d + (20*b*x^3*sinh(c + d*x))/d^3 + (b*x^5*sinh(c + d*x))/d]
    @test_int [x^1*(a + b*x^3)*cosh(c + d*x), x, 9, -((a*cosh(c + d*x))/d^2) - (24*b*x*cosh(c + d*x))/d^4 - (4*b*x^3*cosh(c + d*x))/d^2 + (24*b*sinh(c + d*x))/d^5 + (a*x*sinh(c + d*x))/d + (12*b*x^2*sinh(c + d*x))/d^3 + (b*x^4*sinh(c + d*x))/d]
    @test_int [(a + b*x^3)*cosh(c + d*x), x, 7, (-6*b*cosh(c + d*x))/d^4 - (3*b*x^2*cosh(c + d*x))/d^2 + (a*sinh(c + d*x))/d + (6*b*x*sinh(c + d*x))/d^3 + (b*x^3*sinh(c + d*x))/d]
    @test_int [((a + b*x^3)*cosh(c + d*x))/x^1, x, 8, (-2*b*x*cosh(c + d*x))/d^2 + a*cosh(c)*CoshIntegral(d*x) + (2*b*sinh(c + d*x))/d^3 + (b*x^2*sinh(c + d*x))/d + a*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^3)*cosh(c + d*x))/x^2, x, 8, -((b*cosh(c + d*x))/d^2) - (a*cosh(c + d*x))/x + a*d*CoshIntegral(d*x)*sinh(c) + (b*x*sinh(c + d*x))/d + a*d*cosh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^3)*cosh(c + d*x))/x^3, x, 8, -(a*cosh(c + d*x))/(2*x^2) + (a*d^2*cosh(c)*CoshIntegral(d*x))/2 + (b*sinh(c + d*x))/d - (a*d*sinh(c + d*x))/(2*x) + (a*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x^3)*cosh(c + d*x))/x^4, x, 11, -(a*cosh(c + d*x))/(3*x^3) - (a*d^2*cosh(c + d*x))/(6*x) + b*cosh(c)*CoshIntegral(d*x) + (a*d^3*CoshIntegral(d*x)*sinh(c))/6 - (a*d*sinh(c + d*x))/(6*x^2) + (a*d^3*cosh(c)*SinhIntegral(d*x))/6 + b*sinh(c)*SinhIntegral(d*x)]


    @test_int [x^1*(a + b*x^3)^2*cosh(c + d*x), x, 17, (-5040*b^2*cosh(c + d*x))/d^8 - (a^2*cosh(c + d*x))/d^2 - (48*a*b*x*cosh(c + d*x))/d^4 - (2520*b^2*x^2*cosh(c + d*x))/d^6 - (8*a*b*x^3*cosh(c + d*x))/d^2 - (210*b^2*x^4*cosh(c + d*x))/d^4 - (7*b^2*x^6*cosh(c + d*x))/d^2 + (48*a*b*sinh(c + d*x))/d^5 + (5040*b^2*x*sinh(c + d*x))/d^7 + (a^2*x*sinh(c + d*x))/d + (24*a*b*x^2*sinh(c + d*x))/d^3 + (840*b^2*x^3*sinh(c + d*x))/d^5 + (2*a*b*x^4*sinh(c + d*x))/d + (42*b^2*x^5*sinh(c + d*x))/d^3 + (b^2*x^7*sinh(c + d*x))/d]
    @test_int [(a + b*x^3)^2*cosh(c + d*x), x, 14, (-12*a*b*cosh(c + d*x))/d^4 - (720*b^2*x*cosh(c + d*x))/d^6 - (6*a*b*x^2*cosh(c + d*x))/d^2 - (120*b^2*x^3*cosh(c + d*x))/d^4 - (6*b^2*x^5*cosh(c + d*x))/d^2 + (720*b^2*sinh(c + d*x))/d^7 + (a^2*sinh(c + d*x))/d + (12*a*b*x*sinh(c + d*x))/d^3 + (360*b^2*x^2*sinh(c + d*x))/d^5 + (2*a*b*x^3*sinh(c + d*x))/d + (30*b^2*x^4*sinh(c + d*x))/d^3 + (b^2*x^6*sinh(c + d*x))/d]
    @test_int [((a + b*x^3)^2*cosh(c + d*x))/x^1, x, 14, (-120*b^2*cosh(c + d*x))/d^6 - (4*a*b*x*cosh(c + d*x))/d^2 - (60*b^2*x^2*cosh(c + d*x))/d^4 - (5*b^2*x^4*cosh(c + d*x))/d^2 + a^2*cosh(c)*CoshIntegral(d*x) + (4*a*b*sinh(c + d*x))/d^3 + (120*b^2*x*sinh(c + d*x))/d^5 + (2*a*b*x^2*sinh(c + d*x))/d + (20*b^2*x^3*sinh(c + d*x))/d^3 + (b^2*x^5*sinh(c + d*x))/d + a^2*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^3)^2*cosh(c + d*x))/x^2, x, 13, (-2*a*b*cosh(c + d*x))/d^2 - (a^2*cosh(c + d*x))/x - (24*b^2*x*cosh(c + d*x))/d^4 - (4*b^2*x^3*cosh(c + d*x))/d^2 + a^2*d*CoshIntegral(d*x)*sinh(c) + (24*b^2*sinh(c + d*x))/d^5 + (2*a*b*x*sinh(c + d*x))/d + (12*b^2*x^2*sinh(c + d*x))/d^3 + (b^2*x^4*sinh(c + d*x))/d + a^2*d*cosh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^3)^2*cosh(c + d*x))/x^3, x, 12, (-6*b^2*cosh(c + d*x))/d^4 - (a^2*cosh(c + d*x))/(2*x^2) - (3*b^2*x^2*cosh(c + d*x))/d^2 + (a^2*d^2*cosh(c)*CoshIntegral(d*x))/2 + (2*a*b*sinh(c + d*x))/d - (a^2*d*sinh(c + d*x))/(2*x) + (6*b^2*x*sinh(c + d*x))/d^3 + (b^2*x^3*sinh(c + d*x))/d + (a^2*d^2*sinh(c)*SinhIntegral(d*x))/2]
    @test_int [((a + b*x^3)^2*cosh(c + d*x))/x^4, x, 14, -(a^2*cosh(c + d*x))/(3*x^3) - (a^2*d^2*cosh(c + d*x))/(6*x) - (2*b^2*x*cosh(c + d*x))/d^2 + 2*a*b*cosh(c)*CoshIntegral(d*x) + (a^2*d^3*CoshIntegral(d*x)*sinh(c))/6 + (2*b^2*sinh(c + d*x))/d^3 - (a^2*d*sinh(c + d*x))/(6*x^2) + (b^2*x^2*sinh(c + d*x))/d + (a^2*d^3*cosh(c)*SinhIntegral(d*x))/6 + 2*a*b*sinh(c)*SinhIntegral(d*x)]
    @test_int [((a + b*x^3)^2*cosh(c + d*x))/x^5, x, 15, -((b^2*cosh(c + d*x))/d^2) - (a^2*cosh(c + d*x))/(4*x^4) - (a^2*d^2*cosh(c + d*x))/(24*x^2) - (2*a*b*cosh(c + d*x))/x + (a^2*d^4*cosh(c)*CoshIntegral(d*x))/24 + 2*a*b*d*CoshIntegral(d*x)*sinh(c) - (a^2*d*sinh(c + d*x))/(12*x^3) - (a^2*d^3*sinh(c + d*x))/(24*x) + (b^2*x*sinh(c + d*x))/d + 2*a*b*d*cosh(c)*SinhIntegral(d*x) + (a^2*d^4*sinh(c)*SinhIntegral(d*x))/24]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^4*cosh(c + d*x))/(a + b*x^3), x, 15, -(cosh(c + d*x)/(b*d^2)) + ((-1)^(2/3)*a^(2/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*b^(5/3)) + (a^(2/3)*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(5/3)) + (x*sinh(c + d*x))/(b*d) - ((-1)^(2/3)*a^(2/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b^(5/3)) + (a^(2/3)*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(5/3))]
    @test_int [(x^3*cosh(c + d*x))/(a + b*x^3), x, 14, ((-1)^(1/3)*a^(1/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*b^(4/3)) - (a^(1/3)*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(4/3)) + sinh(c + d*x)/(b*d) - ((-1)^(1/3)*a^(1/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b^(4/3)) - (a^(1/3)*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(4/3))]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x^3), x, 11, (cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b) + (cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*b) + (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b) - (sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b) + (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b) + (sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*b)]
    @test_int [(x^1*cosh(c + d*x))/(a + b*x^3), x, 11, -(((-1)^(2/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(1/3)*b^(2/3))) + ((-1)^(1/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*a^(1/3)*b^(2/3)) - (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(1/3)*b^(2/3)) + ((-1)^(2/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(1/3)*b^(2/3)) - (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(1/3)*b^(2/3)) + ((-1)^(1/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(1/3)*b^(2/3))]
    @test_int [cosh(c + d*x)/(a + b*x^3), x, 11, -(((-1)^(1/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(2/3)*b^(1/3))) + ((-1)^(2/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*a^(2/3)*b^(1/3)) + (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(2/3)*b^(1/3)) + ((-1)^(1/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(2/3)*b^(1/3)) + (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(2/3)*b^(1/3)) + ((-1)^(2/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(2/3)*b^(1/3))]
    @test_int [cosh(c + d*x)/(x^1*(a + b*x^3)), x, 16, (cosh(c)*CoshIntegral(d*x))/a - (cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a) - (cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*a) - (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a) + (sinh(c)*SinhIntegral(d*x))/a + (sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a) - (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a) - (sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a)]
    @test_int [cosh(c + d*x)/(x^2*(a + b*x^3)), x, 17, -(cosh(c + d*x)/(a*x)) + ((-1)^(2/3)*b^(1/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*a^(4/3)) + (b^(1/3)*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(4/3)) + (d*CoshIntegral(d*x)*sinh(c))/a + (d*cosh(c)*SinhIntegral(d*x))/a - ((-1)^(2/3)*b^(1/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(4/3)) + (b^(1/3)*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(4/3))]
    @test_int [cosh(c + d*x)/(x^3*(a + b*x^3)), x, 18, -(cosh(c + d*x)/(2*a*x^2)) + (d^2*cosh(c)*CoshIntegral(d*x))/(2*a) + ((-1)^(1/3)*b^(2/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*a^(5/3)) - (b^(2/3)*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(5/3)) - (d*sinh(c + d*x))/(2*a*x) + (d^2*sinh(c)*SinhIntegral(d*x))/(2*a) - ((-1)^(1/3)*b^(2/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(5/3)) - (b^(2/3)*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(5/3))]


    @test_int [(x^3*cosh(c + d*x))/(a + b*x^3)^2, x, 23, -((x*cosh(c + d*x))/(3*b*(a + b*x^3))) - ((-1)^(1/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(9*a^(2/3)*b^(4/3)) + (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) - (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(1/3)*b^(5/3)) - ((-1)^(2/3)*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(1/3)*b^(5/3)) + ((-1)^(1/3)*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(1/3)*b^(5/3)) + ((-1)^(2/3)*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(1/3)*b^(5/3)) + ((-1)^(1/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(2/3)*b^(4/3)) - (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(1/3)*b^(5/3)) + (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) + ((-1)^(1/3)*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(1/3)*b^(5/3)) + ((-1)^(2/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3))]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x^3)^2, x, 12, -(cosh(c + d*x)/(3*b*(a + b*x^3))) + (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(2/3)*b^(4/3)) - ((-1)^(1/3)*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(2/3)*b^(4/3)) + ((-1)^(1/3)*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(2/3)*b^(4/3)) + (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3))]
    @test_int [(x^1*cosh(c + d*x))/(a + b*x^3)^2, x, 34, cosh(c + d*x)/(3*a*b*x) - cosh(c + d*x)/(3*b*x*(a + b*x^3)) - ((-1)^(2/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(4/3)*b^(2/3)) + ((-1)^(1/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(9*a^(4/3)*b^(2/3)) - (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) - (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(9*a*b) - (d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a*b) - (d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a*b) + (d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a*b) + ((-1)^(2/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(4/3)*b^(2/3)) - (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a*b) - (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) - (d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a*b) + ((-1)^(1/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3))]
    @test_int [cosh(c + d*x)/(a + b*x^3)^2, x, 36, cosh(c + d*x)/(3*a*b*x^2) - cosh(c + d*x)/(3*b*x^2*(a + b*x^3)) - (2*(-1)^(1/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(5/3)*b^(1/3)) + (2*(-1)^(2/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(9*a^(5/3)*b^(1/3)) + (2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) + (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(4/3)*b^(2/3)) + ((-1)^(2/3)*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(4/3)*b^(2/3)) - ((-1)^(1/3)*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(4/3)*b^(2/3)) - ((-1)^(2/3)*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(4/3)*b^(2/3)) + (2*(-1)^(1/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(5/3)*b^(1/3)) + (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) + (2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) - ((-1)^(1/3)*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) + (2*(-1)^(2/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3))]
    @test_int [cosh(c + d*x)/(x^1*(a + b*x^3)^2), x, 41, cosh(c + d*x)/(3*a*b*x^3) - cosh(c + d*x)/(3*b*x^3*(a + b*x^3)) + (cosh(c)*CoshIntegral(d*x))/a^2 - (cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^2) - (cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(3*a^2) - (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^2) - (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(5/3)*b^(1/3)) + ((-1)^(1/3)*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(5/3)*b^(1/3)) - ((-1)^(2/3)*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(5/3)*b^(1/3)) + (sinh(c)*SinhIntegral(d*x))/a^2 - ((-1)^(1/3)*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(5/3)*b^(1/3)) + (sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^2) - (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) - (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^2) - ((-1)^(2/3)*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) - (sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^2)]


    @test_int [(x^5*cosh(c + d*x))/(a + b*x^3)^3, x, 36, -((x^3*cosh(c + d*x))/(6*b*(a + b*x^3)^2)) - cosh(c + d*x)/(6*b^2*(a + b*x^3)) - ((-1)^(2/3)*d^2*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(1/3)*b^(8/3)) + ((-1)^(1/3)*d^2*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(54*a^(1/3)*b^(8/3)) - (d^2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(1/3)*b^(8/3)) + (2*d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(27*a^(2/3)*b^(7/3)) - (2*(-1)^(1/3)*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(2/3)*b^(7/3)) + (2*(-1)^(2/3)*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(2/3)*b^(7/3)) - (d*x*sinh(c + d*x))/(18*b^2*(a + b*x^3)) + (2*(-1)^(1/3)*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(2/3)*b^(7/3)) + ((-1)^(2/3)*d^2*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(1/3)*b^(8/3)) + (2*d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(2/3)*b^(7/3)) - (d^2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(1/3)*b^(8/3)) + (2*(-1)^(2/3)*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(2/3)*b^(7/3)) + ((-1)^(1/3)*d^2*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(1/3)*b^(8/3))]
    @test_int [(x^4*cosh(c + d*x))/(a + b*x^3)^3, x, 47, cosh(c + d*x)/(9*a*b^2*x) - (x^2*cosh(c + d*x))/(6*b*(a + b*x^3)^2) - cosh(c + d*x)/(9*b^2*x*(a + b*x^3)) - ((-1)^(2/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(4/3)*b^(5/3)) - ((-1)^(1/3)*d^2*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(2/3)*b^(7/3)) + ((-1)^(1/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(27*a^(4/3)*b^(5/3)) + ((-1)^(2/3)*d^2*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(54*a^(2/3)*b^(7/3)) - (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(4/3)*b^(5/3)) + (d^2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(2/3)*b^(7/3)) - (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(27*a*b^2) - (d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a*b^2) - (d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a*b^2) - (d*sinh(c + d*x))/(18*b^2*(a + b*x^3)) + (d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a*b^2) + ((-1)^(2/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(4/3)*b^(5/3)) + ((-1)^(1/3)*d^2*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(2/3)*b^(7/3)) - (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a*b^2) - (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(4/3)*b^(5/3)) + (d^2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(2/3)*b^(7/3)) - (d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a*b^2) + ((-1)^(1/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(4/3)*b^(5/3)) + ((-1)^(2/3)*d^2*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(2/3)*b^(7/3))]
    @test_int [(x^3*cosh(c + d*x))/(a + b*x^3)^3, x, 71, cosh(c + d*x)/(18*a*b^2*x^2) - (x*cosh(c + d*x))/(6*b*(a + b*x^3)^2) - cosh(c + d*x)/(18*b^2*x^2*(a + b*x^3)) - ((-1)^(1/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a*b^2) + ((-1)^(2/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(54*a*b^2) + (cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a*b^2) + (d*sinh(c + d*x))/(18*a*b^2*x) - (d*sinh(c + d*x))/(18*b^2*x*(a + b*x^3)) + ((-1)^(1/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(5/3)*b^(4/3)) + (d^2*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a*b^2) + (sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a*b^2) + ((-1)^(2/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a*b^2)]
    @test_int [(x^2*cosh(c + d*x))/(a + b*x^3)^3, x, 37, -(cosh(c + d*x)/(6*b*(a + b*x^3)^2)) + ((-1)^(2/3)*d^2*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(4/3)*b^(5/3)) - ((-1)^(1/3)*d^2*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(54*a^(4/3)*b^(5/3)) + (d^2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(4/3)*b^(5/3)) + (d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(27*a^(5/3)*b^(4/3)) - ((-1)^(1/3)*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(5/3)*b^(4/3)) + ((-1)^(2/3)*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(5/3)*b^(4/3)) + (d*sinh(c + d*x))/(18*a*b^2*x^2) - (d*sinh(c + d*x))/(18*b^2*x^2*(a + b*x^3)) + ((-1)^(1/3)*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(5/3)*b^(4/3)) - ((-1)^(2/3)*d^2*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(4/3)*b^(5/3)) + (d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) + (d^2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(4/3)*b^(5/3)) + ((-1)^(2/3)*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) - ((-1)^(1/3)*d^2*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(4/3)*b^(5/3))]
    @test_int [(x^1*cosh(c + d*x))/(a + b*x^3)^3, x, 89, -(cosh(c + d*x)/(18*a*b^2*x^4)) + (2*cosh(c + d*x))/(9*a^2*b*x) - cosh(c + d*x)/(6*b*x*(a + b*x^3)^2) + cosh(c + d*x)/(18*b^2*x^4*(a + b*x^3)) - (2*(-1)^(2/3)*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(7/3)*b^(2/3)) + ((-1)^(1/3)*d^2*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(5/3)*b^(4/3)) + (2*(-1)^(1/3)*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(27*a^(7/3)*b^(2/3)) - ((-1)^(2/3)*d^2*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x))/(54*a^(5/3)*b^(4/3)) - (2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(7/3)*b^(2/3)) - (d^2*cosh(c - (a^(1/3)*d)/b^(1/3))*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(5/3)*b^(4/3)) - (2*d*CoshIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sinh(c - (a^(1/3)*d)/b^(1/3)))/(27*a^2*b) - (2*d*CoshIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a^2*b) - (2*d*CoshIntegral(-(((-1)^(2/3)*a^(1/3)*d)/b^(1/3)) - d*x)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a^2*b) + (d*sinh(c + d*x))/(18*a*b^2*x^3) - (d*sinh(c + d*x))/(18*b^2*x^3*(a + b*x^3)) + (2*d*cosh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^2*b) + (2*(-1)^(2/3)*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(7/3)*b^(2/3)) - ((-1)^(1/3)*d^2*sinh(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(5/3)*b^(4/3)) - (2*d*cosh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^2*b) - (2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(7/3)*b^(2/3)) - (d^2*sinh(c - (a^(1/3)*d)/b^(1/3))*SinhIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(5/3)*b^(4/3)) - (2*d*cosh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^2*b) + (2*(-1)^(1/3)*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(7/3)*b^(2/3)) - ((-1)^(2/3)*d^2*sinh(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinhIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(5/3)*b^(4/3))]
    end
