include("8.1 Error functions.jl")
include("8.10 Bessel functions.jl")
include("8.2 Fresnel integral functions.jl")
include("8.3 Exponential integral functions.jl")
include("8.4 Trig integral functions.jl")
include("8.5 Hyperbolic integral functions.jl")
include("8.6 Gamma functions.jl")
include("8.7 Zeta function.jl")
include("8.8 Polylogarithm function.jl")
include("8.9 Product logarithm function.jl")
