int_rules_8_4 = @theory begin

    #= ::Subsection::Closed:: =#
    #= 8.4*Trig*integral*functions =#
    @apply_utils Antiderivative(SinIntegral(~(a') + ~(b') * ~x), ~x) => ((~a + ~b * ~x) * SinIntegral(~a + ~b * ~x)) / ~b + cos(~a + ~b * ~x) / ~b <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative(CosIntegral(~(a') + ~(b') * ~x), ~x) => ((~a + ~b * ~x) * CosIntegral(~a + ~b * ~x)) / ~b - sin(~a + ~b * ~x) / ~b <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative(SinIntegral(~(b') * ~x) / ~x, ~x) => (1 / 2) * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], -im * ~b * ~x) + (1 / 2) * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], im * ~b * ~x) <-- FreeQ(~b, ~x)
    @apply_utils Antiderivative(CosIntegral(~(b') * ~x) / ~x, ~x) => (-1 / 2) * im * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], -im * ~b * ~x) + (1 / 2) * im * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], im * ~b * ~x) + EulerGamma * log(~x) + (1 / 2) * log(~b * ~x) ^ 2 <-- FreeQ(~b, ~x)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * SinIntegral(~(a') + ~(b') * ~x), ~x) => ((~c + ~d * ~x) ^ (~m + 1) * SinIntegral(~a + ~b * ~x)) / (~d * (~m + 1)) - (~b / (~d * (~m + 1))) * Antiderivative(((~c + ~d * ~x) ^ (~m + 1) * sin(~a + ~b * ~x)) / (~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~m], ~x) && NeQ(~m, -1)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * CosIntegral(~(a') + ~(b') * ~x), ~x) => ((~c + ~d * ~x) ^ (~m + 1) * CosIntegral(~a + ~b * ~x)) / (~d * (~m + 1)) - (~b / (~d * (~m + 1))) * Antiderivative(((~c + ~d * ~x) ^ (~m + 1) * cos(~a + ~b * ~x)) / (~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~m], ~x) && NeQ(~m, -1)
    @apply_utils Antiderivative(SinIntegral(~(a') + ~(b') * ~x) ^ 2, ~x) => ((~a + ~b * ~x) * SinIntegral(~a + ~b * ~x) ^ 2) / ~b - 2 * Antiderivative(sin(~a + ~b * ~x) * SinIntegral(~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative(CosIntegral(~(a') + ~(b') * ~x) ^ 2, ~x) => ((~a + ~b * ~x) * CosIntegral(~a + ~b * ~x) ^ 2) / ~b - 2 * Antiderivative(cos(~a + ~b * ~x) * CosIntegral(~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative((~x) ^ ~(m') * SinIntegral(~(b') * ~x) ^ 2, ~x) => ((~x) ^ (~m + 1) * SinIntegral(~b * ~x) ^ 2) / (~m + 1) - (2 / (~m + 1)) * Antiderivative((~x) ^ ~m * sin(~b * ~x) * SinIntegral(~b * ~x), ~x) <-- FreeQ(~b, ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~x) ^ ~(m') * CosIntegral(~(b') * ~x) ^ 2, ~x) => ((~x) ^ (~m + 1) * CosIntegral(~b * ~x) ^ 2) / (~m + 1) - (2 / (~m + 1)) * Antiderivative((~x) ^ ~m * cos(~b * ~x) * CosIntegral(~b * ~x), ~x) <-- FreeQ(~b, ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * SinIntegral(~a + ~(b') * ~x) ^ 2, ~x) => (((~a + ~b * ~x) * (~c + ~d * ~x) ^ ~m * SinIntegral(~a + ~b * ~x) ^ 2) / (~b * (~m + 1)) - (2 / (~m + 1)) * Antiderivative((~c + ~d * ~x) ^ ~m * sin(~a + ~b * ~x) * SinIntegral(~a + ~b * ~x), ~x)) + (((~b * ~c - ~a * ~d) * ~m) / (~b * (~m + 1))) * Antiderivative((~c + ~d * ~x) ^ (~m - 1) * SinIntegral(~a + ~b * ~x) ^ 2, ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * CosIntegral(~a + ~(b') * ~x) ^ 2, ~x) => (((~a + ~b * ~x) * (~c + ~d * ~x) ^ ~m * CosIntegral(~a + ~b * ~x) ^ 2) / (~b * (~m + 1)) - (2 / (~m + 1)) * Antiderivative((~c + ~d * ~x) ^ ~m * cos(~a + ~b * ~x) * CosIntegral(~a + ~b * ~x), ~x)) + (((~b * ~c - ~a * ~d) * ~m) / (~b * (~m + 1))) * Antiderivative((~c + ~d * ~x) ^ (~m - 1) * CosIntegral(~a + ~b * ~x) ^ 2, ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x) && IGtQ(~m, 0)
    #= Antiderivative((~x)^(~m')*SinIntegral((~a)+(~b')*(~x))^2,~x) :=  b*x^(m+2)*SinIntegral(a+b*x)^2/(a*(m+1)) + x^(m+1)*SinIntegral(a+b*x)^2/(m+1) - 2*b/(a*(m+1))*Antiderivative(x^(m+1)*sin(a+b*x)*SinIntegral(a+b*x),x) - b*(m+2)/(a*(m+1))*Antiderivative(x^(m+1)*SinIntegral(a+b*x)^2,x) <--  FreeQ([a,b],x) && ILtQ(m,-2) =#
    #= Antiderivative((~x)^(~m')*CosIntegral((~a)+(~b')*(~x))^2,~x) :=  b*x^(m+2)*CosIntegral(a+b*x)^2/(a*(m+1)) + x^(m+1)*CosIntegral(a+b*x)^2/(m+1) - 2*b/(a*(m+1))*Antiderivative(x^(m+1)*cos(a+b*x)*CosIntegral(a+b*x),x) - b*(m+2)/(a*(m+1))*Antiderivative(x^(m+1)*CosIntegral(a+b*x)^2,x) <--  FreeQ([a,b],x) && ILtQ(m,-2) =#
    @apply_utils Antiderivative(sin(~(a') + ~(b') * ~x) * SinIntegral(~(c') + ~(d') * ~x), ~x) => (-(cos(~a + ~b * ~x)) * SinIntegral(~c + ~d * ~x)) / ~b + (~d / ~b) * Antiderivative((cos(~a + ~b * ~x) * sin(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative(cos(~(a') + ~(b') * ~x) * CosIntegral(~(c') + ~(d') * ~x), ~x) => (sin(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative((sin(~a + ~b * ~x) * cos(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * sin(~(a') + ~(b') * ~x) * SinIntegral(~(c') + ~(d') * ~x), ~x) => (-((~e + ~f * ~x) ^ ~m) * cos(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x)) / ~b + (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * cos(~a + ~b * ~x) * sin(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) + ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * cos(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cos(~(a') + ~(b') * ~x) * CosIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ ~m * sin(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * sin(~a + ~b * ~x) * cos(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * sin(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~m * sin(~(a') + ~(b') * ~x) * SinIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * sin(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * sin(~a + ~b * ~x) * sin(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * cos(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cos(~(a') + ~(b') * ~x) * CosIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * cos(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * cos(~a + ~b * ~x) * cos(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) + (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * sin(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative(cos(~(a') + ~(b') * ~x) * SinIntegral(~(c') + ~(d') * ~x), ~x) => (sin(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative((sin(~a + ~b * ~x) * sin(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative(sin(~(a') + ~(b') * ~x) * CosIntegral(~(c') + ~(d') * ~x), ~x) => (-(cos(~a + ~b * ~x)) * CosIntegral(~c + ~d * ~x)) / ~b + (~d / ~b) * Antiderivative((cos(~a + ~b * ~x) * cos(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cos(~(a') + ~(b') * ~x) * SinIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ ~m * sin(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * sin(~a + ~b * ~x) * sin(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * sin(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * sin(~(a') + ~(b') * ~x) * CosIntegral(~(c') + ~(d') * ~x), ~x) => (-((~e + ~f * ~x) ^ ~m) * cos(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x)) / ~b + (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * cos(~a + ~b * ~x) * cos(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) + ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * cos(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cos(~(a') + ~(b') * ~x) * SinIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * cos(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * cos(~a + ~b * ~x) * sin(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) + (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * sin(~a + ~b * ~x) * SinIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~m * sin(~(a') + ~(b') * ~x) * CosIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * sin(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * sin(~a + ~b * ~x) * cos(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * cos(~a + ~b * ~x) * CosIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative(SinIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ~x * SinIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n))) - ~b * ~d * ~n * Antiderivative(sin(~d * (~a + ~b * log(~c * (~x) ^ ~n))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~n], ~x)
    @apply_utils Antiderivative(CosIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ~x * CosIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n))) - ~b * ~d * ~n * Antiderivative(cos(~d * (~a + ~b * log(~c * (~x) ^ ~n))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~n], ~x)
    @apply_utils Antiderivative((~F)(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))) / ~x, ~x) => (1 / ~n) * Subst((~F)(~d * (~a + ~b * ~x)), ~x, log(~c * (~x) ^ ~n)) <-- FreeQ([~a, ~b, ~c, ~d, ~n], ~x) && MemberQ([SinIntegral, CosIntegral], ~x)
    @apply_utils Antiderivative((~(e') * ~x) ^ ~(m') * SinIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ((~e * ~x) ^ (~m + 1) * SinIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~e * (~m + 1)) - ((~b * ~d * ~n) / (~m + 1)) * Antiderivative(((~e * ~x) ^ ~m * sin(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~m, ~n], ~x) && NeQ(~m, -1)
    @apply_utils Antiderivative((~(e') * ~x) ^ ~(m') * CosIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ((~e * ~x) ^ (~m + 1) * CosIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~e * (~m + 1)) - ((~b * ~d * ~n) / (~m + 1)) * Antiderivative(((~e * ~x) ^ ~m * cos(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~m, ~n], ~x) && NeQ(~m, -1)
end
