int_rules_8_5 = @theory begin

    #= ::Subsection::Closed:: =#
    #= 8.5*Hyperbolic*integral*functions =#
    @apply_utils Antiderivative(SinhIntegral(~(a') + ~(b') * ~x), ~x) => ((~a + ~b * ~x) * SinhIntegral(~a + ~b * ~x)) / ~b - cosh(~a + ~b * ~x) / ~b <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative(CoshIntegral(~(a') + ~(b') * ~x), ~x) => ((~a + ~b * ~x) * CoshIntegral(~a + ~b * ~x)) / ~b - sinh(~a + ~b * ~x) / ~b <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative(SinhIntegral(~(b') * ~x) / ~x, ~x) => (1 / 2) * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], -(~b) * ~x) + (1 / 2) * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], ~b * ~x) <-- FreeQ(~b, ~x)
    @apply_utils Antiderivative(CoshIntegral(~(b') * ~x) / ~x, ~x) => (-1 / 2) * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], -(~b) * ~x) + (1 / 2) * ~b * ~x * HypergeometricPFQ([1, 1, 1], [2, 2, 2], ~b * ~x) + EulerGamma * log(~x) + (1 / 2) * log(~b * ~x) ^ 2 <-- FreeQ(~b, ~x)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * SinhIntegral(~(a') + ~(b') * ~x), ~x) => ((~c + ~d * ~x) ^ (~m + 1) * SinhIntegral(~a + ~b * ~x)) / (~d * (~m + 1)) - (~b / (~d * (~m + 1))) * Antiderivative(((~c + ~d * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x)) / (~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~m], ~x) && NeQ(~m, -1)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * CoshIntegral(~(a') + ~(b') * ~x), ~x) => ((~c + ~d * ~x) ^ (~m + 1) * CoshIntegral(~a + ~b * ~x)) / (~d * (~m + 1)) - (~b / (~d * (~m + 1))) * Antiderivative(((~c + ~d * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x)) / (~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~m], ~x) && NeQ(~m, -1)
    @apply_utils Antiderivative(SinhIntegral(~(a') + ~(b') * ~x) ^ 2, ~x) => ((~a + ~b * ~x) * SinhIntegral(~a + ~b * ~x) ^ 2) / ~b - 2 * Antiderivative(sinh(~a + ~b * ~x) * SinhIntegral(~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative(CoshIntegral(~(a') + ~(b') * ~x) ^ 2, ~x) => ((~a + ~b * ~x) * CoshIntegral(~a + ~b * ~x) ^ 2) / ~b - 2 * Antiderivative(cosh(~a + ~b * ~x) * CoshIntegral(~a + ~b * ~x), ~x) <-- FreeQ([~a, ~b], ~x)
    @apply_utils Antiderivative((~x) ^ ~(m') * SinhIntegral(~(b') * ~x) ^ 2, ~x) => ((~x) ^ (~m + 1) * SinhIntegral(~b * ~x) ^ 2) / (~m + 1) - (2 / (~m + 1)) * Antiderivative((~x) ^ ~m * sinh(~b * ~x) * SinhIntegral(~b * ~x), ~x) <-- FreeQ(~b, ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~x) ^ ~(m') * CoshIntegral(~(b') * ~x) ^ 2, ~x) => ((~x) ^ (~m + 1) * CoshIntegral(~b * ~x) ^ 2) / (~m + 1) - (2 / (~m + 1)) * Antiderivative((~x) ^ ~m * cosh(~b * ~x) * CoshIntegral(~b * ~x), ~x) <-- FreeQ(~b, ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * SinhIntegral(~a + ~(b') * ~x) ^ 2, ~x) => (((~a + ~b * ~x) * (~c + ~d * ~x) ^ ~m * SinhIntegral(~a + ~b * ~x) ^ 2) / (~b * (~m + 1)) - (2 / (~m + 1)) * Antiderivative((~c + ~d * ~x) ^ ~m * sinh(~a + ~b * ~x) * SinhIntegral(~a + ~b * ~x), ~x)) + (((~b * ~c - ~a * ~d) * ~m) / (~b * (~m + 1))) * Antiderivative((~c + ~d * ~x) ^ (~m - 1) * SinhIntegral(~a + ~b * ~x) ^ 2, ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(c') + ~(d') * ~x) ^ ~(m') * CoshIntegral(~a + ~(b') * ~x) ^ 2, ~x) => (((~a + ~b * ~x) * (~c + ~d * ~x) ^ ~m * CoshIntegral(~a + ~b * ~x) ^ 2) / (~b * (~m + 1)) - (2 / (~m + 1)) * Antiderivative((~c + ~d * ~x) ^ ~m * cosh(~a + ~b * ~x) * CoshIntegral(~a + ~b * ~x), ~x)) + (((~b * ~c - ~a * ~d) * ~m) / (~b * (~m + 1))) * Antiderivative((~c + ~d * ~x) ^ (~m - 1) * CoshIntegral(~a + ~b * ~x) ^ 2, ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x) && IGtQ(~m, 0)
    #= Antiderivative((~x)^(~m')*SinhIntegral((~a)+(~b')*(~x))^2,~x) :=  b*x^(m+2)*SinhIntegral(a+b*x)^2/(a*(m+1)) + x^(m+1)*SinhIntegral(a+b*x)^2/(m+1) - 2*b/(a*(m+1))*Antiderivative(x^(m+1)*sinh(a+b*x)*SinhIntegral(a+b*x),x) - b*(m+2)/(a*(m+1))*Antiderivative(x^(m+1)*SinhIntegral(a+b*x)^2,x) <--  FreeQ([a,b],x) && ILtQ(m,-2) =#
    #= Antiderivative((~x)^(~m')*CoshIntegral((~a)+(~b')*(~x))^2,~x) :=  b*x^(m+2)*CoshIntegral(a+b*x)^2/(a*(m+1)) + x^(m+1)*CoshIntegral(a+b*x)^2/(m+1) - 2*b/(a*(m+1))*Antiderivative(x^(m+1)*cosh(a+b*x)*CoshIntegral(a+b*x),x) - b*(m+2)/(a*(m+1))*Antiderivative(x^(m+1)*CoshIntegral(a+b*x)^2,x) <--  FreeQ([a,b],x) && ILtQ(m,-2) =#
    @apply_utils Antiderivative(sinh(~(a') + ~(b') * ~x) * SinhIntegral(~(c') + ~(d') * ~x), ~x) => (cosh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative((cosh(~a + ~b * ~x) * sinh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative(cosh(~(a') + ~(b') * ~x) * CoshIntegral(~(c') + ~(d') * ~x), ~x) => (sinh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative((sinh(~a + ~b * ~x) * cosh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * sinh(~(a') + ~(b') * ~x) * SinhIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ ~m * cosh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * cosh(~a + ~b * ~x) * sinh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * cosh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cosh(~(a') + ~(b') * ~x) * CoshIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ ~m * sinh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * sinh(~a + ~b * ~x) * cosh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * sinh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~m * sinh(~(a') + ~(b') * ~x) * SinhIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x) * sinh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cosh(~(a') + ~(b') * ~x) * CoshIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x) * cosh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative(cosh(~(a') + ~(b') * ~x) * SinhIntegral(~(c') + ~(d') * ~x), ~x) => (sinh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative((sinh(~a + ~b * ~x) * sinh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative(sinh(~(a') + ~(b') * ~x) * CoshIntegral(~(c') + ~(d') * ~x), ~x) => (cosh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative((cosh(~a + ~b * ~x) * cosh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d], ~x)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cosh(~(a') + ~(b') * ~x) * SinhIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ ~m * sinh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * sinh(~a + ~b * ~x) * sinh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * sinh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * sinh(~(a') + ~(b') * ~x) * CoshIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ ~m * cosh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x)) / ~b - (~d / ~b) * Antiderivative(((~e + ~f * ~x) ^ ~m * cosh(~a + ~b * ~x) * cosh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - ((~f * ~m) / ~b) * Antiderivative((~e + ~f * ~x) ^ (~m - 1) * cosh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~(m') * cosh(~(a') + ~(b') * ~x) * SinhIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x) * sinh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x) * SinhIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative((~(e') + ~(f') * ~x) ^ ~m * sinh(~(a') + ~(b') * ~x) * CoshIntegral(~(c') + ~(d') * ~x), ~x) => (((~e + ~f * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x)) / (~f * (~m + 1)) - (~d / (~f * (~m + 1))) * Antiderivative(((~e + ~f * ~x) ^ (~m + 1) * sinh(~a + ~b * ~x) * cosh(~c + ~d * ~x)) / (~c + ~d * ~x), ~x)) - (~b / (~f * (~m + 1))) * Antiderivative((~e + ~f * ~x) ^ (~m + 1) * cosh(~a + ~b * ~x) * CoshIntegral(~c + ~d * ~x), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~f], ~x) && ILtQ(~m, -1)
    @apply_utils Antiderivative(SinhIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ~x * SinhIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n))) - ~b * ~d * ~n * Antiderivative(sinh(~d * (~a + ~b * log(~c * (~x) ^ ~n))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~n], ~x)
    @apply_utils Antiderivative(CoshIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ~x * CoshIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n))) - ~b * ~d * ~n * Antiderivative(cosh(~d * (~a + ~b * log(~c * (~x) ^ ~n))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~n], ~x)
    @apply_utils Antiderivative((~F)(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))) / ~x, ~x) => (1 / ~n) * Subst((~F)(~d * (~a + ~b * ~x)), ~x, log(~c * (~x) ^ ~n)) <-- FreeQ([~a, ~b, ~c, ~d, ~n], ~x) && MemberQ([SinhIntegral, CoshIntegral], ~x)
    @apply_utils Antiderivative((~(e') * ~x) ^ ~(m') * SinhIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ((~e * ~x) ^ (~m + 1) * SinhIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~e * (~m + 1)) - ((~b * ~d * ~n) / (~m + 1)) * Antiderivative(((~e * ~x) ^ ~m * sinh(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~m, ~n], ~x) && NeQ(~m, -1)
    @apply_utils Antiderivative((~(e') * ~x) ^ ~(m') * CoshIntegral(~(d') * (~(a') + ~(b') * log(~(c') * (~x) ^ ~(n')))), ~x) => ((~e * ~x) ^ (~m + 1) * CoshIntegral(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~e * (~m + 1)) - ((~b * ~d * ~n) / (~m + 1)) * Antiderivative(((~e * ~x) ^ ~m * cosh(~d * (~a + ~b * log(~c * (~x) ^ ~n)))) / (~d * (~a + ~b * log(~c * (~x) ^ ~n))), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~e, ~m, ~n], ~x) && NeQ(~m, -1)
end
