@testset "4.2.1.2 (g sin)^p (a+b cos)^m" begin
    (a, b, c, d, e, x, ) = @variables a b c d e x

    #= ::Package:: =#

    #= ::Title:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^p*(a+b*cos(e+f*x))^m=#


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^p*(a+b*cos(e+f*x))^m*when*a^2-b^2=0=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*sin(e+f*x)^p*(a+a*cos(e+f*x))^m=#


    @test_int [sin(x)^4/(a + a*cos(x)), x, 3, x/(2*a) - (cos(x)*sin(x))/(2*a) - sin(x)^3/(3*a)]
    @test_int [sin(x)^3/(a + a*cos(x)), x, 2, -(cos(x)/a) + cos(x)^2/(2*a)]
    @test_int [sin(x)^2/(a + a*cos(x)), x, 2, x/a - sin(x)/a]
    @test_int [sin(x)^1/(a + a*cos(x)), x, 2, -(log(1 + cos(x))/a)]
    @test_int [sin(x)^0/(a + a*cos(x)), x, 1, sin(x)/(a + a*cos(x))]
    @test_int [csc(x)^1/(a + a*cos(x)), x, 4, -(atanh(cos(x))/(2*a)) + 1/(2*(a + a*cos(x)))]
    @test_int [csc(x)^2/(a + a*cos(x)), x, 3, -((2*cot(x))/(3*a)) + csc(x)/(3*(a + a*cos(x)))]
    @test_int [csc(x)^3/(a + a*cos(x)), x, 4, -((3*atanh(cos(x)))/(8*a)) - 1/(8*(a - a*cos(x))) + a/(8*(a + a*cos(x))^2) + 1/(4*(a + a*cos(x)))]
    @test_int [csc(x)^4/(a + a*cos(x)), x, 3, -((4*cot(x))/(5*a)) - (4*cot(x)^3)/(15*a) + csc(x)^3/(5*(a + a*cos(x)))]


    @test_int [sin(2*x)/(1 + cos(2*x)), x, 2, -log(cos(x)), (-(1/2))*log(1 + cos(2*x))]
    @test_int [sin(2*x)/(1 - cos(2*x)), x, 2, log(sin(x)), (1/2)*log(1 - cos(2*x))]


    @test_int [sin(x)/(1 + cos(x))^2, x, 2, 1/(1 + cos(x))]
    @test_int [sin(x)/(1 - cos(x))^2, x, 2, -(1/(1 - cos(x)))]
    @test_int [sin(x)^2/(1 + cos(x))^2, x, 2, -x + (2*sin(x))/(1 + cos(x))]
    @test_int [sin(x)^2/(1 - cos(x))^2, x, 2, -x - (2*sin(x))/(1 - cos(x))]
    @test_int [sin(x)^3/(1 + cos(x))^2, x, 3, cos(x) - 2*log(1 + cos(x))]
    @test_int [sin(x)^3/(1 - cos(x))^2, x, 3, cos(x) + 2*log(1 - cos(x))]


    @test_int [sin(x)/(1 + cos(x))^3, x, 2, 1/(2*(1 + cos(x))^2)]
    @test_int [sin(x)/(1 - cos(x))^3, x, 2, -(1/(2*(1 - cos(x))^2))]
    @test_int [sin(x)^2/(1 + cos(x))^3, x, 1, sin(x)^3/(3*(1 + cos(x))^3)]
    @test_int [sin(x)^2/(1 - cos(x))^3, x, 1, -(sin(x)^3/(3*(1 - cos(x))^3))]
    @test_int [sin(x)^3/(1 + cos(x))^3, x, 3, 2/(1 + cos(x)) + log(1 + cos(x))]
    @test_int [sin(x)^3/(1 - cos(x))^3, x, 3, -(2/(1 - cos(x))) - log(1 - cos(x))]


    #= ::Subsection:: =#
    #=Integrands*of*the*form*sin(e+f*x)^p*(a+a*cos(e+f*x))^(m/2)=#


    #= ::Subsection:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^(p/2)*(a+a*cos(e+f*x))^m=#


    #= ::Subsection:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^(p/2)*(a+a*cos(e+f*x))^(m/2)=#


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^p*(a+b*cos(e+f*x))^m=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*sin(e+f*x)^p*(a+b*cos(e+f*x))^m=#


    #= ::Subsubsection:: =#
    #=n>0=#


    #= ::Subsubsection::Closed:: =#
    #=n<0=#


    @test_int [sin(x)^4/(a + b*cos(x)), x, 5, -((a*(2*a^2 - 3*b^2)*x)/(2*b^4)) + (2*(a - b)^(3/2)*(a + b)^(3/2)*atan((sqrt(a - b)*tan(x/2))/sqrt(a + b)))/b^4 + ((2*(a^2 - b^2) - a*b*cos(x))*sin(x))/(2*b^3) - sin(x)^3/(3*b)]
    @test_int [sin(x)^3/(a + b*cos(x)), x, 3, -((a*cos(x))/b^2) + cos(x)^2/(2*b) + ((a^2 - b^2)*log(a + b*cos(x)))/b^3]
    @test_int [sin(x)^2/(a + b*cos(x)), x, 4, (a*x)/b^2 - (2*sqrt(a - b)*sqrt(a + b)*atan((sqrt(a - b)*tan(x/2))/sqrt(a + b)))/b^2 - sin(x)/b]
    @test_int [sin(x)^1/(a + b*cos(x)), x, 2, -(log(a + b*cos(x))/b)]
    @test_int [sin(x)^0/(a + b*cos(x)), x, 2, (2*atan((sqrt(a - b)*tan(x/2))/sqrt(a + b)))/(sqrt(a - b)*sqrt(a + b))]
    @test_int [csc(x)^1/(a + b*cos(x)), x, 6, log(1 - cos(x))/(2*(a + b)) - log(1 + cos(x))/(2*(a - b)) + (b*log(a + b*cos(x)))/(a^2 - b^2)]
    @test_int [csc(x)^2/(a + b*cos(x)), x, 4, -((2*b^2*atan((sqrt(a - b)*tan(x/2))/sqrt(a + b)))/((a - b)^(3/2)*(a + b)^(3/2))) + ((b - a*cos(x))*csc(x))/(a^2 - b^2)]
    @test_int [csc(x)^3/(a + b*cos(x)), x, 4, ((b - a*cos(x))*csc(x)^2)/(2*(a^2 - b^2)) + ((a + 2*b)*log(1 - cos(x)))/(4*(a + b)^2) - ((a - 2*b)*log(1 + cos(x)))/(4*(a - b)^2) - (b^3*log(a + b*cos(x)))/(a^2 - b^2)^2]
    @test_int [csc(x)^4/(a + b*cos(x)), x, 5, (2*b^4*atan((sqrt(a - b)*tan(x/2))/sqrt(a + b)))/((a - b)^(5/2)*(a + b)^(5/2)) - ((3*b^3 + a*(2*a^2 - 5*b^2)*cos(x))*csc(x))/(3*(a^2 - b^2)^2) + ((b - a*cos(x))*csc(x)^3)/(3*(a^2 - b^2))]


    #= ::Subsection:: =#
    #=Integrands*of*the*form*sin(e+f*x)^p*(a+b*cos(e+f*x))^(m/2)=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^(p/2)*(a+b*cos(e+f*x))^m=#


    #= ::Subsubsection::Closed:: =#
    #=m>0=#


    @test_int [(a + b*cos(c + d*x))*(e*sin(c + d*x))^(7/2), x, 5, (10*a*e^4*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(21*d*sqrt(e*sin(c + d*x))) - (10*a*e^3*cos(c + d*x)*sqrt(e*sin(c + d*x)))/(21*d) - (2*a*e*cos(c + d*x)*(e*sin(c + d*x))^(5/2))/(7*d) + (2*b*(e*sin(c + d*x))^(9/2))/(9*d*e)]
    @test_int [(a + b*cos(c + d*x))*(e*sin(c + d*x))^(5/2), x, 4, (6*a*e^2*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*d*sqrt(sin(c + d*x))) - (2*a*e*cos(c + d*x)*(e*sin(c + d*x))^(3/2))/(5*d) + (2*b*(e*sin(c + d*x))^(7/2))/(7*d*e)]
    @test_int [(a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2), x, 4, (2*a*e^2*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*d*sqrt(e*sin(c + d*x))) - (2*a*e*cos(c + d*x)*sqrt(e*sin(c + d*x)))/(3*d) + (2*b*(e*sin(c + d*x))^(5/2))/(5*d*e)]
    @test_int [(a + b*cos(c + d*x))*(e*sin(c + d*x))^(1/2), x, 3, (2*a*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(d*sqrt(sin(c + d*x))) + (2*b*(e*sin(c + d*x))^(3/2))/(3*d*e)]
    @test_int [(a + b*cos(c + d*x))/(e*sin(c + d*x))^(1/2), x, 3, (2*a*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(d*sqrt(e*sin(c + d*x))) + (2*b*sqrt(e*sin(c + d*x)))/(d*e)]
    @test_int [(a + b*cos(c + d*x))/(e*sin(c + d*x))^(3/2), x, 4, (-2*b)/(d*e*sqrt(e*sin(c + d*x))) - (2*a*cos(c + d*x))/(d*e*sqrt(e*sin(c + d*x))) - (2*a*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(d*e^2*sqrt(sin(c + d*x)))]
    @test_int [(a + b*cos(c + d*x))/(e*sin(c + d*x))^(5/2), x, 4, (-2*b)/(3*d*e*(e*sin(c + d*x))^(3/2)) - (2*a*cos(c + d*x))/(3*d*e*(e*sin(c + d*x))^(3/2)) + (2*a*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*d*e^2*sqrt(e*sin(c + d*x)))]
    @test_int [(a + b*cos(c + d*x))/(e*sin(c + d*x))^(7/2), x, 5, (-2*b)/(5*d*e*(e*sin(c + d*x))^(5/2)) - (2*a*cos(c + d*x))/(5*d*e*(e*sin(c + d*x))^(5/2)) - (6*a*cos(c + d*x))/(5*d*e^3*sqrt(e*sin(c + d*x))) - (6*a*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*d*e^4*sqrt(sin(c + d*x)))]


    @test_int [(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(7/2), x, 6, (10*(11*a^2 + 2*b^2)*e^4*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(231*d*sqrt(e*sin(c + d*x))) - (10*(11*a^2 + 2*b^2)*e^3*cos(c + d*x)*sqrt(e*sin(c + d*x)))/(231*d) - (2*(11*a^2 + 2*b^2)*e*cos(c + d*x)*(e*sin(c + d*x))^(5/2))/(77*d) + (26*a*b*(e*sin(c + d*x))^(9/2))/(99*d*e) + (2*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(9/2))/(11*d*e)]
    @test_int [(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(5/2), x, 5, (2*(9*a^2 + 2*b^2)*e^2*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(15*d*sqrt(sin(c + d*x))) - (2*(9*a^2 + 2*b^2)*e*cos(c + d*x)*(e*sin(c + d*x))^(3/2))/(45*d) + (22*a*b*(e*sin(c + d*x))^(7/2))/(63*d*e) + (2*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(7/2))/(9*d*e)]
    @test_int [(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(3/2), x, 5, (2*(7*a^2 + 2*b^2)*e^2*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(21*d*sqrt(e*sin(c + d*x))) - (2*(7*a^2 + 2*b^2)*e*cos(c + d*x)*sqrt(e*sin(c + d*x)))/(21*d) + (18*a*b*(e*sin(c + d*x))^(5/2))/(35*d*e) + (2*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(5/2))/(7*d*e)]
    @test_int [(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(1/2), x, 4, (2*(5*a^2 + 2*b^2)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*d*sqrt(sin(c + d*x))) + (14*a*b*(e*sin(c + d*x))^(3/2))/(15*d*e) + (2*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(5*d*e)]
    @test_int [(a + b*cos(c + d*x))^2/(e*sin(c + d*x))^(1/2), x, 4, (2*(3*a^2 + 2*b^2)*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*d*sqrt(e*sin(c + d*x))) + (10*a*b*sqrt(e*sin(c + d*x)))/(3*d*e) + (2*b*(a + b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(3*d*e)]
    @test_int [(a + b*cos(c + d*x))^2/(e*sin(c + d*x))^(3/2), x, 4, (-2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x)))/(d*e*sqrt(e*sin(c + d*x))) - (2*(a^2 + 2*b^2)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(d*e^2*sqrt(sin(c + d*x))) - (2*a*b*(e*sin(c + d*x))^(3/2))/(d*e^3)]
    @test_int [(a + b*cos(c + d*x))^2/(e*sin(c + d*x))^(5/2), x, 4, (-2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x)))/(3*d*e*(e*sin(c + d*x))^(3/2)) + (2*(a^2 - 2*b^2)*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*d*e^2*sqrt(e*sin(c + d*x))) - (2*a*b*sqrt(e*sin(c + d*x)))/(3*d*e^3)]
    @test_int [(a + b*cos(c + d*x))^2/(e*sin(c + d*x))^(7/2), x, 5, (-2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x)))/(5*d*e*(e*sin(c + d*x))^(5/2)) - (2*a*b)/(5*d*e^3*sqrt(e*sin(c + d*x))) - (2*(3*a^2 - 2*b^2)*cos(c + d*x))/(5*d*e^3*sqrt(e*sin(c + d*x))) - (2*(3*a^2 - 2*b^2)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*d*e^4*sqrt(sin(c + d*x)))]


    @test_int [(a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(7/2), x, 7, (10*a*(11*a^2 + 6*b^2)*e^4*Elliptic.F((1/2)*(c - pi/2 + d*x), 2)*sqrt(sin(c + d*x)))/(231*d*sqrt(e*sin(c + d*x))) - (10*a*(11*a^2 + 6*b^2)*e^3*cos(c + d*x)*sqrt(e*sin(c + d*x)))/(231*d) - (2*a*(11*a^2 + 6*b^2)*e*cos(c + d*x)*(e*sin(c + d*x))^(5/2))/(77*d) + (2*b*(177*a^2 + 44*b^2)*(e*sin(c + d*x))^(9/2))/(1287*d*e) + (34*a*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(9/2))/(143*d*e) + (2*b*(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(9/2))/(13*d*e)]
    @test_int [(a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(5/2), x, 6, (2*a*(3*a^2 + 2*b^2)*e^2*Elliptic.E((1/2)*(c - pi/2 + d*x), 2)*sqrt(e*sin(c + d*x)))/(5*d*sqrt(sin(c + d*x))) - (2*a*(3*a^2 + 2*b^2)*e*cos(c + d*x)*(e*sin(c + d*x))^(3/2))/(15*d) + (2*b*(43*a^2 + 12*b^2)*(e*sin(c + d*x))^(7/2))/(231*d*e) + (10*a*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(7/2))/(33*d*e) + (2*b*(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(7/2))/(11*d*e)]
    @test_int [(a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(3/2), x, 6, (2*a*(7*a^2 + 6*b^2)*e^2*Elliptic.F((1/2)*(c - pi/2 + d*x), 2)*sqrt(sin(c + d*x)))/(21*d*sqrt(e*sin(c + d*x))) - (2*a*(7*a^2 + 6*b^2)*e*cos(c + d*x)*sqrt(e*sin(c + d*x)))/(21*d) + (2*b*(89*a^2 + 28*b^2)*(e*sin(c + d*x))^(5/2))/(315*d*e) + (26*a*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(5/2))/(63*d*e) + (2*b*(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(5/2))/(9*d*e)]
    @test_int [(a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(1/2), x, 5, (2*a*(5*a^2 + 6*b^2)*Elliptic.E((1/2)*(c - pi/2 + d*x), 2)*sqrt(e*sin(c + d*x)))/(5*d*sqrt(sin(c + d*x))) + (2*b*(57*a^2 + 20*b^2)*(e*sin(c + d*x))^(3/2))/(105*d*e) + (22*a*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(35*d*e) + (2*b*(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(3/2))/(7*d*e)]
    @test_int [(a + b*cos(c + d*x))^3/(e*sin(c + d*x))^(1/2), x, 5, (2*a*(a^2 + 2*b^2)*Elliptic.F((1/2)*(c - pi/2 + d*x), 2)*sqrt(sin(c + d*x)))/(d*sqrt(e*sin(c + d*x))) + (2*b*(11*a^2 + 4*b^2)*sqrt(e*sin(c + d*x)))/(5*d*e) + (6*a*b*(a + b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(5*d*e) + (2*b*(a + b*cos(c + d*x))^2*sqrt(e*sin(c + d*x)))/(5*d*e)]
    @test_int [(a + b*cos(c + d*x))^3/(e*sin(c + d*x))^(3/2), x, 5, -((2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x))^2)/(d*e*sqrt(e*sin(c + d*x)))) - (2*a*(a^2 + 6*b^2)*Elliptic.E((1/2)*(c - pi/2 + d*x), 2)*sqrt(e*sin(c + d*x)))/(d*e^2*sqrt(sin(c + d*x))) - (2*b*(3*a^2 + 4*b^2)*(e*sin(c + d*x))^(3/2))/(3*d*e^3) - (2*a*b*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(d*e^3)]
    @test_int [(a + b*cos(c + d*x))^3/(e*sin(c + d*x))^(5/2), x, 5, -((2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x))^2)/(3*d*e*(e*sin(c + d*x))^(3/2))) + (2*a*(a^2 - 6*b^2)*Elliptic.F((1/2)*(c - pi/2 + d*x), 2)*sqrt(sin(c + d*x)))/(3*d*e^2*sqrt(e*sin(c + d*x))) - (2*b*(a^2 + 4*b^2)*sqrt(e*sin(c + d*x)))/(3*d*e^3) - (2*a*b*(a + b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(3*d*e^3)]
    @test_int [(a + b*cos(c + d*x))^3/(e*sin(c + d*x))^(7/2), x, 5, -((2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x))^2)/(5*d*e*(e*sin(c + d*x))^(5/2))) + (2*(a + b*cos(c + d*x))*(a*b - (3*a^2 - 4*b^2)*cos(c + d*x)))/(5*d*e^3*sqrt(e*sin(c + d*x))) - (6*a*(a^2 - 2*b^2)*Elliptic.E((1/2)*(c - pi/2 + d*x), 2)*sqrt(e*sin(c + d*x)))/(5*d*e^4*sqrt(sin(c + d*x))) - (2*b*(3*a^2 - 4*b^2)*(e*sin(c + d*x))^(3/2))/(5*d*e^5)]
    @test_int [(a + b*cos(c + d*x))^3/(e*sin(c + d*x))^(9/2), x, 5, -((2*(b + a*cos(c + d*x))*(a + b*cos(c + d*x))^2)/(7*d*e*(e*sin(c + d*x))^(7/2))) - (2*(a + b*cos(c + d*x))*(a*b + (5*a^2 - 4*b^2)*cos(c + d*x)))/(21*d*e^3*(e*sin(c + d*x))^(3/2)) + (2*a*(5*a^2 - 6*b^2)*Elliptic.F((1/2)*(c - pi/2 + d*x), 2)*sqrt(sin(c + d*x)))/(21*d*e^4*sqrt(e*sin(c + d*x))) - (2*b*(5*a^2 - 4*b^2)*sqrt(e*sin(c + d*x)))/(21*d*e^5)]


    #= ::Subsubsection::Closed:: =#
    #=m<0=#


    @test_int [(e*sin(c + d*x))^(11/2)/(a + b*cos(c + d*x)), x, 15, ((-a^2 + b^2)^(9/4)*e^(11/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(11/2)*d) + ((-a^2 + b^2)^(9/4)*e^(11/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(11/2)*d) + (2*a*(21*a^4 - 49*a^2*b^2 + 33*b^4)*e^6*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(21*b^6*d*sqrt(e*sin(c + d*x))) - (a*(a^2 - b^2)^3*e^6*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^6*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (a*(a^2 - b^2)^3*e^6*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^6*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (2*e^5*(21*(a^2 - b^2)^2 - a*b*(7*a^2 - 12*b^2)*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(21*b^5*d) + (2*e^3*(7*(a^2 - b^2) - 5*a*b*cos(c + d*x))*(e*sin(c + d*x))^(5/2))/(35*b^3*d) - (2*e*(e*sin(c + d*x))^(9/2))/(9*b*d)]
    @test_int [(e*sin(c + d*x))^(9/2)/(a + b*cos(c + d*x)), x, 14, -(((-a^2 + b^2)^(7/4)*e^(9/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(9/2)*d)) + ((-a^2 + b^2)^(7/4)*e^(9/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(9/2)*d) + (a*(a^2 - b^2)^2*e^5*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^5*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (a*(a^2 - b^2)^2*e^5*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^5*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (2*a*(5*a^2 - 8*b^2)*e^4*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*b^4*d*sqrt(sin(c + d*x))) + (2*e^3*(5*(a^2 - b^2) - 3*a*b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(15*b^3*d) - (2*e*(e*sin(c + d*x))^(7/2))/(7*b*d)]
    @test_int [(e*sin(c + d*x))^(7/2)/(a + b*cos(c + d*x)), x, 14, ((-a^2 + b^2)^(5/4)*e^(7/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(7/2)*d) + ((-a^2 + b^2)^(5/4)*e^(7/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(7/2)*d) - (2*a*(3*a^2 - 4*b^2)*e^4*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*b^4*d*sqrt(e*sin(c + d*x))) + (a*(a^2 - b^2)^2*e^4*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^4*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (a*(a^2 - b^2)^2*e^4*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^4*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (2*e^3*(3*(a^2 - b^2) - a*b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(3*b^3*d) - (2*e*(e*sin(c + d*x))^(5/2))/(5*b*d)]
    @test_int [(e*sin(c + d*x))^(5/2)/(a + b*cos(c + d*x)), x, 13, -(((-a^2 + b^2)^(3/4)*e^(5/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(5/2)*d)) + ((-a^2 + b^2)^(3/4)*e^(5/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(5/2)*d) - (a*(a^2 - b^2)*e^3*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^3*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (a*(a^2 - b^2)*e^3*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^3*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (2*a*e^2*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(b^2*d*sqrt(sin(c + d*x))) - (2*e*(e*sin(c + d*x))^(3/2))/(3*b*d)]
    @test_int [(e*sin(c + d*x))^(3/2)/(a + b*cos(c + d*x)), x, 13, ((-a^2 + b^2)^(1/4)*e^(3/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(3/2)*d) + ((-a^2 + b^2)^(1/4)*e^(3/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(b^(3/2)*d) + (2*a*e^2*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^2*d*sqrt(e*sin(c + d*x))) - (a*(a^2 - b^2)*e^2*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^2*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (a*(a^2 - b^2)*e^2*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^2*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (2*e*sqrt(e*sin(c + d*x)))/(b*d)]
    @test_int [(e*sin(c + d*x))^(1/2)/(a + b*cos(c + d*x)), x, 9, -((sqrt(e)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(sqrt(b)*(-a^2 + b^2)^(1/4)*d)) + (sqrt(e)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(sqrt(b)*(-a^2 + b^2)^(1/4)*d) + (a*e*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (a*e*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))*(e*sin(c + d*x))^(1/2)), x, 9, (sqrt(b)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(3/4)*d*sqrt(e)) + (sqrt(b)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(3/4)*d*sqrt(e)) + (a*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (a*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2)), x, 13, -((b^(3/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(5/4)*d*e^(3/2))) + (b^(3/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(5/4)*d*e^(3/2)) + (2*(b - a*cos(c + d*x)))/((a^2 - b^2)*d*e*sqrt(e*sin(c + d*x))) - (a*b*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)*(b - sqrt(-a^2 + b^2))*d*e*sqrt(e*sin(c + d*x))) - (a*b*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)*(b + sqrt(-a^2 + b^2))*d*e*sqrt(e*sin(c + d*x))) - (2*a*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/((a^2 - b^2)*d*e^2*sqrt(sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))*(e*sin(c + d*x))^(5/2)), x, 13, (b^(5/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(7/4)*d*e^(5/2)) + (b^(5/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(7/4)*d*e^(5/2)) + (2*(b - a*cos(c + d*x)))/(3*(a^2 - b^2)*d*e*(e*sin(c + d*x))^(3/2)) + (2*a*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*(a^2 - b^2)*d*e^2*sqrt(e*sin(c + d*x))) - (a*b^2*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*e^2*sqrt(e*sin(c + d*x))) - (a*b^2*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*e^2*sqrt(e*sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))*(e*sin(c + d*x))^(7/2)), x, 14, -((b^(7/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(9/4)*d*e^(7/2))) + (b^(7/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/((-a^2 + b^2)^(9/4)*d*e^(7/2)) + (2*(b - a*cos(c + d*x)))/(5*(a^2 - b^2)*d*e*(e*sin(c + d*x))^(5/2)) - (2*(5*b^3 + a*(3*a^2 - 8*b^2)*cos(c + d*x)))/(5*(a^2 - b^2)^2*d*e^3*sqrt(e*sin(c + d*x))) + (a*b^3*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)^2*(b - sqrt(-a^2 + b^2))*d*e^3*sqrt(e*sin(c + d*x))) + (a*b^3*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)^2*(b + sqrt(-a^2 + b^2))*d*e^3*sqrt(e*sin(c + d*x))) - (2*a*(3*a^2 - 8*b^2)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*(a^2 - b^2)^2*d*e^4*sqrt(sin(c + d*x)))]


    @test_int [(e*sin(c + d*x))^(11/2)/(a + b*cos(c + d*x))^2, x, 15, (9*a*(-a^2 + b^2)^(5/4)*e^(11/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(11/2)*d) + (9*a*(-a^2 + b^2)^(5/4)*e^(11/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(11/2)*d) - (3*(21*a^4 - 28*a^2*b^2 + 5*b^4)*e^6*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(7*b^6*d*sqrt(e*sin(c + d*x))) + (9*a^2*(a^2 - b^2)^2*e^6*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^6*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (9*a^2*(a^2 - b^2)^2*e^6*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^6*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (3*e^5*(21*a*(a^2 - b^2) - b*(7*a^2 - 5*b^2)*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(7*b^5*d) - (9*e^3*(7*a - 5*b*cos(c + d*x))*(e*sin(c + d*x))^(5/2))/(35*b^3*d) + (e*(e*sin(c + d*x))^(9/2))/(b*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(9/2)/(a + b*cos(c + d*x))^2, x, 14, (-7*a*(-a^2 + b^2)^(3/4)*e^(9/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(9/2)*d) + (7*a*(-a^2 + b^2)^(3/4)*e^(9/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(9/2)*d) - (7*a^2*(a^2 - b^2)*e^5*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^5*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (7*a^2*(a^2 - b^2)*e^5*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^5*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (7*(5*a^2 - 3*b^2)*e^4*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*b^4*d*sqrt(sin(c + d*x))) - (7*e^3*(5*a - 3*b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(15*b^3*d) + (e*(e*sin(c + d*x))^(7/2))/(b*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(7/2)/(a + b*cos(c + d*x))^2, x, 14, (5*a*(-a^2 + b^2)^(1/4)*e^(7/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(7/2)*d) + (5*a*(-a^2 + b^2)^(1/4)*e^(7/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(7/2)*d) + (5*(3*a^2 - b^2)*e^4*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*b^4*d*sqrt(e*sin(c + d*x))) - (5*a^2*(a^2 - b^2)*e^4*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^4*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (5*a^2*(a^2 - b^2)*e^4*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^4*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (5*e^3*(3*a - b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(3*b^3*d) + (e*(e*sin(c + d*x))^(5/2))/(b*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(5/2)/(a + b*cos(c + d*x))^2, x, 13, (-3*a*e^(5/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(5/2)*(-a^2 + b^2)^(1/4)*d) + (3*a*e^(5/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(5/2)*(-a^2 + b^2)^(1/4)*d) + (3*a^2*e^3*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^3*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (3*a^2*e^3*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^3*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (3*e^2*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(b^2*d*sqrt(sin(c + d*x))) + (e*(e*sin(c + d*x))^(3/2))/(b*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(3/2)/(a + b*cos(c + d*x))^2, x, 13, (a*e^(3/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(3/2)*(-a^2 + b^2)^(3/4)*d) + (a*e^(3/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*b^(3/2)*(-a^2 + b^2)^(3/4)*d) - (e^2*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(b^2*d*sqrt(e*sin(c + d*x))) + (a^2*e^2*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^2*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (a^2*e^2*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b^2*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (e*sqrt(e*sin(c + d*x)))/(b*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(1/2)/(a + b*cos(c + d*x))^2, x, 13, (a*sqrt(e)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*sqrt(b)*(-a^2 + b^2)^(5/4)*d) - (a*sqrt(e)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*sqrt(b)*(-a^2 + b^2)^(5/4)*d) + (a^2*e*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b*(a^2 - b^2)*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (a^2*e*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*b*(a^2 - b^2)*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/((a^2 - b^2)*d*sqrt(sin(c + d*x))) - (b*(e*sin(c + d*x))^(3/2))/((a^2 - b^2)*d*e*(a + b*cos(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(1/2)), x, 13, (-3*a*sqrt(b)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(7/4)*d*sqrt(e)) - (3*a*sqrt(b)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(7/4)*d*sqrt(e)) - (Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/((a^2 - b^2)*d*sqrt(e*sin(c + d*x))) + (3*a^2*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (3*a^2*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (b*sqrt(e*sin(c + d*x)))/((a^2 - b^2)*d*e*(a + b*cos(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(3/2)), x, 14, (5*a*b^(3/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(9/4)*d*e^(3/2)) - (5*a*b^(3/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(9/4)*d*e^(3/2)) - b/((a^2 - b^2)*d*e*(a + b*cos(c + d*x))*sqrt(e*sin(c + d*x))) + (5*a*b - (2*a^2 + 3*b^2)*cos(c + d*x))/((a^2 - b^2)^2*d*e*sqrt(e*sin(c + d*x))) - (5*a^2*b*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)^2*(b - sqrt(-a^2 + b^2))*d*e*sqrt(e*sin(c + d*x))) - (5*a^2*b*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)^2*(b + sqrt(-a^2 + b^2))*d*e*sqrt(e*sin(c + d*x))) - ((2*a^2 + 3*b^2)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/((a^2 - b^2)^2*d*e^2*sqrt(sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(5/2)), x, 14, (-7*a*b^(5/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(11/4)*d*e^(5/2)) - (7*a*b^(5/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(11/4)*d*e^(5/2)) - b/((a^2 - b^2)*d*e*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2)) + (7*a*b - (2*a^2 + 5*b^2)*cos(c + d*x))/(3*(a^2 - b^2)^2*d*e*(e*sin(c + d*x))^(3/2)) + ((2*a^2 + 5*b^2)*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(3*(a^2 - b^2)^2*d*e^2*sqrt(e*sin(c + d*x))) - (7*a^2*b^2*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)^2*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*e^2*sqrt(e*sin(c + d*x))) - (7*a^2*b^2*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)^2*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*e^2*sqrt(e*sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(7/2)), x, 15, (9*a*b^(7/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(13/4)*d*e^(7/2)) - (9*a*b^(7/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(2*(-a^2 + b^2)^(13/4)*d*e^(7/2)) - b/((a^2 - b^2)*d*e*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(5/2)) + (9*a*b - (2*a^2 + 7*b^2)*cos(c + d*x))/(5*(a^2 - b^2)^2*d*e*(e*sin(c + d*x))^(5/2)) - (3*(15*a*b^3 + (2*a^4 - 10*a^2*b^2 - 7*b^4)*cos(c + d*x)))/(5*(a^2 - b^2)^3*d*e^3*sqrt(e*sin(c + d*x))) + (9*a^2*b^3*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)^3*(b - sqrt(-a^2 + b^2))*d*e^3*sqrt(e*sin(c + d*x))) + (9*a^2*b^3*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(2*(a^2 - b^2)^3*(b + sqrt(-a^2 + b^2))*d*e^3*sqrt(e*sin(c + d*x))) - (3*(2*a^4 - 10*a^2*b^2 - 7*b^4)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(5*(a^2 - b^2)^3*d*e^4*sqrt(sin(c + d*x)))]


    @test_int [(e*sin(c + d*x))^(13/2)/(a + b*cos(c + d*x))^3, x, 15, (11*(9*a^4 - 11*a^2*b^2 + 2*b^4)*e^(13/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(13/2)*(-a^2 + b^2)^(1/4)*d) - (11*(9*a^4 - 11*a^2*b^2 + 2*b^4)*e^(13/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(13/2)*(-a^2 + b^2)^(1/4)*d) - (11*a*(9*a^4 - 11*a^2*b^2 + 2*b^4)*e^7*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^7*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (11*a*(9*a^4 - 11*a^2*b^2 + 2*b^4)*e^7*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^7*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (11*a*(45*a^2 - 37*b^2)*e^6*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(20*b^6*d*sqrt(sin(c + d*x))) - (11*e^5*(5*(9*a^2 - 2*b^2) - 27*a*b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(60*b^5*d) + (11*e^3*(9*a + 2*b*cos(c + d*x))*(e*sin(c + d*x))^(7/2))/(28*b^3*d*(a + b*cos(c + d*x))) + (e*(e*sin(c + d*x))^(11/2))/(2*b*d*(a + b*cos(c + d*x))^2)]
    @test_int [(e*sin(c + d*x))^(11/2)/(a + b*cos(c + d*x))^3, x, 15, (-9*(7*a^4 - 9*a^2*b^2 + 2*b^4)*e^(11/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(11/2)*(-a^2 + b^2)^(3/4)*d) - (9*(7*a^4 - 9*a^2*b^2 + 2*b^4)*e^(11/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(11/2)*(-a^2 + b^2)^(3/4)*d) + (3*a*(21*a^2 - 13*b^2)*e^6*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(4*b^6*d*sqrt(e*sin(c + d*x))) - (9*a*(7*a^4 - 9*a^2*b^2 + 2*b^4)*e^6*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^6*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (9*a*(7*a^4 - 9*a^2*b^2 + 2*b^4)*e^6*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^6*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (3*e^5*(3*(7*a^2 - 2*b^2) - 7*a*b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(4*b^5*d) + (9*e^3*(7*a + 2*b*cos(c + d*x))*(e*sin(c + d*x))^(5/2))/(20*b^3*d*(a + b*cos(c + d*x))) + (e*(e*sin(c + d*x))^(9/2))/(2*b*d*(a + b*cos(c + d*x))^2)]
    @test_int [(e*sin(c + d*x))^(9/2)/(a + b*cos(c + d*x))^3, x, 14, (-7*(5*a^2 - 2*b^2)*e^(9/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(9/2)*(-a^2 + b^2)^(1/4)*d) + (7*(5*a^2 - 2*b^2)*e^(9/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(9/2)*(-a^2 + b^2)^(1/4)*d) + (7*a*(5*a^2 - 2*b^2)*e^5*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^5*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (7*a*(5*a^2 - 2*b^2)*e^5*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^5*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (35*a*e^4*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(4*b^4*d*sqrt(sin(c + d*x))) + (7*e^3*(5*a + 2*b*cos(c + d*x))*(e*sin(c + d*x))^(3/2))/(12*b^3*d*(a + b*cos(c + d*x))) + (e*(e*sin(c + d*x))^(7/2))/(2*b*d*(a + b*cos(c + d*x))^2)]
    @test_int [(e*sin(c + d*x))^(7/2)/(a + b*cos(c + d*x))^3, x, 14, (5*(3*a^2 - 2*b^2)*e^(7/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(7/2)*(-a^2 + b^2)^(3/4)*d) + (5*(3*a^2 - 2*b^2)*e^(7/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(7/2)*(-a^2 + b^2)^(3/4)*d) - (15*a*e^4*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(4*b^4*d*sqrt(e*sin(c + d*x))) + (5*a*(3*a^2 - 2*b^2)*e^4*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^4*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (5*a*(3*a^2 - 2*b^2)*e^4*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^4*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (5*e^3*(3*a + 2*b*cos(c + d*x))*sqrt(e*sin(c + d*x)))/(4*b^3*d*(a + b*cos(c + d*x))) + (e*(e*sin(c + d*x))^(5/2))/(2*b*d*(a + b*cos(c + d*x))^2)]
    @test_int [(e*sin(c + d*x))^(5/2)/(a + b*cos(c + d*x))^3, x, 14, (-3*(a^2 - 2*b^2)*e^(5/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(5/2)*(-a^2 + b^2)^(5/4)*d) + (3*(a^2 - 2*b^2)*e^(5/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(5/2)*(-a^2 + b^2)^(5/4)*d) - (3*a*(a^2 - 2*b^2)*e^3*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^3*(a^2 - b^2)*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) - (3*a*(a^2 - 2*b^2)*e^3*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^3*(a^2 - b^2)*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (3*a*e^2*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(4*b^2*(a^2 - b^2)*d*sqrt(sin(c + d*x))) + (e*(e*sin(c + d*x))^(3/2))/(2*b*d*(a + b*cos(c + d*x))^2) - (3*a*e*(e*sin(c + d*x))^(3/2))/(4*b*(a^2 - b^2)*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(3/2)/(a + b*cos(c + d*x))^3, x, 14, -((a^2 + 2*b^2)*e^(3/2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(3/2)*(-a^2 + b^2)^(7/4)*d) - ((a^2 + 2*b^2)*e^(3/2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*b^(3/2)*(-a^2 + b^2)^(7/4)*d) - (a*e^2*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(4*b^2*(a^2 - b^2)*d*sqrt(e*sin(c + d*x))) + (a*(a^2 + 2*b^2)*e^2*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^2*(a^2 - b^2)*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (a*(a^2 + 2*b^2)*e^2*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b^2*(a^2 - b^2)*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (e*sqrt(e*sin(c + d*x)))/(2*b*d*(a + b*cos(c + d*x))^2) - (a*e*sqrt(e*sin(c + d*x)))/(4*b*(a^2 - b^2)*d*(a + b*cos(c + d*x)))]
    @test_int [(e*sin(c + d*x))^(1/2)/(a + b*cos(c + d*x))^3, x, 14, -((3*a^2 + 2*b^2)*sqrt(e)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*sqrt(b)*(-a^2 + b^2)^(9/4)*d) + ((3*a^2 + 2*b^2)*sqrt(e)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*sqrt(b)*(-a^2 + b^2)^(9/4)*d) + (a*(3*a^2 + 2*b^2)*e*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b*(a^2 - b^2)^2*(b - sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (a*(3*a^2 + 2*b^2)*e*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*b*(a^2 - b^2)^2*(b + sqrt(-a^2 + b^2))*d*sqrt(e*sin(c + d*x))) + (5*a*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(4*(a^2 - b^2)^2*d*sqrt(sin(c + d*x))) - (b*(e*sin(c + d*x))^(3/2))/(2*(a^2 - b^2)*d*e*(a + b*cos(c + d*x))^2) - (5*a*b*(e*sin(c + d*x))^(3/2))/(4*(a^2 - b^2)^2*d*e*(a + b*cos(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(1/2)), x, 14, (3*sqrt(b)*(5*a^2 + 2*b^2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(11/4)*d*sqrt(e)) + (3*sqrt(b)*(5*a^2 + 2*b^2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(11/4)*d*sqrt(e)) - (7*a*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(4*(a^2 - b^2)^2*d*sqrt(e*sin(c + d*x))) + (3*a*(5*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^2*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) + (3*a*(5*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^2*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*sqrt(e*sin(c + d*x))) - (b*sqrt(e*sin(c + d*x)))/(2*(a^2 - b^2)*d*e*(a + b*cos(c + d*x))^2) - (7*a*b*sqrt(e*sin(c + d*x)))/(4*(a^2 - b^2)^2*d*e*(a + b*cos(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(3/2)), x, 15, (-5*b^(3/2)*(7*a^2 + 2*b^2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(13/4)*d*e^(3/2)) + (5*b^(3/2)*(7*a^2 + 2*b^2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(13/4)*d*e^(3/2)) - b/(2*(a^2 - b^2)*d*e*(a + b*cos(c + d*x))^2*sqrt(e*sin(c + d*x))) - (9*a*b)/(4*(a^2 - b^2)^2*d*e*(a + b*cos(c + d*x))*sqrt(e*sin(c + d*x))) + (5*b*(7*a^2 + 2*b^2) - a*(8*a^2 + 37*b^2)*cos(c + d*x))/(4*(a^2 - b^2)^3*d*e*sqrt(e*sin(c + d*x))) - (5*a*b*(7*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^3*(b - sqrt(-a^2 + b^2))*d*e*sqrt(e*sin(c + d*x))) - (5*a*b*(7*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^3*(b + sqrt(-a^2 + b^2))*d*e*sqrt(e*sin(c + d*x))) - (a*(8*a^2 + 37*b^2)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(4*(a^2 - b^2)^3*d*e^2*sqrt(sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(5/2)), x, 15, (7*b^(5/2)*(9*a^2 + 2*b^2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(15/4)*d*e^(5/2)) + (7*b^(5/2)*(9*a^2 + 2*b^2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(15/4)*d*e^(5/2)) - b/(2*(a^2 - b^2)*d*e*(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(3/2)) - (11*a*b)/(4*(a^2 - b^2)^2*d*e*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(3/2)) + (7*b*(9*a^2 + 2*b^2) - a*(8*a^2 + 69*b^2)*cos(c + d*x))/(12*(a^2 - b^2)^3*d*e*(e*sin(c + d*x))^(3/2)) + (a*(8*a^2 + 69*b^2)*Elliptic.F((c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(12*(a^2 - b^2)^3*d*e^2*sqrt(e*sin(c + d*x))) - (7*a*b^2*(9*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^3*(a^2 - b*(b - sqrt(-a^2 + b^2)))*d*e^2*sqrt(e*sin(c + d*x))) - (7*a*b^2*(9*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^3*(a^2 - b*(b + sqrt(-a^2 + b^2)))*d*e^2*sqrt(e*sin(c + d*x)))]
    @test_int [1/((a + b*cos(c + d*x))^3*(e*sin(c + d*x))^(7/2)), x, 16, (-9*b^(7/2)*(11*a^2 + 2*b^2)*atan((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(17/4)*d*e^(7/2)) + (9*b^(7/2)*(11*a^2 + 2*b^2)*atanh((sqrt(b)*sqrt(e*sin(c + d*x)))/((-a^2 + b^2)^(1/4)*sqrt(e))))/(8*(-a^2 + b^2)^(17/4)*d*e^(7/2)) - b/(2*(a^2 - b^2)*d*e*(a + b*cos(c + d*x))^2*(e*sin(c + d*x))^(5/2)) - (13*a*b)/(4*(a^2 - b^2)^2*d*e*(a + b*cos(c + d*x))*(e*sin(c + d*x))^(5/2)) + (9*b*(11*a^2 + 2*b^2) - a*(8*a^2 + 109*b^2)*cos(c + d*x))/(20*(a^2 - b^2)^3*d*e*(e*sin(c + d*x))^(5/2)) - (3*(15*b^3*(11*a^2 + 2*b^2) + a*(8*a^4 - 64*a^2*b^2 - 139*b^4)*cos(c + d*x)))/(20*(a^2 - b^2)^4*d*e^3*sqrt(e*sin(c + d*x))) + (9*a*b^3*(11*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b - sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^4*(b - sqrt(-a^2 + b^2))*d*e^3*sqrt(e*sin(c + d*x))) + (9*a*b^3*(11*a^2 + 2*b^2)*Elliptic.Pi((2*b)/(b + sqrt(-a^2 + b^2)), (c - pi/2 + d*x)/2, 2)*sqrt(sin(c + d*x)))/(8*(a^2 - b^2)^4*(b + sqrt(-a^2 + b^2))*d*e^3*sqrt(e*sin(c + d*x))) - (3*a*(8*a^4 - 64*a^2*b^2 - 139*b^4)*Elliptic.E((c - pi/2 + d*x)/2, 2)*sqrt(e*sin(c + d*x)))/(20*(a^2 - b^2)^4*d*e^4*sqrt(sin(c + d*x)))]


    #= ::Subsection:: =#
    #=Integrands*of*the*form*(g*sin(e+f*x))^(p/2)*(a+b*cos(e+f*x))^(m/2)=#


    #= ::Title:: =#
    #=Integrands*of*the*form*(g*csc(e+f*x))^p*(a+b*cos(e+f*x))^m=#


    #= ::Section:: =#
    #=Integrands*of*the*form*(g*csc(e+f*x))^p*(a+b*cos(e+f*x))^m*when*a^2-b^2=0=#


    #= ::Section:: =#
    #=Integrands*of*the*form*(g*csc(e+f*x))^p*(a+b*cos(e+f*x))^m=#
    end
