@testset "4.1.11 (e x)^m (a+b x^n)^p sin" begin
    @variables a, b, c, d, x

    #= ::Package:: =#

    #= ::Title:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^n)^p*sin(c+d*x)=#


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^1)^p*sin(c+d*x)=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^3*(a + b*x)*sin(c + d*x), x, 11, (-24*b*cos(c + d*x))/d^5 + (6*a*x*cos(c + d*x))/d^3 + (12*b*x^2*cos(c + d*x))/d^3 - (a*x^3*cos(c + d*x))/d - (b*x^4*cos(c + d*x))/d - (6*a*sin(c + d*x))/d^4 - (24*b*x*sin(c + d*x))/d^4 + (3*a*x^2*sin(c + d*x))/d^2 + (4*b*x^3*sin(c + d*x))/d^2]
    @test_int [x^2*(a + b*x)*sin(c + d*x), x, 9, (2*a*cos(c + d*x))/d^3 + (6*b*x*cos(c + d*x))/d^3 - (a*x^2*cos(c + d*x))/d - (b*x^3*cos(c + d*x))/d - (6*b*sin(c + d*x))/d^4 + (2*a*x*sin(c + d*x))/d^2 + (3*b*x^2*sin(c + d*x))/d^2]
    @test_int [x*(a + b*x)*sin(c + d*x), x, 7, (2*b*cos(c + d*x))/d^3 - (a*x*cos(c + d*x))/d - (b*x^2*cos(c + d*x))/d + (a*sin(c + d*x))/d^2 + (2*b*x*sin(c + d*x))/d^2]
    @test_int [(a + b*x)*sin(c + d*x), x, 2, -(((a + b*x)*cos(c + d*x))/d) + (b*sin(c + d*x))/d^2]
    @test_int [((a + b*x)*sin(c + d*x))/x, x, 6, -((b*cos(c + d*x))/d) + a*CosIntegral(d*x)*sin(c) + a*cos(c)*SinIntegral(d*x)]
    @test_int [((a + b*x)*sin(c + d*x))/x^2, x, 9, a*d*cos(c)*CosIntegral(d*x) + b*CosIntegral(d*x)*sin(c) - (a*sin(c + d*x))/x + b*cos(c)*SinIntegral(d*x) - a*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x)*sin(c + d*x))/x^3, x, 11, -(a*d*cos(c + d*x))/(2*x) + b*d*cos(c)*CosIntegral(d*x) - (a*d^2*CosIntegral(d*x)*sin(c))/2 - (a*sin(c + d*x))/(2*x^2) - (b*sin(c + d*x))/x - (a*d^2*cos(c)*SinIntegral(d*x))/2 - b*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x)*sin(c + d*x))/x^4, x, 13, -(a*d*cos(c + d*x))/(6*x^2) - (b*d*cos(c + d*x))/(2*x) - (a*d^3*cos(c)*CosIntegral(d*x))/6 - (b*d^2*CosIntegral(d*x)*sin(c))/2 - (a*sin(c + d*x))/(3*x^3) - (b*sin(c + d*x))/(2*x^2) + (a*d^2*sin(c + d*x))/(6*x) - (b*d^2*cos(c)*SinIntegral(d*x))/2 + (a*d^3*sin(c)*SinIntegral(d*x))/6]
    @test_int [((a + b*x)*sin(c + d*x))/x^5, x, 15, -(a*d*cos(c + d*x))/(12*x^3) - (b*d*cos(c + d*x))/(6*x^2) + (a*d^3*cos(c + d*x))/(24*x) - (b*d^3*cos(c)*CosIntegral(d*x))/6 + (a*d^4*CosIntegral(d*x)*sin(c))/24 - (a*sin(c + d*x))/(4*x^4) - (b*sin(c + d*x))/(3*x^3) + (a*d^2*sin(c + d*x))/(24*x^2) + (b*d^2*sin(c + d*x))/(6*x) + (a*d^4*cos(c)*SinIntegral(d*x))/24 + (b*d^3*sin(c)*SinIntegral(d*x))/6]


    @test_int [x^2*(a + b*x)^2*sin(c + d*x), x, 14, (-24*b^2*cos(c + d*x))/d^5 + (2*a^2*cos(c + d*x))/d^3 + (12*a*b*x*cos(c + d*x))/d^3 + (12*b^2*x^2*cos(c + d*x))/d^3 - (a^2*x^2*cos(c + d*x))/d - (2*a*b*x^3*cos(c + d*x))/d - (b^2*x^4*cos(c + d*x))/d - (12*a*b*sin(c + d*x))/d^4 - (24*b^2*x*sin(c + d*x))/d^4 + (2*a^2*x*sin(c + d*x))/d^2 + (6*a*b*x^2*sin(c + d*x))/d^2 + (4*b^2*x^3*sin(c + d*x))/d^2]
    @test_int [x*(a + b*x)^2*sin(c + d*x), x, 11, (4*a*b*cos(c + d*x))/d^3 + (6*b^2*x*cos(c + d*x))/d^3 - (a^2*x*cos(c + d*x))/d - (2*a*b*x^2*cos(c + d*x))/d - (b^2*x^3*cos(c + d*x))/d - (6*b^2*sin(c + d*x))/d^4 + (a^2*sin(c + d*x))/d^2 + (4*a*b*x*sin(c + d*x))/d^2 + (3*b^2*x^2*sin(c + d*x))/d^2]
    @test_int [(a + b*x)^2*sin(c + d*x), x, 3, (2*b^2*cos(c + d*x))/d^3 - ((a + b*x)^2*cos(c + d*x))/d + (2*b*(a + b*x)*sin(c + d*x))/d^2]
    @test_int [((a + b*x)^2*sin(c + d*x))/x, x, 8, (-2*a*b*cos(c + d*x))/d - (b^2*x*cos(c + d*x))/d + a^2*CosIntegral(d*x)*sin(c) + (b^2*sin(c + d*x))/d^2 + a^2*cos(c)*SinIntegral(d*x)]
    @test_int [((a + b*x)^2*sin(c + d*x))/x^2, x, 10, -((b^2*cos(c + d*x))/d) + a^2*d*cos(c)*CosIntegral(d*x) + 2*a*b*CosIntegral(d*x)*sin(c) - (a^2*sin(c + d*x))/x + 2*a*b*cos(c)*SinIntegral(d*x) - a^2*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x)^2*sin(c + d*x))/x^3, x, 14, -(a^2*d*cos(c + d*x))/(2*x) + 2*a*b*d*cos(c)*CosIntegral(d*x) + b^2*CosIntegral(d*x)*sin(c) - (a^2*d^2*CosIntegral(d*x)*sin(c))/2 - (a^2*sin(c + d*x))/(2*x^2) - (2*a*b*sin(c + d*x))/x + b^2*cos(c)*SinIntegral(d*x) - (a^2*d^2*cos(c)*SinIntegral(d*x))/2 - 2*a*b*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x)^2*sin(c + d*x))/x^4, x, 17, -(a^2*d*cos(c + d*x))/(6*x^2) - (a*b*d*cos(c + d*x))/x + b^2*d*cos(c)*CosIntegral(d*x) - (a^2*d^3*cos(c)*CosIntegral(d*x))/6 - a*b*d^2*CosIntegral(d*x)*sin(c) - (a^2*sin(c + d*x))/(3*x^3) - (a*b*sin(c + d*x))/x^2 - (b^2*sin(c + d*x))/x + (a^2*d^2*sin(c + d*x))/(6*x) - a*b*d^2*cos(c)*SinIntegral(d*x) - b^2*d*sin(c)*SinIntegral(d*x) + (a^2*d^3*sin(c)*SinIntegral(d*x))/6]
    @test_int [((a + b*x)^2*sin(c + d*x))/x^5, x, 20, -(a^2*d*cos(c + d*x))/(12*x^3) - (a*b*d*cos(c + d*x))/(3*x^2) - (b^2*d*cos(c + d*x))/(2*x) + (a^2*d^3*cos(c + d*x))/(24*x) - (a*b*d^3*cos(c)*CosIntegral(d*x))/3 - (b^2*d^2*CosIntegral(d*x)*sin(c))/2 + (a^2*d^4*CosIntegral(d*x)*sin(c))/24 - (a^2*sin(c + d*x))/(4*x^4) - (2*a*b*sin(c + d*x))/(3*x^3) - (b^2*sin(c + d*x))/(2*x^2) + (a^2*d^2*sin(c + d*x))/(24*x^2) + (a*b*d^2*sin(c + d*x))/(3*x) - (b^2*d^2*cos(c)*SinIntegral(d*x))/2 + (a^2*d^4*cos(c)*SinIntegral(d*x))/24 + (a*b*d^3*sin(c)*SinIntegral(d*x))/3]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^4*sin(c + d*x))/(a + b*x), x, 15, (-2*a*cos(c + d*x))/(b^2*d^3) + (a^3*cos(c + d*x))/(b^4*d) + (6*x*cos(c + d*x))/(b*d^3) - (a^2*x*cos(c + d*x))/(b^3*d) + (a*x^2*cos(c + d*x))/(b^2*d) - (x^3*cos(c + d*x))/(b*d) + (a^4*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^5 - (6*sin(c + d*x))/(b*d^4) + (a^2*sin(c + d*x))/(b^3*d^2) - (2*a*x*sin(c + d*x))/(b^2*d^2) + (3*x^2*sin(c + d*x))/(b*d^2) + (a^4*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^5]
    @test_int [(x^3*sin(c + d*x))/(a + b*x), x, 11, (2*cos(c + d*x))/(b*d^3) - (a^2*cos(c + d*x))/(b^3*d) + (a*x*cos(c + d*x))/(b^2*d) - (x^2*cos(c + d*x))/(b*d) - (a^3*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^4 - (a*sin(c + d*x))/(b^2*d^2) + (2*x*sin(c + d*x))/(b*d^2) - (a^3*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^4]
    @test_int [(x^2*sin(c + d*x))/(a + b*x), x, 8, (a*cos(c + d*x))/(b^2*d) - (x*cos(c + d*x))/(b*d) + (a^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^3 + sin(c + d*x)/(b*d^2) + (a^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^3]
    @test_int [(x*sin(c + d*x))/(a + b*x), x, 6, -(cos(c + d*x)/(b*d)) - (a*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^2 - (a*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^2]
    @test_int [sin(c + d*x)/(a + b*x), x, 3, (CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b + (cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b]
    @test_int [sin(c + d*x)/(x*(a + b*x)), x, 8, (CosIntegral(d*x)*sin(c))/a - (CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a + (cos(c)*SinIntegral(d*x))/a - (cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a]
    @test_int [sin(c + d*x)/(x^2*(a + b*x)), x, 12, (d*cos(c)*CosIntegral(d*x))/a - (b*CosIntegral(d*x)*sin(c))/a^2 + (b*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^2 - sin(c + d*x)/(a*x) - (b*cos(c)*SinIntegral(d*x))/a^2 - (d*sin(c)*SinIntegral(d*x))/a + (b*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^2]
    @test_int [sin(c + d*x)/(x^3*(a + b*x)), x, 17, -(d*cos(c + d*x))/(2*a*x) - (b*d*cos(c)*CosIntegral(d*x))/a^2 + (b^2*CosIntegral(d*x)*sin(c))/a^3 - (d^2*CosIntegral(d*x)*sin(c))/(2*a) - (b^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^3 - sin(c + d*x)/(2*a*x^2) + (b*sin(c + d*x))/(a^2*x) + (b^2*cos(c)*SinIntegral(d*x))/a^3 - (d^2*cos(c)*SinIntegral(d*x))/(2*a) + (b*d*sin(c)*SinIntegral(d*x))/a^2 - (b^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^3]


    @test_int [(x^4*sin(c + d*x))/(a + b*x)^2, x, 15, (2*cos(c + d*x))/(b^2*d^3) - (3*a^2*cos(c + d*x))/(b^4*d) + (2*a*x*cos(c + d*x))/(b^3*d) - (x^2*cos(c + d*x))/(b^2*d) + (a^4*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^6 - (4*a^3*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^5 - (2*a*sin(c + d*x))/(b^3*d^2) + (2*x*sin(c + d*x))/(b^2*d^2) - (a^4*sin(c + d*x))/(b^5*(a + b*x)) - (4*a^3*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^5 - (a^4*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^6]
    @test_int [(x^3*sin(c + d*x))/(a + b*x)^2, x, 12, (2*a*cos(c + d*x))/(b^3*d) - (x*cos(c + d*x))/(b^2*d) - (a^3*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^5 + (3*a^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^4 + sin(c + d*x)/(b^2*d^2) + (a^3*sin(c + d*x))/(b^4*(a + b*x)) + (3*a^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^4 + (a^3*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^5]
    @test_int [(x^2*sin(c + d*x))/(a + b*x)^2, x, 10, -(cos(c + d*x)/(b^2*d)) + (a^2*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^4 - (2*a*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^3 - (a^2*sin(c + d*x))/(b^3*(a + b*x)) - (2*a*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^3 - (a^2*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^4]
    @test_int [(x*sin(c + d*x))/(a + b*x)^2, x, 9, -((a*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^3) + (CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^2 + (a*sin(c + d*x))/(b^2*(a + b*x)) + (cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^2 + (a*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^3]
    @test_int [sin(c + d*x)/(a + b*x)^2, x, 4, (d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^2 - sin(c + d*x)/(b*(a + b*x)) - (d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^2]
    @test_int [sin(c + d*x)/(x*(a + b*x)^2), x, 12, -((d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/(a*b)) + (CosIntegral(d*x)*sin(c))/a^2 - (CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^2 + sin(c + d*x)/(a*(a + b*x)) + (cos(c)*SinIntegral(d*x))/a^2 - (cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^2 + (d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(a*b)]
    @test_int [sin(c + d*x)/(x^2*(a + b*x)^2), x, 16, (d*cos(c)*CosIntegral(d*x))/a^2 + (d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/a^2 - (2*b*CosIntegral(d*x)*sin(c))/a^3 + (2*b*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^3 - sin(c + d*x)/(a^2*x) - (b*sin(c + d*x))/(a^2*(a + b*x)) - (2*b*cos(c)*SinIntegral(d*x))/a^3 - (d*sin(c)*SinIntegral(d*x))/a^2 + (2*b*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^3 - (d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^2]


    @test_int [(x^3*sin(c + d*x))/(a + b*x)^3, x, 15, -(cos(c + d*x)/(b^3*d)) + (a^3*d*cos(c + d*x))/(2*b^5*(a + b*x)) + (3*a^2*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^5 - (3*a*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^4 + (a^3*d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*b^6) + (a^3*sin(c + d*x))/(2*b^4*(a + b*x)^2) - (3*a^2*sin(c + d*x))/(b^4*(a + b*x)) - (3*a*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^4 + (a^3*d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*b^6) - (3*a^2*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^5]
    @test_int [(x^2*sin(c + d*x))/(a + b*x)^3, x, 14, -(a^2*d*cos(c + d*x))/(2*b^4*(a + b*x)) - (2*a*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^4 + (CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/b^3 - (a^2*d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*b^5) - (a^2*sin(c + d*x))/(2*b^3*(a + b*x)^2) + (2*a*sin(c + d*x))/(b^3*(a + b*x)) + (cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^3 - (a^2*d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*b^5) + (2*a*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^4]
    @test_int [(x*sin(c + d*x))/(a + b*x)^3, x, 11, (a*d*cos(c + d*x))/(2*b^3*(a + b*x)) + (d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/b^3 + (a*d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*b^4) + (a*sin(c + d*x))/(2*b^2*(a + b*x)^2) - sin(c + d*x)/(b^2*(a + b*x)) + (a*d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*b^4) - (d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/b^3]
    @test_int [sin(c + d*x)/(a + b*x)^3, x, 5, -(d*cos(c + d*x))/(2*b^2*(a + b*x)) - (d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*b^3) - sin(c + d*x)/(2*b*(a + b*x)^2) - (d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*b^3)]
    @test_int [sin(c + d*x)/(x*(a + b*x)^3), x, 17, (d*cos(c + d*x))/(2*a*b*(a + b*x)) - (d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/(a^2*b) + (CosIntegral(d*x)*sin(c))/a^3 - (CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^3 + (d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*a*b^2) + sin(c + d*x)/(2*a*(a + b*x)^2) + sin(c + d*x)/(a^2*(a + b*x)) + (cos(c)*SinIntegral(d*x))/a^3 - (cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^3 + (d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*a*b^2) + (d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(a^2*b)]
    @test_int [sin(c + d*x)/(x^2*(a + b*x)^3), x, 21, -(d*cos(c + d*x))/(2*a^2*(a + b*x)) + (d*cos(c)*CosIntegral(d*x))/a^3 + (2*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/a^3 - (3*b*CosIntegral(d*x)*sin(c))/a^4 + (3*b*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^4 - (d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*a^2*b) - sin(c + d*x)/(a^3*x) - (b*sin(c + d*x))/(2*a^2*(a + b*x)^2) - (2*b*sin(c + d*x))/(a^3*(a + b*x)) - (3*b*cos(c)*SinIntegral(d*x))/a^4 - (d*sin(c)*SinIntegral(d*x))/a^3 + (3*b*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^4 - (d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*a^2*b) - (2*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^3]
    @test_int [sin(c + d*x)/(x^3*(a + b*x)^3), x, 26, -(d*cos(c + d*x))/(2*a^3*x) + (b*d*cos(c + d*x))/(2*a^3*(a + b*x)) - (3*b*d*cos(c)*CosIntegral(d*x))/a^4 - (3*b*d*cos(c - (a*d)/b)*CosIntegral((a*d)/b + d*x))/a^4 + (6*b^2*CosIntegral(d*x)*sin(c))/a^5 - (d^2*CosIntegral(d*x)*sin(c))/(2*a^3) - (6*b^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/a^5 + (d^2*CosIntegral((a*d)/b + d*x)*sin(c - (a*d)/b))/(2*a^3) - sin(c + d*x)/(2*a^3*x^2) + (3*b*sin(c + d*x))/(a^4*x) + (b^2*sin(c + d*x))/(2*a^3*(a + b*x)^2) + (3*b^2*sin(c + d*x))/(a^4*(a + b*x)) + (6*b^2*cos(c)*SinIntegral(d*x))/a^5 - (d^2*cos(c)*SinIntegral(d*x))/(2*a^3) + (3*b*d*sin(c)*SinIntegral(d*x))/a^4 - (6*b^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^5 + (d^2*cos(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/(2*a^3) + (3*b*d*sin(c - (a*d)/b)*SinIntegral((a*d)/b + d*x))/a^4]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^2)^p*sin(c+d*x)=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^3*(a + b*x^2)*sin(c + d*x), x, 12, (-120*b*x*cos(c + d*x))/d^5 + (6*a*x*cos(c + d*x))/d^3 + (20*b*x^3*cos(c + d*x))/d^3 - (a*x^3*cos(c + d*x))/d - (b*x^5*cos(c + d*x))/d + (120*b*sin(c + d*x))/d^6 - (6*a*sin(c + d*x))/d^4 - (60*b*x^2*sin(c + d*x))/d^4 + (3*a*x^2*sin(c + d*x))/d^2 + (5*b*x^4*sin(c + d*x))/d^2]
    @test_int [x^2*(a + b*x^2)*sin(c + d*x), x, 10, (-24*b*cos(c + d*x))/d^5 + (2*a*cos(c + d*x))/d^3 + (12*b*x^2*cos(c + d*x))/d^3 - (a*x^2*cos(c + d*x))/d - (b*x^4*cos(c + d*x))/d - (24*b*x*sin(c + d*x))/d^4 + (2*a*x*sin(c + d*x))/d^2 + (4*b*x^3*sin(c + d*x))/d^2]
    @test_int [x*(a + b*x^2)*sin(c + d*x), x, 8, (6*b*x*cos(c + d*x))/d^3 - (a*x*cos(c + d*x))/d - (b*x^3*cos(c + d*x))/d - (6*b*sin(c + d*x))/d^4 + (a*sin(c + d*x))/d^2 + (3*b*x^2*sin(c + d*x))/d^2]
    @test_int [(a + b*x^2)*sin(c + d*x), x, 6, (2*b*cos(c + d*x))/d^3 - (a*cos(c + d*x))/d - (b*x^2*cos(c + d*x))/d + (2*b*x*sin(c + d*x))/d^2]
    @test_int [((a + b*x^2)*sin(c + d*x))/x, x, 7, -((b*x*cos(c + d*x))/d) + a*CosIntegral(d*x)*sin(c) + (b*sin(c + d*x))/d^2 + a*cos(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^2)*sin(c + d*x))/x^2, x, 7, -((b*cos(c + d*x))/d) + a*d*cos(c)*CosIntegral(d*x) - (a*sin(c + d*x))/x - a*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^2)*sin(c + d*x))/x^3, x, 10, -(a*d*cos(c + d*x))/(2*x) + b*CosIntegral(d*x)*sin(c) - (a*d^2*CosIntegral(d*x)*sin(c))/2 - (a*sin(c + d*x))/(2*x^2) + b*cos(c)*SinIntegral(d*x) - (a*d^2*cos(c)*SinIntegral(d*x))/2]
    @test_int [((a + b*x^2)*sin(c + d*x))/x^4, x, 12, -(a*d*cos(c + d*x))/(6*x^2) + b*d*cos(c)*CosIntegral(d*x) - (a*d^3*cos(c)*CosIntegral(d*x))/6 - (a*sin(c + d*x))/(3*x^3) - (b*sin(c + d*x))/x + (a*d^2*sin(c + d*x))/(6*x) - b*d*sin(c)*SinIntegral(d*x) + (a*d^3*sin(c)*SinIntegral(d*x))/6]
    @test_int [((a + b*x^2)*sin(c + d*x))/x^5, x, 14, -(a*d*cos(c + d*x))/(12*x^3) - (b*d*cos(c + d*x))/(2*x) + (a*d^3*cos(c + d*x))/(24*x) - (b*d^2*CosIntegral(d*x)*sin(c))/2 + (a*d^4*CosIntegral(d*x)*sin(c))/24 - (a*sin(c + d*x))/(4*x^4) - (b*sin(c + d*x))/(2*x^2) + (a*d^2*sin(c + d*x))/(24*x^2) - (b*d^2*cos(c)*SinIntegral(d*x))/2 + (a*d^4*cos(c)*SinIntegral(d*x))/24]


    @test_int [x^2*(a + b*x^2)^2*sin(c + d*x), x, 17, (720*b^2*cos(c + d*x))/d^7 - (48*a*b*cos(c + d*x))/d^5 + (2*a^2*cos(c + d*x))/d^3 - (360*b^2*x^2*cos(c + d*x))/d^5 + (24*a*b*x^2*cos(c + d*x))/d^3 - (a^2*x^2*cos(c + d*x))/d + (30*b^2*x^4*cos(c + d*x))/d^3 - (2*a*b*x^4*cos(c + d*x))/d - (b^2*x^6*cos(c + d*x))/d + (720*b^2*x*sin(c + d*x))/d^6 - (48*a*b*x*sin(c + d*x))/d^4 + (2*a^2*x*sin(c + d*x))/d^2 - (120*b^2*x^3*sin(c + d*x))/d^4 + (8*a*b*x^3*sin(c + d*x))/d^2 + (6*b^2*x^5*sin(c + d*x))/d^2]
    @test_int [x*(a + b*x^2)^2*sin(c + d*x), x, 14, (-120*b^2*x*cos(c + d*x))/d^5 + (12*a*b*x*cos(c + d*x))/d^3 - (a^2*x*cos(c + d*x))/d + (20*b^2*x^3*cos(c + d*x))/d^3 - (2*a*b*x^3*cos(c + d*x))/d - (b^2*x^5*cos(c + d*x))/d + (120*b^2*sin(c + d*x))/d^6 - (12*a*b*sin(c + d*x))/d^4 + (a^2*sin(c + d*x))/d^2 - (60*b^2*x^2*sin(c + d*x))/d^4 + (6*a*b*x^2*sin(c + d*x))/d^2 + (5*b^2*x^4*sin(c + d*x))/d^2]
    @test_int [(a + b*x^2)^2*sin(c + d*x), x, 11, (-24*b^2*cos(c + d*x))/d^5 + (4*a*b*cos(c + d*x))/d^3 - (a^2*cos(c + d*x))/d + (12*b^2*x^2*cos(c + d*x))/d^3 - (2*a*b*x^2*cos(c + d*x))/d - (b^2*x^4*cos(c + d*x))/d - (24*b^2*x*sin(c + d*x))/d^4 + (4*a*b*x*sin(c + d*x))/d^2 + (4*b^2*x^3*sin(c + d*x))/d^2]
    @test_int [((a + b*x^2)^2*sin(c + d*x))/x, x, 11, (6*b^2*x*cos(c + d*x))/d^3 - (2*a*b*x*cos(c + d*x))/d - (b^2*x^3*cos(c + d*x))/d + a^2*CosIntegral(d*x)*sin(c) - (6*b^2*sin(c + d*x))/d^4 + (2*a*b*sin(c + d*x))/d^2 + (3*b^2*x^2*sin(c + d*x))/d^2 + a^2*cos(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^2)^2*sin(c + d*x))/x^2, x, 10, (2*b^2*cos(c + d*x))/d^3 - (2*a*b*cos(c + d*x))/d - (b^2*x^2*cos(c + d*x))/d + a^2*d*cos(c)*CosIntegral(d*x) - (a^2*sin(c + d*x))/x + (2*b^2*x*sin(c + d*x))/d^2 - a^2*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^2)^2*sin(c + d*x))/x^3, x, 12, -(a^2*d*cos(c + d*x))/(2*x) - (b^2*x*cos(c + d*x))/d + 2*a*b*CosIntegral(d*x)*sin(c) - (a^2*d^2*CosIntegral(d*x)*sin(c))/2 + (b^2*sin(c + d*x))/d^2 - (a^2*sin(c + d*x))/(2*x^2) + 2*a*b*cos(c)*SinIntegral(d*x) - (a^2*d^2*cos(c)*SinIntegral(d*x))/2]
    @test_int [((a + b*x^2)^2*sin(c + d*x))/x^4, x, 13, -((b^2*cos(c + d*x))/d) - (a^2*d*cos(c + d*x))/(6*x^2) + 2*a*b*d*cos(c)*CosIntegral(d*x) - (a^2*d^3*cos(c)*CosIntegral(d*x))/6 - (a^2*sin(c + d*x))/(3*x^3) - (2*a*b*sin(c + d*x))/x + (a^2*d^2*sin(c + d*x))/(6*x) - 2*a*b*d*sin(c)*SinIntegral(d*x) + (a^2*d^3*sin(c)*SinIntegral(d*x))/6]
    @test_int [((a + b*x^2)^2*sin(c + d*x))/x^5, x, 17, -(a^2*d*cos(c + d*x))/(12*x^3) - (a*b*d*cos(c + d*x))/x + (a^2*d^3*cos(c + d*x))/(24*x) + b^2*CosIntegral(d*x)*sin(c) - a*b*d^2*CosIntegral(d*x)*sin(c) + (a^2*d^4*CosIntegral(d*x)*sin(c))/24 - (a^2*sin(c + d*x))/(4*x^4) - (a*b*sin(c + d*x))/x^2 + (a^2*d^2*sin(c + d*x))/(24*x^2) + b^2*cos(c)*SinIntegral(d*x) - a*b*d^2*cos(c)*SinIntegral(d*x) + (a^2*d^4*cos(c)*SinIntegral(d*x))/24]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^4*sin(c + d*x))/(a + b*x^2), x, 14, (2*cos(c + d*x))/(b*d^3) + (a*cos(c + d*x))/(b^2*d) - (x^2*cos(c + d*x))/(b*d) - ((-a)^(3/2)*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*b^(5/2)) + ((-a)^(3/2)*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*b^(5/2)) + (2*x*sin(c + d*x))/(b*d^2) - ((-a)^(3/2)*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^(5/2)) - ((-a)^(3/2)*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^(5/2))]
    @test_int [(x^3*sin(c + d*x))/(a + b*x^2), x, 12, -((x*cos(c + d*x))/(b*d)) - (a*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*b^2) - (a*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*b^2) + sin(c + d*x)/(b*d^2) + (a*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^2) - (a*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^2)]
    @test_int [(x^2*sin(c + d*x))/(a + b*x^2), x, 11, -(cos(c + d*x)/(b*d)) - (sqrt(-a)*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*b^(3/2)) + (sqrt(-a)*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*b^(3/2)) - (sqrt(-a)*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^(3/2)) - (sqrt(-a)*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^(3/2))]
    @test_int [(x*sin(c + d*x))/(a + b*x^2), x, 8, (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*b) + (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*b) - (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b) + (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b)]
    @test_int [sin(c + d*x)/(a + b*x^2), x, 8, -(CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*sqrt(-a)*sqrt(b)) + (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*sqrt(-a)*sqrt(b)) - (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*sqrt(-a)*sqrt(b)) - (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*sqrt(-a)*sqrt(b))]
    @test_int [sin(c + d*x)/(x*(a + b*x^2)), x, 13, (CosIntegral(d*x)*sin(c))/a - (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*a) - (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*a) + (cos(c)*SinIntegral(d*x))/a + (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a) - (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a)]
    @test_int [sin(c + d*x)/(x^2*(a + b*x^2)), x, 14, (d*cos(c)*CosIntegral(d*x))/a - (sqrt(b)*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*(-a)^(3/2)) + (sqrt(b)*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*(-a)^(3/2)) - sin(c + d*x)/(a*x) - (d*sin(c)*SinIntegral(d*x))/a - (sqrt(b)*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*(-a)^(3/2)) - (sqrt(b)*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*(-a)^(3/2))]
    @test_int [sin(c + d*x)/(x^3*(a + b*x^2)), x, 18, -(d*cos(c + d*x))/(2*a*x) - (b*CosIntegral(d*x)*sin(c))/a^2 - (d^2*CosIntegral(d*x)*sin(c))/(2*a) + (b*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*a^2) + (b*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*a^2) - sin(c + d*x)/(2*a*x^2) - (b*cos(c)*SinIntegral(d*x))/a^2 - (d^2*cos(c)*SinIntegral(d*x))/(2*a) - (b*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^2) + (b*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^2)]


    @test_int [(x^4*sin(c + d*x))/(a + b*x^2)^2, x, 24, -(cos(c + d*x)/(b^2*d)) - (a*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^3) - (a*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^3) - (3*sqrt(-a)*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(4*b^(5/2)) + (3*sqrt(-a)*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(4*b^(5/2)) + (x*sin(c + d*x))/(2*b^2) - (x^3*sin(c + d*x))/(2*b*(a + b*x^2)) - (3*sqrt(-a)*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^(5/2)) - (a*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^3) - (3*sqrt(-a)*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^(5/2)) + (a*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^3)]
    @test_int [(x^3*sin(c + d*x))/(a + b*x^2)^2, x, 20, (sqrt(-a)*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^(5/2)) - (sqrt(-a)*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^(5/2)) + (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*b^2) + (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*b^2) + sin(c + d*x)/(2*b^2) - (x^2*sin(c + d*x))/(2*b*(a + b*x^2)) - (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*b^2) + (sqrt(-a)*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^(5/2)) + (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*b^2) + (sqrt(-a)*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^(5/2))]
    @test_int [(x^2*sin(c + d*x))/(a + b*x^2)^2, x, 17, (d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^2) + (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^2) - (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(4*sqrt(-a)*b^(3/2)) + (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(4*sqrt(-a)*b^(3/2)) - (x*sin(c + d*x))/(2*b*(a + b*x^2)) - (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*sqrt(-a)*b^(3/2)) + (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*b^2) - (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*sqrt(-a)*b^(3/2)) - (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*b^2)]
    @test_int [(x*sin(c + d*x))/(a + b*x^2)^2, x, 9, (d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*sqrt(-a)*b^(3/2)) - (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*sqrt(-a)*b^(3/2)) - sin(c + d*x)/(2*b*(a + b*x^2)) + (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*sqrt(-a)*b^(3/2)) + (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*sqrt(-a)*b^(3/2))]
    @test_int [sin(c + d*x)/(a + b*x^2)^2, x, 18, -(d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*a*b) - (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*a*b) + (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(4*(-a)^(3/2)*sqrt(b)) - (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(4*(-a)^(3/2)*sqrt(b)) - sin(c + d*x)/(4*a*sqrt(b)*(sqrt(-a) - sqrt(b)*x)) + sin(c + d*x)/(4*a*sqrt(b)*(sqrt(-a) + sqrt(b)*x)) + (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(3/2)*sqrt(b)) - (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*a*b) + (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(3/2)*sqrt(b)) + (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*a*b)]
    @test_int [sin(c + d*x)/(x*(a + b*x^2)^2), x, 22, (d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(3/2)*sqrt(b)) - (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(3/2)*sqrt(b)) + (CosIntegral(d*x)*sin(c))/a^2 - (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*a^2) - (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*a^2) + sin(c + d*x)/(2*a*(a + b*x^2)) + (cos(c)*SinIntegral(d*x))/a^2 + (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^2) + (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(3/2)*sqrt(b)) - (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^2) + (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(3/2)*sqrt(b))]
    @test_int [sin(c + d*x)/(x^2*(a + b*x^2)^2), x, 32, (d*cos(c)*CosIntegral(d*x))/a^2 + (d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*a^2) + (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*a^2) + (3*sqrt(b)*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(4*(-a)^(5/2)) - (3*sqrt(b)*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(4*(-a)^(5/2)) - sin(c + d*x)/(a^2*x) + (sqrt(b)*sin(c + d*x))/(4*a^2*(sqrt(-a) - sqrt(b)*x)) - (sqrt(b)*sin(c + d*x))/(4*a^2*(sqrt(-a) + sqrt(b)*x)) - (d*sin(c)*SinIntegral(d*x))/a^2 + (3*sqrt(b)*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*(-a)^(5/2)) + (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(4*a^2) + (3*sqrt(b)*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*(-a)^(5/2)) - (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(4*a^2)]


    @test_int [(x^3*sin(c + d*x))/(a + b*x^2)^3, x, 27, -(d*x*cos(c + d*x))/(8*b^2*(a + b*x^2)) + (3*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*sqrt(-a)*b^(5/2)) - (3*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*sqrt(-a)*b^(5/2)) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*b^3) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*b^3) - (x^2*sin(c + d*x))/(4*b*(a + b*x^2)^2) - sin(c + d*x)/(4*b^2*(a + b*x^2)) + (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*b^3) + (3*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*sqrt(-a)*b^(5/2)) - (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*b^3) + (3*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*sqrt(-a)*b^(5/2))]
    @test_int [(x^2*sin(c + d*x))/(a + b*x^2)^3, x, 28, -(d*cos(c + d*x))/(8*b^2*(a + b*x^2)) - (d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a*b^2) - (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a*b^2) + (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*sqrt(-a)*b^(5/2)) - (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(3/2)*b^(3/2)) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*sqrt(-a)*b^(5/2)) - sin(c + d*x)/(16*a*b^(3/2)*(sqrt(-a) - sqrt(b)*x)) + sin(c + d*x)/(16*a*b^(3/2)*(sqrt(-a) + sqrt(b)*x)) - (x*sin(c + d*x))/(4*b*(a + b*x^2)^2) + (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*sqrt(-a)*b^(5/2)) - (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a*b^2) + (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*sqrt(-a)*b^(5/2)) + (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a*b^2)]
    @test_int [(x*sin(c + d*x))/(a + b*x^2)^3, x, 19, -(d*cos(c + d*x))/(16*a*b^(3/2)*(sqrt(-a) - sqrt(b)*x)) + (d*cos(c + d*x))/(16*a*b^(3/2)*(sqrt(-a) + sqrt(b)*x)) - (d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*a*b^2) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*a*b^2) - sin(c + d*x)/(4*b*(a + b*x^2)^2) - (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a*b^2) - (d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) + (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a*b^2) - (d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2))]
    @test_int [sin(c + d*x)/(a + b*x^2)^3, x, 28, (d*cos(c + d*x))/(16*(-a)^(3/2)*b*(sqrt(-a) - sqrt(b)*x)) + (d*cos(c + d*x))/(16*(-a)^(3/2)*b*(sqrt(-a) + sqrt(b)*x)) - (3*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^2*b) - (3*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^2*b) - (3*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(5/2)*sqrt(b)) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(3/2)*b^(3/2)) + (3*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(5/2)*sqrt(b)) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(3/2)*b^(3/2)) - sin(c + d*x)/(16*(-a)^(3/2)*sqrt(b)*(sqrt(-a) - sqrt(b)*x)^2) - (3*sin(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) - sqrt(b)*x)) + sin(c + d*x)/(16*(-a)^(3/2)*sqrt(b)*(sqrt(-a) + sqrt(b)*x)^2) + (3*sin(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) + sqrt(b)*x)) - (3*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) + (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(3/2)*b^(3/2)) - (3*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^2*b) - (3*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) + (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(3/2)*b^(3/2)) + (3*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^2*b)]
    @test_int [sin(c + d*x)/(x*(a + b*x^2)^3), x, 41, (d*cos(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) - sqrt(b)*x)) - (d*cos(c + d*x))/(16*a^2*sqrt(b)*(sqrt(-a) + sqrt(b)*x)) - (5*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) + (5*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) + (CosIntegral(d*x)*sin(c))/a^3 - (CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*a^3) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*a^2*b) - (CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*a^3) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*a^2*b) + sin(c + d*x)/(4*a*(a + b*x^2)^2) + sin(c + d*x)/(2*a^2*(a + b*x^2)) + (cos(c)*SinIntegral(d*x))/a^3 + (cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^3) + (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^2*b) - (5*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) - (cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^3) - (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^2*b) - (5*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b))]
    @test_int [sin(c + d*x)/(x^2*(a + b*x^2)^3), x, 60, (d*cos(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) - sqrt(b)*x)) + (d*cos(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) + sqrt(b)*x)) + (d*cos(c)*CosIntegral(d*x))/a^3 + (7*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^3) + (7*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^3) - (15*sqrt(b)*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(7/2)) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(5/2)*sqrt(b)) + (15*sqrt(b)*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(7/2)) - (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*(-a)^(5/2)*sqrt(b)) - sin(c + d*x)/(a^3*x) - (sqrt(b)*sin(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) - sqrt(b)*x)^2) + (7*sqrt(b)*sin(c + d*x))/(16*a^3*(sqrt(-a) - sqrt(b)*x)) + (sqrt(b)*sin(c + d*x))/(16*(-a)^(5/2)*(sqrt(-a) + sqrt(b)*x)^2) - (7*sqrt(b)*sin(c + d*x))/(16*a^3*(sqrt(-a) + sqrt(b)*x)) - (d*sin(c)*SinIntegral(d*x))/a^3 - (15*sqrt(b)*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(7/2)) + (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(5/2)*sqrt(b)) + (7*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^3) - (15*sqrt(b)*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(7/2)) + (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(5/2)*sqrt(b)) - (7*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^3)]
    @test_int [sin(c + d*x)/(x^3*(a + b*x^2)^3), x, 46, -(d*cos(c + d*x))/(2*a^3*x) - (sqrt(b)*d*cos(c + d*x))/(16*a^3*(sqrt(-a) - sqrt(b)*x)) + (sqrt(b)*d*cos(c + d*x))/(16*a^3*(sqrt(-a) + sqrt(b)*x)) - (9*sqrt(b)*d*cos(c + (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(7/2)) + (9*sqrt(b)*d*cos(c - (sqrt(-a)*d)/sqrt(b))*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(7/2)) - (3*b*CosIntegral(d*x)*sin(c))/a^4 - (d^2*CosIntegral(d*x)*sin(c))/(2*a^3) + (3*b*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(2*a^4) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) + d*x)*sin(c - (sqrt(-a)*d)/sqrt(b)))/(16*a^3) + (3*b*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(2*a^4) + (d^2*CosIntegral((sqrt(-a)*d)/sqrt(b) - d*x)*sin(c + (sqrt(-a)*d)/sqrt(b)))/(16*a^3) - sin(c + d*x)/(2*a^3*x^2) - (b*sin(c + d*x))/(4*a^2*(a + b*x^2)^2) - (b*sin(c + d*x))/(a^3*(a + b*x^2)) - (3*b*cos(c)*SinIntegral(d*x))/a^4 - (d^2*cos(c)*SinIntegral(d*x))/(2*a^3) - (3*b*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(2*a^4) - (d^2*cos(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*a^3) - (9*sqrt(b)*d*sin(c + (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) - d*x))/(16*(-a)^(7/2)) + (3*b*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(2*a^4) + (d^2*cos(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*a^3) - (9*sqrt(b)*d*sin(c - (sqrt(-a)*d)/sqrt(b))*SinIntegral((sqrt(-a)*d)/sqrt(b) + d*x))/(16*(-a)^(7/2))]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(e*x)^m*(a+b*x^3)^p*sin(c+d*x)=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^3*(a + b*x^3)*sin(c + d*x), x, 13, (720*b*cos(c + d*x))/d^7 + (6*a*x*cos(c + d*x))/d^3 - (360*b*x^2*cos(c + d*x))/d^5 - (a*x^3*cos(c + d*x))/d + (30*b*x^4*cos(c + d*x))/d^3 - (b*x^6*cos(c + d*x))/d - (6*a*sin(c + d*x))/d^4 + (720*b*x*sin(c + d*x))/d^6 + (3*a*x^2*sin(c + d*x))/d^2 - (120*b*x^3*sin(c + d*x))/d^4 + (6*b*x^5*sin(c + d*x))/d^2]
    @test_int [x^2*(a + b*x^3)*sin(c + d*x), x, 11, (2*a*cos(c + d*x))/d^3 - (120*b*x*cos(c + d*x))/d^5 - (a*x^2*cos(c + d*x))/d + (20*b*x^3*cos(c + d*x))/d^3 - (b*x^5*cos(c + d*x))/d + (120*b*sin(c + d*x))/d^6 + (2*a*x*sin(c + d*x))/d^2 - (60*b*x^2*sin(c + d*x))/d^4 + (5*b*x^4*sin(c + d*x))/d^2]
    @test_int [x*(a + b*x^3)*sin(c + d*x), x, 9, (-24*b*cos(c + d*x))/d^5 - (a*x*cos(c + d*x))/d + (12*b*x^2*cos(c + d*x))/d^3 - (b*x^4*cos(c + d*x))/d + (a*sin(c + d*x))/d^2 - (24*b*x*sin(c + d*x))/d^4 + (4*b*x^3*sin(c + d*x))/d^2]
    @test_int [(a + b*x^3)*sin(c + d*x), x, 7, -((a*cos(c + d*x))/d) + (6*b*x*cos(c + d*x))/d^3 - (b*x^3*cos(c + d*x))/d - (6*b*sin(c + d*x))/d^4 + (3*b*x^2*sin(c + d*x))/d^2]
    @test_int [((a + b*x^3)*sin(c + d*x))/x, x, 8, (2*b*cos(c + d*x))/d^3 - (b*x^2*cos(c + d*x))/d + a*CosIntegral(d*x)*sin(c) + (2*b*x*sin(c + d*x))/d^2 + a*cos(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^3)*sin(c + d*x))/x^2, x, 8, -((b*x*cos(c + d*x))/d) + a*d*cos(c)*CosIntegral(d*x) + (b*sin(c + d*x))/d^2 - (a*sin(c + d*x))/x - a*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^3)*sin(c + d*x))/x^3, x, 8, -((b*cos(c + d*x))/d) - (a*d*cos(c + d*x))/(2*x) - (a*d^2*CosIntegral(d*x)*sin(c))/2 - (a*sin(c + d*x))/(2*x^2) - (a*d^2*cos(c)*SinIntegral(d*x))/2]
    @test_int [((a + b*x^3)*sin(c + d*x))/x^4, x, 11, -(a*d*cos(c + d*x))/(6*x^2) - (a*d^3*cos(c)*CosIntegral(d*x))/6 + b*CosIntegral(d*x)*sin(c) - (a*sin(c + d*x))/(3*x^3) + (a*d^2*sin(c + d*x))/(6*x) + b*cos(c)*SinIntegral(d*x) + (a*d^3*sin(c)*SinIntegral(d*x))/6]


    @test_int [x*(a + b*x^3)^2*sin(c + d*x), x, 17, (-48*a*b*cos(c + d*x))/d^5 + (5040*b^2*x*cos(c + d*x))/d^7 - (a^2*x*cos(c + d*x))/d + (24*a*b*x^2*cos(c + d*x))/d^3 - (840*b^2*x^3*cos(c + d*x))/d^5 - (2*a*b*x^4*cos(c + d*x))/d + (42*b^2*x^5*cos(c + d*x))/d^3 - (b^2*x^7*cos(c + d*x))/d - (5040*b^2*sin(c + d*x))/d^8 + (a^2*sin(c + d*x))/d^2 - (48*a*b*x*sin(c + d*x))/d^4 + (2520*b^2*x^2*sin(c + d*x))/d^6 + (8*a*b*x^3*sin(c + d*x))/d^2 - (210*b^2*x^4*sin(c + d*x))/d^4 + (7*b^2*x^6*sin(c + d*x))/d^2]
    @test_int [(a + b*x^3)^2*sin(c + d*x), x, 14, (720*b^2*cos(c + d*x))/d^7 - (a^2*cos(c + d*x))/d + (12*a*b*x*cos(c + d*x))/d^3 - (360*b^2*x^2*cos(c + d*x))/d^5 - (2*a*b*x^3*cos(c + d*x))/d + (30*b^2*x^4*cos(c + d*x))/d^3 - (b^2*x^6*cos(c + d*x))/d - (12*a*b*sin(c + d*x))/d^4 + (720*b^2*x*sin(c + d*x))/d^6 + (6*a*b*x^2*sin(c + d*x))/d^2 - (120*b^2*x^3*sin(c + d*x))/d^4 + (6*b^2*x^5*sin(c + d*x))/d^2]
    @test_int [((a + b*x^3)^2*sin(c + d*x))/x, x, 14, (4*a*b*cos(c + d*x))/d^3 - (120*b^2*x*cos(c + d*x))/d^5 - (2*a*b*x^2*cos(c + d*x))/d + (20*b^2*x^3*cos(c + d*x))/d^3 - (b^2*x^5*cos(c + d*x))/d + a^2*CosIntegral(d*x)*sin(c) + (120*b^2*sin(c + d*x))/d^6 + (4*a*b*x*sin(c + d*x))/d^2 - (60*b^2*x^2*sin(c + d*x))/d^4 + (5*b^2*x^4*sin(c + d*x))/d^2 + a^2*cos(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^3)^2*sin(c + d*x))/x^2, x, 13, (-24*b^2*cos(c + d*x))/d^5 - (2*a*b*x*cos(c + d*x))/d + (12*b^2*x^2*cos(c + d*x))/d^3 - (b^2*x^4*cos(c + d*x))/d + a^2*d*cos(c)*CosIntegral(d*x) + (2*a*b*sin(c + d*x))/d^2 - (a^2*sin(c + d*x))/x - (24*b^2*x*sin(c + d*x))/d^4 + (4*b^2*x^3*sin(c + d*x))/d^2 - a^2*d*sin(c)*SinIntegral(d*x)]
    @test_int [((a + b*x^3)^2*sin(c + d*x))/x^3, x, 12, (-2*a*b*cos(c + d*x))/d - (a^2*d*cos(c + d*x))/(2*x) + (6*b^2*x*cos(c + d*x))/d^3 - (b^2*x^3*cos(c + d*x))/d - (a^2*d^2*CosIntegral(d*x)*sin(c))/2 - (6*b^2*sin(c + d*x))/d^4 - (a^2*sin(c + d*x))/(2*x^2) + (3*b^2*x^2*sin(c + d*x))/d^2 - (a^2*d^2*cos(c)*SinIntegral(d*x))/2]
    @test_int [((a + b*x^3)^2*sin(c + d*x))/x^4, x, 14, (2*b^2*cos(c + d*x))/d^3 - (a^2*d*cos(c + d*x))/(6*x^2) - (b^2*x^2*cos(c + d*x))/d - (a^2*d^3*cos(c)*CosIntegral(d*x))/6 + 2*a*b*CosIntegral(d*x)*sin(c) - (a^2*sin(c + d*x))/(3*x^3) + (a^2*d^2*sin(c + d*x))/(6*x) + (2*b^2*x*sin(c + d*x))/d^2 + 2*a*b*cos(c)*SinIntegral(d*x) + (a^2*d^3*sin(c)*SinIntegral(d*x))/6]
    @test_int [((a + b*x^3)^2*sin(c + d*x))/x^5, x, 15, -(a^2*d*cos(c + d*x))/(12*x^3) + (a^2*d^3*cos(c + d*x))/(24*x) - (b^2*x*cos(c + d*x))/d + 2*a*b*d*cos(c)*CosIntegral(d*x) + (a^2*d^4*CosIntegral(d*x)*sin(c))/24 + (b^2*sin(c + d*x))/d^2 - (a^2*sin(c + d*x))/(4*x^4) + (a^2*d^2*sin(c + d*x))/(24*x^2) - (2*a*b*sin(c + d*x))/x + (a^2*d^4*cos(c)*SinIntegral(d*x))/24 - 2*a*b*d*sin(c)*SinIntegral(d*x)]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^4*sin(c + d*x))/(a + b*x^3), x, 15, -((x*cos(c + d*x))/(b*d)) + (a^(2/3)*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*b^(5/3)) + ((-1)^(2/3)*a^(2/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*b^(5/3)) + sin(c + d*x)/(b*d^2) - ((-1)^(2/3)*a^(2/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b^(5/3)) + (a^(2/3)*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(5/3)) - ((-1)^(1/3)*a^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(5/3))]
    @test_int [(x^3*sin(c + d*x))/(a + b*x^3), x, 14, -(cos(c + d*x)/(b*d)) - (a^(1/3)*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*b^(4/3)) + ((-1)^(1/3)*a^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*b^(4/3)) - ((-1)^(1/3)*a^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b^(4/3)) - (a^(1/3)*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(4/3)) - ((-1)^(2/3)*a^(1/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*b^(4/3))]
    @test_int [(x^2*sin(c + d*x))/(a + b*x^3), x, 11, (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*b) + (CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*b) + (CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*b) - (cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*b) + (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*b) + (cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*b)]
    @test_int [(x*sin(c + d*x))/(a + b*x^3), x, 11, -((CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a^(1/3)*b^(2/3))) - ((-1)^(2/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(1/3)*b^(2/3)) + ((-1)^(1/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(1/3)*b^(2/3)) + ((-1)^(2/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(1/3)*b^(2/3)) - (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(1/3)*b^(2/3)) + ((-1)^(1/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(1/3)*b^(2/3))]
    @test_int [sin(c + d*x)/(a + b*x^3), x, 11, (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a^(2/3)*b^(1/3)) - ((-1)^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(2/3)*b^(1/3)) + ((-1)^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(2/3)*b^(1/3)) + ((-1)^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(2/3)*b^(1/3)) + (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(2/3)*b^(1/3)) + ((-1)^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(2/3)*b^(1/3))]
    @test_int [sin(c + d*x)/(x*(a + b*x^3)), x, 16, (CosIntegral(d*x)*sin(c))/a - (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a) - (CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a) - (CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a) + (cos(c)*SinIntegral(d*x))/a + (cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a) - (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a) - (cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a)]
    @test_int [sin(c + d*x)/(x^2*(a + b*x^3)), x, 17, (d*cos(c)*CosIntegral(d*x))/a + (b^(1/3)*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a^(4/3)) + ((-1)^(2/3)*b^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(4/3)) - sin(c + d*x)/(a*x) - (d*sin(c)*SinIntegral(d*x))/a - ((-1)^(2/3)*b^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(4/3)) + (b^(1/3)*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(4/3)) - ((-1)^(1/3)*b^(1/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(4/3))]
    @test_int [sin(c + d*x)/(x^3*(a + b*x^3)), x, 18, -((d*cos(c + d*x))/(2*a*x)) - (d^2*CosIntegral(d*x)*sin(c))/(2*a) - (b^(2/3)*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a^(5/3)) + ((-1)^(1/3)*b^(2/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a^(5/3)) - sin(c + d*x)/(2*a*x^2) - (d^2*cos(c)*SinIntegral(d*x))/(2*a) - ((-1)^(1/3)*b^(2/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^(5/3)) - (b^(2/3)*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(5/3)) - ((-1)^(2/3)*b^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^(5/3))]


    @test_int [(x^3*sin(c + d*x))/(a + b*x^3)^2, x, 23, -(((-1)^(2/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(1/3)*b^(5/3))) - (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(1/3)*b^(5/3)) + ((-1)^(1/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(1/3)*b^(5/3)) + (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(2/3)*b^(4/3)) - ((-1)^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(2/3)*b^(4/3)) - (x*sin(c + d*x))/(3*b*(a + b*x^3)) + ((-1)^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(2/3)*b^(4/3)) - ((-1)^(2/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(1/3)*b^(5/3)) + (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) + (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(1/3)*b^(5/3)) + ((-1)^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) - ((-1)^(1/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(1/3)*b^(5/3))]
    @test_int [(x^2*sin(c + d*x))/(a + b*x^3)^2, x, 12, -(((-1)^(1/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(2/3)*b^(4/3))) + (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) + ((-1)^(2/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) - sin(c + d*x)/(3*b*(a + b*x^3)) - ((-1)^(1/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(2/3)*b^(4/3)) - (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3)) - ((-1)^(2/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(2/3)*b^(4/3))]
    @test_int [(x*sin(c + d*x))/(a + b*x^3)^2, x, 34, -((d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a*b)) - (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a*b) - (d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a*b) - (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(4/3)*b^(2/3)) - ((-1)^(2/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(4/3)*b^(2/3)) + ((-1)^(1/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(4/3)*b^(2/3)) + sin(c + d*x)/(3*a*b*x) - sin(c + d*x)/(3*b*x*(a + b*x^3)) + ((-1)^(2/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(4/3)*b^(2/3)) - (d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a*b) - (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) + (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a*b) + ((-1)^(1/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) + (d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a*b)]
    @test_int [sin(c + d*x)/(a + b*x^3)^2, x, 36, ((-1)^(2/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(4/3)*b^(2/3)) + (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) - ((-1)^(1/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) + (2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(5/3)*b^(1/3)) - (2*(-1)^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(5/3)*b^(1/3)) + (2*(-1)^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(5/3)*b^(1/3)) + sin(c + d*x)/(3*a*b*x^2) - sin(c + d*x)/(3*b*x^2*(a + b*x^3)) + (2*(-1)^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(5/3)*b^(1/3)) + ((-1)^(2/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(4/3)*b^(2/3)) + (2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) - (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3)) + (2*(-1)^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) + ((-1)^(1/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(4/3)*b^(2/3))]
    @test_int [sin(c + d*x)/(x*(a + b*x^3)^2), x, 41, ((-1)^(1/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(5/3)*b^(1/3)) - (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) - ((-1)^(2/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) + (CosIntegral(d*x)*sin(c))/a^2 - (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a^2) - (CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a^2) - (CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a^2) + sin(c + d*x)/(3*a*b*x^3) - sin(c + d*x)/(3*b*x^3*(a + b*x^3)) + (cos(c)*SinIntegral(d*x))/a^2 + (cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^2) + ((-1)^(1/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(5/3)*b^(1/3)) - (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^2) + (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3)) - (cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^2) + ((-1)^(2/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(5/3)*b^(1/3))]
    @test_int [sin(c + d*x)/(x^2*(a + b*x^3)^2), x, 47, (d*cos(c)*CosIntegral(d*x))/a^2 + (d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^2) + (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^2) + (d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^2) + (4*b^(1/3)*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(7/3)) + (4*(-1)^(2/3)*b^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(7/3)) - (4*(-1)^(1/3)*b^(1/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(7/3)) + sin(c + d*x)/(3*a*b*x^4) - (4*sin(c + d*x))/(3*a^2*x) - sin(c + d*x)/(3*b*x^4*(a + b*x^3)) - (d*sin(c)*SinIntegral(d*x))/a^2 - (4*(-1)^(2/3)*b^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(7/3)) + (d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^2) + (4*b^(1/3)*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)) - (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^2) - (4*(-1)^(1/3)*b^(1/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)) - (d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^2)]
    @test_int [sin(c + d*x)/(x^3*(a + b*x^3)^2), x, 51, -((d*cos(c + d*x))/(2*a^2*x)) - ((-1)^(2/3)*b^(1/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(7/3)) - (b^(1/3)*d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)) + ((-1)^(1/3)*b^(1/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)) - (d^2*CosIntegral(d*x)*sin(c))/(2*a^2) - (5*b^(2/3)*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(9*a^(8/3)) + (5*(-1)^(1/3)*b^(2/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(8/3)) - (5*(-1)^(2/3)*b^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(9*a^(8/3)) + sin(c + d*x)/(3*a*b*x^5) - (5*sin(c + d*x))/(6*a^2*x^2) - sin(c + d*x)/(3*b*x^5*(a + b*x^3)) - (d^2*cos(c)*SinIntegral(d*x))/(2*a^2) - (5*(-1)^(1/3)*b^(2/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(8/3)) - ((-1)^(2/3)*b^(1/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(7/3)) - (5*b^(2/3)*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(8/3)) + (b^(1/3)*d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)) - (5*(-1)^(2/3)*b^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(8/3)) - ((-1)^(1/3)*b^(1/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3))]


    @test_int [(x^3*sin(c + d*x))/(a + b*x^3)^3, x, 71, (d*cos(c + d*x))/(18*a*b^2*x) - (d*cos(c + d*x))/(18*b^2*x*(a + b*x^3)) + (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(27*a^(5/3)*b^(4/3)) + (d^2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(54*a*b^2) - ((-1)^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(5/3)*b^(4/3)) + (d^2*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(54*a*b^2) + ((-1)^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(5/3)*b^(4/3)) + (d^2*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(54*a*b^2) + sin(c + d*x)/(18*a*b^2*x^2) - (x*sin(c + d*x))/(6*b*(a + b*x^3)^2) - sin(c + d*x)/(18*b^2*x^2*(a + b*x^3)) + ((-1)^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a*b^2) + (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) + (d^2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a*b^2) + ((-1)^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) + (d^2*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a*b^2)]
    @test_int [(x^2*sin(c + d*x))/(a + b*x^3)^3, x, 37, (d*cos(c + d*x))/(18*a*b^2*x^2) - (d*cos(c + d*x))/(18*b^2*x^2*(a + b*x^3)) - ((-1)^(1/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(5/3)*b^(4/3)) + (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) + ((-1)^(2/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(54*a^(4/3)*b^(5/3)) - ((-1)^(2/3)*d^2*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(54*a^(4/3)*b^(5/3)) + ((-1)^(1/3)*d^2*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(54*a^(4/3)*b^(5/3)) - sin(c + d*x)/(6*b*(a + b*x^3)^2) + ((-1)^(2/3)*d^2*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(4/3)*b^(5/3)) - ((-1)^(1/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(5/3)*b^(4/3)) - (d^2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(4/3)*b^(5/3)) - (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3)) + ((-1)^(1/3)*d^2*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(4/3)*b^(5/3)) - ((-1)^(2/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(5/3)*b^(4/3))]
    @test_int [(x*sin(c + d*x))/(a + b*x^3)^3, x, 89, (d*cos(c + d*x))/(18*a*b^2*x^3) - (d*cos(c + d*x))/(18*b^2*x^3*(a + b*x^3)) - (2*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^2*b) - (2*d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^2*b) - (2*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^2*b) - (2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(27*a^(7/3)*b^(2/3)) + (d^2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(54*a^(5/3)*b^(4/3)) - (2*(-1)^(2/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(7/3)*b^(2/3)) - ((-1)^(1/3)*d^2*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(54*a^(5/3)*b^(4/3)) + (2*(-1)^(1/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(7/3)*b^(2/3)) + ((-1)^(2/3)*d^2*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(54*a^(5/3)*b^(4/3)) - sin(c + d*x)/(18*a*b^2*x^4) + (2*sin(c + d*x))/(9*a^2*b*x) - sin(c + d*x)/(6*b*x*(a + b*x^3)^2) + sin(c + d*x)/(18*b^2*x^4*(a + b*x^3)) + (2*(-1)^(2/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(7/3)*b^(2/3)) + ((-1)^(1/3)*d^2*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(5/3)*b^(4/3)) - (2*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^2*b) - (2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(7/3)*b^(2/3)) + (d^2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(5/3)*b^(4/3)) + (2*d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^2*b) + (2*(-1)^(1/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(7/3)*b^(2/3)) + ((-1)^(2/3)*d^2*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(5/3)*b^(4/3)) + (2*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^2*b)]
    @test_int [sin(c + d*x)/(a + b*x^3)^3, x, 99, (d*cos(c + d*x))/(18*a*b^2*x^4) - (d*cos(c + d*x))/(18*a^2*b*x) - (d*cos(c + d*x))/(18*b^2*x^4*(a + b*x^3)) + ((-1)^(2/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(7/3)*b^(2/3)) + (d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)*b^(2/3)) - ((-1)^(1/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)*b^(2/3)) + (5*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(27*a^(8/3)*b^(1/3)) - (d^2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(54*a^2*b) - (5*(-1)^(1/3)*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(8/3)*b^(1/3)) - (d^2*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(54*a^2*b) + (5*(-1)^(2/3)*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(27*a^(8/3)*b^(1/3)) - (d^2*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(54*a^2*b) - sin(c + d*x)/(9*a*b^2*x^5) + (5*sin(c + d*x))/(18*a^2*b*x^2) - sin(c + d*x)/(6*b*x^2*(a + b*x^3)^2) + sin(c + d*x)/(9*b^2*x^5*(a + b*x^3)) + (5*(-1)^(1/3)*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(8/3)*b^(1/3)) + (d^2*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^2*b) + ((-1)^(2/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(9*a^(7/3)*b^(2/3)) + (5*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(8/3)*b^(1/3)) - (d^2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^2*b) - (d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)*b^(2/3)) + (5*(-1)^(2/3)*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(8/3)*b^(1/3)) - (d^2*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^2*b) + ((-1)^(1/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(9*a^(7/3)*b^(2/3))]
    @test_int [sin(c + d*x)/(x*(a + b*x^3)^3), x, 110, (d*cos(c + d*x))/(18*a*b^2*x^5) - (d*cos(c + d*x))/(18*a^2*b*x^2) - (d*cos(c + d*x))/(18*b^2*x^5*(a + b*x^3)) + (4*(-1)^(1/3)*d*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(8/3)*b^(1/3)) - (4*d*cos(c - (a^(1/3)*d)/b^(1/3))*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(8/3)*b^(1/3)) - (4*(-1)^(2/3)*d*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(8/3)*b^(1/3)) + (CosIntegral(d*x)*sin(c))/a^3 - (CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(3*a^3) + (d^2*CosIntegral((a^(1/3)*d)/b^(1/3) + d*x)*sin(c - (a^(1/3)*d)/b^(1/3)))/(54*a^(7/3)*b^(2/3)) - (CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(3*a^3) + ((-1)^(2/3)*d^2*CosIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x)*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3)))/(54*a^(7/3)*b^(2/3)) - (CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(3*a^3) - ((-1)^(1/3)*d^2*CosIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x)*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3)))/(54*a^(7/3)*b^(2/3)) - sin(c + d*x)/(6*a*b^2*x^6) + sin(c + d*x)/(3*a^2*b*x^3) - sin(c + d*x)/(6*b*x^3*(a + b*x^3)^2) + sin(c + d*x)/(6*b^2*x^6*(a + b*x^3)) + (cos(c)*SinIntegral(d*x))/a^3 + (cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(3*a^3) - ((-1)^(2/3)*d^2*cos(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(54*a^(7/3)*b^(2/3)) + (4*(-1)^(1/3)*d*sin(c + ((-1)^(1/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(1/3)*a^(1/3)*d)/b^(1/3) - d*x))/(27*a^(8/3)*b^(1/3)) - (cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(3*a^3) + (d^2*cos(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(7/3)*b^(2/3)) + (4*d*sin(c - (a^(1/3)*d)/b^(1/3))*SinIntegral((a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(8/3)*b^(1/3)) - (cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(3*a^3) - ((-1)^(1/3)*d^2*cos(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(54*a^(7/3)*b^(2/3)) + (4*(-1)^(2/3)*d*sin(c - ((-1)^(2/3)*a^(1/3)*d)/b^(1/3))*SinIntegral(((-1)^(2/3)*a^(1/3)*d)/b^(1/3) + d*x))/(27*a^(8/3)*b^(1/3))]
    end
