int_rules_7_2_2 = @theory begin

    #= ::Subsection::Closed:: =#
    #= 7.2.2*(d*x)^m*(a+b*arccosh(c*x))^n =#
    @apply_utils Antiderivative((~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~(n') / ~x, ~x) => (1 / ~b) * Subst(Antiderivative((~x) ^ ~n * tanh(-(~a) / ~b + ~x / ~b), ~x), ~x, ~a + ~b * acosh(~c * ~x)) <-- FreeQ([~a, ~b, ~c], ~x) && IGtQ(~n, 0)
    @apply_utils Antiderivative((~(d') * ~x) ^ ~(m') * (~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~(n'), ~x) => ((~d * ~x) ^ (~m + 1) * (~a + ~b * acosh(~c * ~x)) ^ ~n) / (~d * (~m + 1)) - ((~b * ~c * ~n) / (~d * (~m + 1))) * Antiderivative(((~d * ~x) ^ (~m + 1) * (~a + ~b * acosh(~c * ~x)) ^ (~n - 1)) / (sqrt(1 + ~c * ~x) * sqrt(-1 + ~c * ~x)), ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~m], ~x) && (IGtQ(~n, 0) && NeQ(~m, -1))
    @apply_utils Antiderivative((~x) ^ ~(m') * (~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~n, ~x) => ((~x) ^ (~m + 1) * (~a + ~b * acosh(~c * ~x)) ^ ~n) / (~m + 1) - ((~b * ~c * ~n) / (~m + 1)) * Antiderivative(((~x) ^ (~m + 1) * (~a + ~b * acosh(~c * ~x)) ^ (~n - 1)) / (sqrt(1 + ~c * ~x) * sqrt(-1 + ~c * ~x)), ~x) <-- FreeQ([~a, ~b, ~c], ~x) && (IGtQ(~m, 0) && GtQ(~n, 0))
    @apply_utils Antiderivative((~x) ^ ~(m') * (~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~n, ~x) => ((~x) ^ ~m * sqrt(1 + ~c * ~x) * sqrt(-1 + ~c * ~x) * (~a + ~b * acosh(~c * ~x)) ^ (~n + 1)) / (~b * ~c * (~n + 1)) + (1 / ((~b) ^ 2 * (~c) ^ (~m + 1) * (~n + 1))) * Subst(Antiderivative(ExpandTrigReduce((~x) ^ (~n + 1), cosh(-(~a) / ~b + ~x / ~b) ^ (~m - 1) * (~m - (~m + 1) * cosh(-(~a) / ~b + ~x / ~b) ^ 2), ~x), ~x), ~x, ~a + ~b * acosh(~c * ~x)) <-- FreeQ([~a, ~b, ~c], ~x) && (IGtQ(~m, 0) && (GeQ(~n, -2) && LtQ(~n, -1)))
    @apply_utils Antiderivative((~x) ^ ~(m') * (~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~n, ~x) => (((~x) ^ ~m * sqrt(1 + ~c * ~x) * sqrt(-1 + ~c * ~x) * (~a + ~b * acosh(~c * ~x)) ^ (~n + 1)) / (~b * ~c * (~n + 1)) + (~m / (~b * ~c * (~n + 1))) * Antiderivative(((~x) ^ (~m - 1) * (~a + ~b * acosh(~c * ~x)) ^ (~n + 1)) / (sqrt(1 + ~c * ~x) * sqrt(-1 + ~c * ~x)), ~x)) - ((~c * (~m + 1)) / (~b * (~n + 1))) * Antiderivative(((~x) ^ (~m + 1) * (~a + ~b * acosh(~c * ~x)) ^ (~n + 1)) / (sqrt(1 + ~c * ~x) * sqrt(-1 + ~c * ~x)), ~x) <-- FreeQ([~a, ~b, ~c], ~x) && (IGtQ(~m, 0) && LtQ(~n, -2))
    @apply_utils Antiderivative((~x) ^ ~(m') * (~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~n, ~x) => (1 / (~b * (~c) ^ (~m + 1))) * Subst(Antiderivative((~x) ^ ~n * cosh(-(~a) / ~b + ~x / ~b) ^ ~m * sinh(-(~a) / ~b + ~x / ~b), ~x), ~x, ~a + ~b * acosh(~c * ~x)) <-- FreeQ([~a, ~b, ~c, ~n], ~x) && IGtQ(~m, 0)
    @apply_utils Antiderivative((~(d') * ~x) ^ ~(m') * (~(a') + ~(b') * acosh(~(c') * ~x)) ^ ~(n'), ~x) => Unintegrable((~d * ~x) ^ ~m * (~a + ~b * acosh(~c * ~x)) ^ ~n, ~x) <-- FreeQ([~a, ~b, ~c, ~d, ~m, ~n], ~x)
end
