@testset "7.5.1 u (a+b arcsech(c x))^n" begin
    (a, b, c, d, e, f, m, x, ) = @variables a b c d e f m x

    #= ::Package:: =#

    #= ::Title:: =#
    #=Integrands*of*the*form*u*(a+b*asech(c*x))^n=#


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(d*x)^m*(a+b*asech(c*x))^n=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*x^m*asech(a*x)^n=#


    @test_int [x^4*asech(a*x)^2, x, 9, -((3*x)/(20*a^4)) - x^3/(30*a^2) - (3*x*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(20*a^4) - (x^3*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(10*a^2) + (1/5)*x^5*asech(a*x)^2 - (3*asech(a*x)*atan(ℯ^asech(a*x)))/(10*a^5) + (3*im*PolyLog(2, (-im)*ℯ^asech(a*x)))/(20*a^5) - (3*im*PolyLog(2, im*ℯ^asech(a*x)))/(20*a^5)]
    @test_int [x^3*asech(a*x)^2, x, 5, -(x^2/(12*a^2)) - (sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(3*a^4) - (x^2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(6*a^2) + (1/4)*x^4*asech(a*x)^2 - log(x)/(3*a^4)]
    @test_int [x^2*asech(a*x)^2, x, 8, -(x/(3*a^2)) - (x*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(3*a^2) + (1/3)*x^3*asech(a*x)^2 - (2*asech(a*x)*atan(ℯ^asech(a*x)))/(3*a^3) + (im*PolyLog(2, (-im)*ℯ^asech(a*x)))/(3*a^3) - (im*PolyLog(2, im*ℯ^asech(a*x)))/(3*a^3)]
    @test_int [x^1*asech(a*x)^2, x, 4, -((sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/a^2) + (1/2)*x^2*asech(a*x)^2 - log(x)/a^2]
    @test_int [x^0*asech(a*x)^2, x, 7, x*asech(a*x)^2 - (4*asech(a*x)*atan(ℯ^asech(a*x)))/a + (2*im*PolyLog(2, (-im)*ℯ^asech(a*x)))/a - (2*im*PolyLog(2, im*ℯ^asech(a*x)))/a]
    @test_int [asech(a*x)^2/x^1, x, 6, (1/3)*asech(a*x)^3 - asech(a*x)^2*log(1 + ℯ^(2*asech(a*x))) - asech(a*x)*PolyLog(2, -ℯ^(2*asech(a*x))) + (1/2)*PolyLog(3, -ℯ^(2*asech(a*x)))]
    @test_int [asech(a*x)^2/x^2, x, 4, -(2/x) + (2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/x - asech(a*x)^2/x]
    @test_int [asech(a*x)^2/x^3, x, 4, -(((1 - a*x)*(1 + a*x))/(4*x^2)) + (sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(2*x^2) - (1/4)*a^2*asech(a*x)^2 - ((1 - a*x)*(1 + a*x)*asech(a*x)^2)/(2*x^2)]
    @test_int [asech(a*x)^2/x^4, x, 5, -(2/(27*x^3)) - (4*a^2)/(9*x) + (2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(9*x^3) + (4*a^2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x))/(9*x) - asech(a*x)^2/(3*x^3)]


    @test_int [x^4*asech(a*x)^3, x, 14, (x*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/(20*a^4) - (9*x*asech(a*x))/(20*a^4) - (x^3*asech(a*x))/(10*a^2) - (9*x*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(40*a^4) - (3*x^3*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(20*a^2) + (1/5)*x^5*asech(a*x)^3 - (9*asech(a*x)^2*atan(ℯ^asech(a*x)))/(20*a^5) + atan((sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/(a*x))/(2*a^5) + (9*im*asech(a*x)*PolyLog(2, (-im)*ℯ^asech(a*x)))/(20*a^5) - (9*im*asech(a*x)*PolyLog(2, im*ℯ^asech(a*x)))/(20*a^5) - (9*im*PolyLog(3, (-im)*ℯ^asech(a*x)))/(20*a^5) + (9*im*PolyLog(3, im*ℯ^asech(a*x)))/(20*a^5)]
    @test_int [x^3*asech(a*x)^3, x, 10, (sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/(4*a^4) - (x^2*asech(a*x))/(4*a^2) - asech(a*x)^2/(2*a^4) - (sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(2*a^4) - (x^2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(4*a^2) + (1/4)*x^4*asech(a*x)^3 + (asech(a*x)*log(1 + ℯ^(2*asech(a*x))))/a^4 + PolyLog(2, -ℯ^(2*asech(a*x)))/(2*a^4)]
    @test_int [x^2*asech(a*x)^3, x, 11, -((x*asech(a*x))/a^2) - (x*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(2*a^2) + (1/3)*x^3*asech(a*x)^3 - (asech(a*x)^2*atan(ℯ^asech(a*x)))/a^3 + atan((sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/(a*x))/a^3 + (im*asech(a*x)*PolyLog(2, (-im)*ℯ^asech(a*x)))/a^3 - (im*asech(a*x)*PolyLog(2, im*ℯ^asech(a*x)))/a^3 - (im*PolyLog(3, (-im)*ℯ^asech(a*x)))/a^3 + (im*PolyLog(3, im*ℯ^asech(a*x)))/a^3]
    @test_int [x^1*asech(a*x)^3, x, 7, -((3*asech(a*x)^2)/(2*a^2)) - (3*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(2*a^2) + (1/2)*x^2*asech(a*x)^3 + (3*asech(a*x)*log(1 + ℯ^(2*asech(a*x))))/a^2 + (3*PolyLog(2, -ℯ^(2*asech(a*x))))/(2*a^2)]
    @test_int [x^0*asech(a*x)^3, x, 9, x*asech(a*x)^3 - (6*asech(a*x)^2*atan(ℯ^asech(a*x)))/a + (6*im*asech(a*x)*PolyLog(2, (-im)*ℯ^asech(a*x)))/a - (6*im*asech(a*x)*PolyLog(2, im*ℯ^asech(a*x)))/a - (6*im*PolyLog(3, (-im)*ℯ^asech(a*x)))/a + (6*im*PolyLog(3, im*ℯ^asech(a*x)))/a]
    @test_int [asech(a*x)^3/x^1, x, 7, (1/4)*asech(a*x)^4 - asech(a*x)^3*log(1 + ℯ^(2*asech(a*x))) - (3/2)*asech(a*x)^2*PolyLog(2, -ℯ^(2*asech(a*x))) + (3/2)*asech(a*x)*PolyLog(3, -ℯ^(2*asech(a*x))) - (3/4)*PolyLog(4, -ℯ^(2*asech(a*x)))]
    @test_int [asech(a*x)^3/x^2, x, 5, (6*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/x - (6*asech(a*x))/x + (3*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/x - asech(a*x)^3/x]
    @test_int [asech(a*x)^3/x^3, x, 6, (3*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/(8*x^2) - (3/8)*a^2*asech(a*x) - (3*(1 - a*x)*(1 + a*x)*asech(a*x))/(4*x^2) + (3*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(4*x^2) - (1/4)*a^2*asech(a*x)^3 - ((1 - a*x)*(1 + a*x)*asech(a*x)^3)/(2*x^2)]
    @test_int [asech(a*x)^3/x^4, x, 8, (14*a^2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x))/(9*x) + (2*((1 - a*x)/(1 + a*x))^(3/2)*(1 + a*x)^3)/(27*x^3) - (2*asech(a*x))/(9*x^3) - (4*a^2*asech(a*x))/(3*x) + (sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(3*x^3) + (2*a^2*sqrt((1 - a*x)/(1 + a*x))*(1 + a*x)*asech(a*x)^2)/(3*x) - asech(a*x)^3/(3*x^3)]


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*x^m*(a+b*asech(c*x))^n=#


    #= ::Subsubsection::Closed:: =#
    #=n>0=#


    @test_int [x^6*(a + b*asech(c*x)), x, 8, -((5*b*x*sqrt(1 - c*x))/(112*c^6*sqrt(1/(1 + c*x)))) - (5*b*x^3*sqrt(1 - c*x))/(168*c^4*sqrt(1/(1 + c*x))) - (b*x^5*sqrt(1 - c*x))/(42*c^2*sqrt(1/(1 + c*x))) + (1/7)*x^7*(a + b*asech(c*x)) + (5*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(112*c^7)]
    @test_int [x^5*(a + b*asech(c*x)), x, 6, -((4*b*sqrt(1 - c*x))/(45*c^6*sqrt(1/(1 + c*x)))) - (2*b*x^2*sqrt(1 - c*x))/(45*c^4*sqrt(1/(1 + c*x))) - (b*x^4*sqrt(1 - c*x))/(30*c^2*sqrt(1/(1 + c*x))) + (1/6)*x^6*(a + b*asech(c*x))]
    @test_int [x^4*(a + b*asech(c*x)), x, 6, -((3*b*x*sqrt(1 - c*x))/(40*c^4*sqrt(1/(1 + c*x)))) - (b*x^3*sqrt(1 - c*x))/(20*c^2*sqrt(1/(1 + c*x))) + (1/5)*x^5*(a + b*asech(c*x)) + (3*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(40*c^5)]
    @test_int [x^3*(a + b*asech(c*x)), x, 4, -((b*sqrt(1 - c*x))/(6*c^4*sqrt(1/(1 + c*x)))) - (b*x^2*sqrt(1 - c*x))/(12*c^2*sqrt(1/(1 + c*x))) + (1/4)*x^4*(a + b*asech(c*x))]
    @test_int [x^2*(a + b*asech(c*x)), x, 4, -((b*x*sqrt(1 - c*x))/(6*c^2*sqrt(1/(1 + c*x)))) + (1/3)*x^3*(a + b*asech(c*x)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(6*c^3)]
    @test_int [x^1*(a + b*asech(c*x)), x, 2, -((b*sqrt(1 - c*x))/(2*c^2*sqrt(1/(1 + c*x)))) + (1/2)*x^2*(a + b*asech(c*x))]
    @test_int [x^0*(a + b*asech(c*x)), x, 3, a*x + b*x*asech(c*x) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/c]
    @test_int [(a + b*asech(c*x))/x^1, x, 6, -((a + b*asech(c*x))^2/(2*b)) - (a + b*asech(c*x))*log(1 + ℯ^(-2*asech(c*x))) + (1/2)*b*PolyLog(2, -ℯ^(-2*asech(c*x)))]
    @test_int [(a + b*asech(c*x))/x^2, x, 2, (b*sqrt(1 - c*x))/(x*sqrt(1/(1 + c*x))) - (a + b*asech(c*x))/x]
    @test_int [(a + b*asech(c*x))/x^3, x, 5, (b*sqrt(1 - c*x))/(4*x^2*sqrt(1/(1 + c*x))) - (a + b*asech(c*x))/(2*x^2) + (1/4)*b*c^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c*x)*sqrt(1 + c*x))]
    @test_int [(a + b*asech(c*x))/x^4, x, 4, (b*sqrt(1 - c*x))/(9*x^3*sqrt(1/(1 + c*x))) + (2*b*c^2*sqrt(1 - c*x))/(9*x*sqrt(1/(1 + c*x))) - (a + b*asech(c*x))/(3*x^3)]
    @test_int [(a + b*asech(c*x))/x^5, x, 7, (b*sqrt(1 - c*x))/(16*x^4*sqrt(1/(1 + c*x))) + (3*b*c^2*sqrt(1 - c*x))/(32*x^2*sqrt(1/(1 + c*x))) - (a + b*asech(c*x))/(4*x^4) + (3/32)*b*c^4*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c*x)*sqrt(1 + c*x))]
    @test_int [(a + b*asech(c*x))/x^6, x, 6, (b*sqrt(1 - c*x))/(25*x^5*sqrt(1/(1 + c*x))) + (4*b*c^2*sqrt(1 - c*x))/(75*x^3*sqrt(1/(1 + c*x))) + (8*b*c^4*sqrt(1 - c*x))/(75*x*sqrt(1/(1 + c*x))) - (a + b*asech(c*x))/(5*x^5)]
    @test_int [(a + b*asech(c*x))/x^7, x, 9, (b*sqrt(1 - c*x))/(36*x^6*sqrt(1/(1 + c*x))) + (5*b*c^2*sqrt(1 - c*x))/(144*x^4*sqrt(1/(1 + c*x))) + (5*b*c^4*sqrt(1 - c*x))/(96*x^2*sqrt(1/(1 + c*x))) - (a + b*asech(c*x))/(6*x^6) + (5/96)*b*c^6*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c*x)*sqrt(1 + c*x))]


    @test_int [x^3*(a + b*asech(c*x))^2, x, 5, -((b^2*x^2)/(12*c^2)) - (b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(3*c^4) - (b*x^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(6*c^2) + (1/4)*x^4*(a + b*asech(c*x))^2 - (b^2*log(x))/(3*c^4)]
    @test_int [x^2*(a + b*asech(c*x))^2, x, 8, -((b^2*x)/(3*c^2)) - (b*x*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(3*c^2) + (1/3)*x^3*(a + b*asech(c*x))^2 - (2*b*(a + b*asech(c*x))*atan(ℯ^asech(c*x)))/(3*c^3) + (im*b^2*PolyLog(2, (-im)*ℯ^asech(c*x)))/(3*c^3) - (im*b^2*PolyLog(2, im*ℯ^asech(c*x)))/(3*c^3)]
    @test_int [x^1*(a + b*asech(c*x))^2, x, 4, -((b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/c^2) + (1/2)*x^2*(a + b*asech(c*x))^2 - (b^2*log(x))/c^2]
    @test_int [x^0*(a + b*asech(c*x))^2, x, 7, x*(a + b*asech(c*x))^2 - (4*b*(a + b*asech(c*x))*atan(ℯ^asech(c*x)))/c + (2*im*b^2*PolyLog(2, (-im)*ℯ^asech(c*x)))/c - (2*im*b^2*PolyLog(2, im*ℯ^asech(c*x)))/c]
    @test_int [(a + b*asech(c*x))^2/x^1, x, 6, (a + b*asech(c*x))^3/(3*b) - (a + b*asech(c*x))^2*log(1 + ℯ^(2*asech(c*x))) - b*(a + b*asech(c*x))*PolyLog(2, -ℯ^(2*asech(c*x))) + (1/2)*b^2*PolyLog(3, -ℯ^(2*asech(c*x)))]
    @test_int [(a + b*asech(c*x))^2/x^2, x, 4, -((2*b^2)/x) + (2*b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/x - (a + b*asech(c*x))^2/x]
    @test_int [(a + b*asech(c*x))^2/x^3, x, 4, -((b^2*(1 - c*x)*(1 + c*x))/(4*x^2)) - (1/2)*a*b*c^2*asech(c*x) - (1/4)*b^2*c^2*asech(c*x)^2 + (b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(2*x^2) - ((1 - c*x)*(1 + c*x)*(a + b*asech(c*x))^2)/(2*x^2)]
    @test_int [(a + b*asech(c*x))^2/x^4, x, 5, -((2*b^2)/(27*x^3)) - (4*b^2*c^2)/(9*x) + (2*b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(9*x^3) + (4*b*c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(9*x) - (a + b*asech(c*x))^2/(3*x^3)]
    @test_int [(a + b*asech(c*x))^2/x^5, x, 5, -(b^2/(32*x^4)) - (3*b^2*c^2)/(32*x^2) + (3/16)*a*b*c^4*asech(c*x) + (3/32)*b^2*c^4*asech(c*x)^2 + (b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(8*x^4) + (3*b*c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x)))/(16*x^2) - (a + b*asech(c*x))^2/(4*x^4)]


    @test_int [x^3*(a + b*asech(c*x))^3, x, 10, (b^3*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(4*c^4) - (b^2*x^2*(a + b*asech(c*x)))/(4*c^2) - (b*(a + b*asech(c*x))^2)/(2*c^4) - (b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(2*c^4) - (b*x^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(4*c^2) + (1/4)*x^4*(a + b*asech(c*x))^3 + (b^2*(a + b*asech(c*x))*log(1 + ℯ^(2*asech(c*x))))/c^4 + (b^3*PolyLog(2, -ℯ^(2*asech(c*x))))/(2*c^4)]
    @test_int [x^2*(a + b*asech(c*x))^3, x, 11, -((b^2*x*(a + b*asech(c*x)))/c^2) - (b*x*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(2*c^2) + (1/3)*x^3*(a + b*asech(c*x))^3 - (b*(a + b*asech(c*x))^2*atan(ℯ^asech(c*x)))/c^3 + (b^3*atan((sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(c*x)))/c^3 + (im*b^2*(a + b*asech(c*x))*PolyLog(2, (-im)*ℯ^asech(c*x)))/c^3 - (im*b^2*(a + b*asech(c*x))*PolyLog(2, im*ℯ^asech(c*x)))/c^3 - (im*b^3*PolyLog(3, (-im)*ℯ^asech(c*x)))/c^3 + (im*b^3*PolyLog(3, im*ℯ^asech(c*x)))/c^3]
    @test_int [x^1*(a + b*asech(c*x))^3, x, 7, -((3*b*(a + b*asech(c*x))^2)/(2*c^2)) - (3*b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(2*c^2) + (1/2)*x^2*(a + b*asech(c*x))^3 + (3*b^2*(a + b*asech(c*x))*log(1 + ℯ^(2*asech(c*x))))/c^2 + (3*b^3*PolyLog(2, -ℯ^(2*asech(c*x))))/(2*c^2)]
    @test_int [x^0*(a + b*asech(c*x))^3, x, 9, x*(a + b*asech(c*x))^3 - (6*b*(a + b*asech(c*x))^2*atan(ℯ^asech(c*x)))/c + (6*im*b^2*(a + b*asech(c*x))*PolyLog(2, (-im)*ℯ^asech(c*x)))/c - (6*im*b^2*(a + b*asech(c*x))*PolyLog(2, im*ℯ^asech(c*x)))/c - (6*im*b^3*PolyLog(3, (-im)*ℯ^asech(c*x)))/c + (6*im*b^3*PolyLog(3, im*ℯ^asech(c*x)))/c]
    @test_int [(a + b*asech(c*x))^3/x^1, x, 7, (a + b*asech(c*x))^4/(4*b) - (a + b*asech(c*x))^3*log(1 + ℯ^(2*asech(c*x))) - (3/2)*b*(a + b*asech(c*x))^2*PolyLog(2, -ℯ^(2*asech(c*x))) + (3/2)*b^2*(a + b*asech(c*x))*PolyLog(3, -ℯ^(2*asech(c*x))) - (3/4)*b^3*PolyLog(4, -ℯ^(2*asech(c*x)))]
    @test_int [(a + b*asech(c*x))^3/x^2, x, 5, (6*b^3*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/x - (6*b^2*(a + b*asech(c*x)))/x + (3*b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/x - (a + b*asech(c*x))^3/x]
    @test_int [(a + b*asech(c*x))^3/x^3, x, 6, (3*b^3*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(8*x^2) - (3/8)*b^3*c^2*asech(c*x) - (3*b^2*(1 - c*x)*(1 + c*x)*(a + b*asech(c*x)))/(4*x^2) + (3*b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(4*x^2) - (1/4)*c^2*(a + b*asech(c*x))^3 - ((1 - c*x)*(1 + c*x)*(a + b*asech(c*x))^3)/(2*x^2)]
    @test_int [(a + b*asech(c*x))^3/x^4, x, 8, (14*b^3*c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(9*x) + (2*b^3*((1 - c*x)/(1 + c*x))^(3/2)*(1 + c*x)^3)/(27*x^3) - (2*b^2*(a + b*asech(c*x)))/(9*x^3) - (4*b^2*c^2*(a + b*asech(c*x)))/(3*x) + (b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(3*x^3) + (2*b*c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(3*x) - (a + b*asech(c*x))^3/(3*x^3)]
    @test_int [(a + b*asech(c*x))^3/x^5, x, 10, (3*b^3*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(128*x^4) + (45*b^3*c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(256*x^2) + (45/256)*b^3*c^4*asech(c*x) - (3*b^2*(a + b*asech(c*x)))/(32*x^4) - (9*b^2*c^2*(a + b*asech(c*x)))/(32*x^2) + (3*b*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(16*x^4) + (9*b*c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x)*(a + b*asech(c*x))^2)/(32*x^2) + (3/32)*c^4*(a + b*asech(c*x))^3 - (a + b*asech(c*x))^3/(4*x^4)]


    #= ::Subsubsection::Closed:: =#
    #=n<0=#


    @test_int [x^1/(a + b*asech(c*x)), x, 0, Unintegrable(x/(a + b*asech(c*x)), x)]
    @test_int [x^0/(a + b*asech(c*x)), x, 0, Unintegrable(1/(a + b*asech(c*x)), x)]
    @test_int [1/(x^1*(a + b*asech(c*x))), x, 0, Unintegrable(1/(x*(a + b*asech(c*x))), x)]
    @test_int [1/(x^2*(a + b*asech(c*x))), x, 4, (c*CoshIntegral(a/b + asech(c*x))*sinh(a/b))/b - (c*cosh(a/b)*SinhIntegral(a/b + asech(c*x)))/b]
    @test_int [1/(x^3*(a + b*asech(c*x))), x, 6, (c^2*CoshIntegral((2*a)/b + 2*asech(c*x))*sinh((2*a)/b))/(2*b) - (c^2*cosh((2*a)/b)*SinhIntegral((2*a)/b + 2*asech(c*x)))/(2*b)]
    @test_int [1/(x^4*(a + b*asech(c*x))), x, 9, (c^3*CoshIntegral(a/b + asech(c*x))*sinh(a/b))/(4*b) + (c^3*CoshIntegral((3*a)/b + 3*asech(c*x))*sinh((3*a)/b))/(4*b) - (c^3*cosh(a/b)*SinhIntegral(a/b + asech(c*x)))/(4*b) - (c^3*cosh((3*a)/b)*SinhIntegral((3*a)/b + 3*asech(c*x)))/(4*b)]


    @test_int [x^1/(a + b*asech(c*x))^2, x, 0, Unintegrable(x/(a + b*asech(c*x))^2, x)]
    @test_int [x^0/(a + b*asech(c*x))^2, x, 0, Unintegrable(1/(a + b*asech(c*x))^2, x)]
    @test_int [1/(x^1*(a + b*asech(c*x))^2), x, 0, Unintegrable(1/(x*(a + b*asech(c*x))^2), x)]
    @test_int [1/(x^2*(a + b*asech(c*x))^2), x, 5, (sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(b*x*(a + b*asech(c*x))) - (c*cosh(a/b)*CoshIntegral(a/b + asech(c*x)))/b^2 + (c*sinh(a/b)*SinhIntegral(a/b + asech(c*x)))/b^2]
    @test_int [1/(x^3*(a + b*asech(c*x))^2), x, 7, -((c^2*cosh((2*a)/b)*CoshIntegral((2*a)/b + 2*asech(c*x)))/b^2) + (c^2*sinh(2*asech(c*x)))/(2*b*(a + b*asech(c*x))) + (c^2*sinh((2*a)/b)*SinhIntegral((2*a)/b + 2*asech(c*x)))/b^2]
    @test_int [1/(x^4*(a + b*asech(c*x))^2), x, 11, (c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(4*b*x*(a + b*asech(c*x))) - (c^3*cosh(a/b)*CoshIntegral(a/b + asech(c*x)))/(4*b^2) - (3*c^3*cosh((3*a)/b)*CoshIntegral((3*a)/b + 3*asech(c*x)))/(4*b^2) + (c^3*sinh(3*asech(c*x)))/(4*b*(a + b*asech(c*x))) + (c^3*sinh(a/b)*SinhIntegral(a/b + asech(c*x)))/(4*b^2) + (3*c^3*sinh((3*a)/b)*SinhIntegral((3*a)/b + 3*asech(c*x)))/(4*b^2)]


    @test_int [x^1/(a + b*asech(c*x))^3, x, 0, Unintegrable(x/(a + b*asech(c*x))^3, x)]
    @test_int [x^0/(a + b*asech(c*x))^3, x, 0, Unintegrable(1/(a + b*asech(c*x))^3, x)]
    @test_int [1/(x^1*(a + b*asech(c*x))^3), x, 0, Unintegrable(1/(x*(a + b*asech(c*x))^3), x)]
    @test_int [1/(x^2*(a + b*asech(c*x))^3), x, 6, (sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(2*b*x*(a + b*asech(c*x))^2) + 1/(2*b^2*x*(a + b*asech(c*x))) + (c*CoshIntegral(a/b + asech(c*x))*sinh(a/b))/(2*b^3) - (c*cosh(a/b)*SinhIntegral(a/b + asech(c*x)))/(2*b^3)]
    @test_int [1/(x^3*(a + b*asech(c*x))^3), x, 8, (c^2*cosh(2*asech(c*x)))/(2*b^2*(a + b*asech(c*x))) + (c^2*CoshIntegral((2*a)/b + 2*asech(c*x))*sinh((2*a)/b))/b^3 + (c^2*sinh(2*asech(c*x)))/(4*b*(a + b*asech(c*x))^2) - (c^2*cosh((2*a)/b)*SinhIntegral((2*a)/b + 2*asech(c*x)))/b^3]
    @test_int [1/(x^4*(a + b*asech(c*x))^3), x, 13, (c^2*sqrt((1 - c*x)/(1 + c*x))*(1 + c*x))/(8*b*x*(a + b*asech(c*x))^2) + c^2/(8*b^2*x*(a + b*asech(c*x))) + (3*c^3*cosh(3*asech(c*x)))/(8*b^2*(a + b*asech(c*x))) + (c^3*CoshIntegral(a/b + asech(c*x))*sinh(a/b))/(8*b^3) + (9*c^3*CoshIntegral((3*a)/b + 3*asech(c*x))*sinh((3*a)/b))/(8*b^3) + (c^3*sinh(3*asech(c*x)))/(8*b*(a + b*asech(c*x))^2) - (c^3*cosh(a/b)*SinhIntegral(a/b + asech(c*x)))/(8*b^3) - (9*c^3*cosh((3*a)/b)*SinhIntegral((3*a)/b + 3*asech(c*x)))/(8*b^3)]


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*(d*x)^m*(a+b*asech(c*x))^n*when*m*symbolic=#


    @test_int [(d*x)^m*(a + b*asech(c*x))^3, x, 0, Unintegrable((d*x)^m*(a + b*asech(c*x))^3, x)]
    @test_int [(d*x)^m*(a + b*asech(c*x))^2, x, 0, Unintegrable((d*x)^m*(a + b*asech(c*x))^2, x)]
    @test_int [(d*x)^m*(a + b*asech(c*x)), x, 3, ((d*x)^(1 + m)*(a + b*asech(c*x)))/(d*(1 + m)) + (b*(d*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*HypergeometricFunctions._₂F₁(1/2, (1 + m)/2, (3 + m)/2, c^2*x^2))/(d*(1 + m)^2)]
    @test_int [(d*x)^m/(a + b*asech(c*x)), x, 0, Unintegrable((d*x)^m/(a + b*asech(c*x)), x)]
    @test_int [(d*x)^m/(a + b*asech(c*x))^2, x, 0, Unintegrable((d*x)^m/(a + b*asech(c*x))^2, x)]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(f*x)^m*(d+e*x)^m*(a+b*asech(c*x))^n=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*(d+e*x)^m*(a+b*asech(c*x))^n=#


    #= ::Subsubsection::Closed:: =#
    #=n>0=#


    @test_int [(d + e*x)^3*(a + b*asech(c*x)), x, 9, -((b*e*(9*c^2*d^2 + e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(6*c^4)) - (b*d*e^2*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(2*c^2) - (b*e^3*x^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(12*c^2) + ((d + e*x)^4*(a + b*asech(c*x)))/(4*e) + (b*d*(2*c^2*d^2 + e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(2*c^3) - (b*d^4*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(4*e)]
    @test_int [(d + e*x)^2*(a + b*asech(c*x)), x, 8, -((b*d*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/c^2) - (b*e^2*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(6*c^2) + ((d + e*x)^3*(a + b*asech(c*x)))/(3*e) + (b*(6*c^2*d^2 + e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(6*c^3) - (b*d^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(3*e)]
    @test_int [(d + e*x)^1*(a + b*asech(c*x)), x, 7, -((b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(2*c^2)) + ((d + e*x)^2*(a + b*asech(c*x)))/(2*e) + (b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/c - (b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(2*e)]
    @test_int [(d + e*x)^0*(a + b*asech(c*x)), x, 3, a*x + b*x*asech(c*x) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/c]
    @test_int [(a + b*asech(c*x))/(d + e*x)^1, x, 4, -(((a + b*asech(c*x))*log(1 + ℯ^(-2*asech(c*x))))/e) + ((a + b*asech(c*x))*log(1 + (e - sqrt((-c^2)*d^2 + e^2))/(ℯ^asech(c*x)*(c*d))))/e + ((a + b*asech(c*x))*log(1 + (e + sqrt((-c^2)*d^2 + e^2))/(ℯ^asech(c*x)*(c*d))))/e + (b*PolyLog(2, -ℯ^(-2*asech(c*x))))/(2*e) - (b*PolyLog(2, -((e - sqrt((-c^2)*d^2 + e^2))/(ℯ^asech(c*x)*(c*d)))))/e - (b*PolyLog(2, -((e + sqrt((-c^2)*d^2 + e^2))/(ℯ^asech(c*x)*(c*d)))))/e]
    @test_int [(a + b*asech(c*x))/(d + e*x)^2, x, 8, -((a + b*asech(c*x))/(e*(d + e*x))) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((e + c^2*d*x)/(sqrt(c^2*d^2 - e^2)*sqrt(1 - c^2*x^2))))/(d*sqrt(c^2*d^2 - e^2)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(d*e)]
    @test_int [(a + b*asech(c*x))/(d + e*x)^3, x, 11, (b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(2*d*(c^2*d^2 - e^2)*(d + e*x)) - (a + b*asech(c*x))/(2*e*(d + e*x)^2) + (b*c^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((e + c^2*d*x)/(sqrt(c^2*d^2 - e^2)*sqrt(1 - c^2*x^2))))/(2*(c^2*d^2 - e^2)^(3/2)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((e + c^2*d*x)/(sqrt(c^2*d^2 - e^2)*sqrt(1 - c^2*x^2))))/(2*d^2*sqrt(c^2*d^2 - e^2)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(2*d^2*e)]


    #= ::Subsubsection:: =#
    #=n<0=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*(d+e*x)^(m/2)*(a+b*asech(c*x))^n=#


    #= ::Subsubsection::Closed:: =#
    #=n>0=#


    @test_int [(d + e*x)^(3/2)*(a + b*asech(c*x)), x, 21, -((4*b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x)*sqrt(1 - c^2*x^2))/(15*c^2)) + (2*(d + e*x)^(5/2)*(a + b*asech(c*x)))/(5*e) - (28*b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x)*Elliptic.E(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(15*c*sqrt((c*(d + e*x))/(c*d + e))) - (4*b*(2*c^2*d^2 + e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.F(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(15*c^3*sqrt(d + e*x)) - (4*b*d^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.Pi(2, asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(5*e*sqrt(d + e*x))]
    @test_int [(d + e*x)^(1/2)*(a + b*asech(c*x)), x, 14, (2*(d + e*x)^(3/2)*(a + b*asech(c*x)))/(3*e) - (4*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x)*Elliptic.E(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(3*c*sqrt((c*(d + e*x))/(c*d + e))) - (4*b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.F(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(3*c*sqrt(d + e*x)) - (4*b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.Pi(2, asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(3*e*sqrt(d + e*x))]
    @test_int [(a + b*asech(c*x))/(d + e*x)^(1/2), x, 8, (2*sqrt(d + e*x)*(a + b*asech(c*x)))/e - (4*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.F(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(c*sqrt(d + e*x)) - (4*b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.Pi(2, asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(e*sqrt(d + e*x))]
    @test_int [(a + b*asech(c*x))/(d + e*x)^(3/2), x, 5, -((2*(a + b*asech(c*x)))/(e*sqrt(d + e*x))) + (4*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.Pi(2, asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(e*sqrt(d + e*x))]
    @test_int [(a + b*asech(c*x))/(d + e*x)^(5/2), x, 11, (4*b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3*d*(c^2*d^2 - e^2)*sqrt(d + e*x)) - (2*(a + b*asech(c*x)))/(3*e*(d + e*x)^(3/2)) - (4*b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x)*Elliptic.E(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(3*d*(c^2*d^2 - e^2)*sqrt((c*(d + e*x))/(c*d + e))) + (4*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.Pi(2, asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(3*d*e*sqrt(d + e*x))]
    @test_int [(a + b*asech(c*x))/(d + e*x)^(7/2), x, 18, (4*b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(15*d*(c^2*d^2 - e^2)*(d + e*x)^(3/2)) + (16*b*c^2*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(15*(c^2*d^2 - e^2)^2*sqrt(d + e*x)) + (4*b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(5*d^2*(c^2*d^2 - e^2)*sqrt(d + e*x)) - (2*(a + b*asech(c*x)))/(5*e*(d + e*x)^(5/2)) - (16*b*c^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x)*Elliptic.E(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(15*(c^2*d^2 - e^2)^2*sqrt((c*(d + e*x))/(c*d + e))) - (4*b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x)*Elliptic.E(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(5*d^2*(c^2*d^2 - e^2)*sqrt((c*(d + e*x))/(c*d + e))) + (4*b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.F(asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(15*d*(c^2*d^2 - e^2)*sqrt(d + e*x)) + (4*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt((c*(d + e*x))/(c*d + e))*Elliptic.Pi(2, asin(sqrt(1 - c*x)/sqrt(2)), (2*e)/(c*d + e)))/(5*d^2*e*sqrt(d + e*x))]


    #= ::Subsubsection:: =#
    #=n<0=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*(d+e*x)^m*(a+b*asech(c*x))^n*when*m*symbolic=#


    @test_int [(d + e*x)^m*(a + b*asech(c*x)), x, 1, ((d + e*x)^(1 + m)*(a + b*asech(c*x)))/(e*(1 + m)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*Unintegrable((d + e*x)^(1 + m)/(x*sqrt(1 - c^2*x^2)), x))/(e*(1 + m))]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(f*x)^m*(d+e*x^2)^p*(a+b*asech(c*x))^n=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*x^m*(d+e*x^2)^p*(a+b*asech(c*x))=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^4*(d + e*x^2)*(a + b*asech(c*x)), x, 6, -((b*(42*c^2*d + 25*e)*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(560*c^6)) - (b*(42*c^2*d + 25*e)*x^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(840*c^4) - (b*e*x^5*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(42*c^2) + (1/5)*d*x^5*(a + b*asech(c*x)) + (1/7)*e*x^7*(a + b*asech(c*x)) + (b*(42*c^2*d + 25*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(560*c^7)]
    @test_int [x^2*(d + e*x^2)*(a + b*asech(c*x)), x, 5, -((b*(20*c^2*d + 9*e)*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(120*c^4)) - (b*e*x^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(20*c^2) + (1/3)*d*x^3*(a + b*asech(c*x)) + (1/5)*e*x^5*(a + b*asech(c*x)) + (b*(20*c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(120*c^5)]
    @test_int [x^0*(d + e*x^2)*(a + b*asech(c*x)), x, 4, -((b*e*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(6*c^2)) + d*x*(a + b*asech(c*x)) + (1/3)*e*x^3*(a + b*asech(c*x)) + (b*(6*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(6*c^3)]
    @test_int [((d + e*x^2)*(a + b*asech(c*x)))/x^2, x, 3, (b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/x - (d*(a + b*asech(c*x)))/x + e*x*(a + b*asech(c*x)) + (b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/c]
    @test_int [((d + e*x^2)*(a + b*asech(c*x)))/x^4, x, 4, (b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(9*x^3) + (b*(2*c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(9*x) - (d*(a + b*asech(c*x)))/(3*x^3) - (e*(a + b*asech(c*x)))/x]
    @test_int [((d + e*x^2)*(a + b*asech(c*x)))/x^6, x, 5, (b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(25*x^5) + (b*(12*c^2*d + 25*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(225*x^3) + (2*b*c^2*(12*c^2*d + 25*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(225*x) - (d*(a + b*asech(c*x)))/(5*x^5) - (e*(a + b*asech(c*x)))/(3*x^3)]
    @test_int [((d + e*x^2)*(a + b*asech(c*x)))/x^8, x, 6, (b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(49*x^7) + (b*(30*c^2*d + 49*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(1225*x^5) + (4*b*c^2*(30*c^2*d + 49*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3675*x^3) + (8*b*c^4*(30*c^2*d + 49*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3675*x) - (d*(a + b*asech(c*x)))/(7*x^7) - (e*(a + b*asech(c*x)))/(5*x^5)]

    @test_int [x^5*(d + e*x^2)*(a + b*asech(c*x)), x, 5, -((b*(4*c^2*d + 3*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(24*c^8)) + (b*(8*c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(3/2))/(72*c^8) - (b*(4*c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(5/2))/(120*c^8) + (b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(7/2))/(56*c^8) + (1/6)*d*x^6*(a + b*asech(c*x)) + (1/8)*e*x^8*(a + b*asech(c*x))]
    @test_int [x^3*(d + e*x^2)*(a + b*asech(c*x)), x, 5, -((b*(3*c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(12*c^6)) + (b*(3*c^2*d + 4*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(3/2))/(36*c^6) - (b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(5/2))/(30*c^6) + (1/4)*d*x^4*(a + b*asech(c*x)) + (1/6)*e*x^6*(a + b*asech(c*x))]
    @test_int [x*(d + e*x^2)*(a + b*asech(c*x)), x, 7, -((b*(2*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(4*c^4)) + (b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(3/2))/(12*c^4) + ((d + e*x^2)^2*(a + b*asech(c*x)))/(4*e) - (b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(4*e)]
    @test_int [((d + e*x^2)*(a + b*asech(c*x)))/x, x, 12, -((b*e*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)/(2*c)) + (im*b*d*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)^2)/(2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (1/2)*e*x^2*(a + b*asech(c*x)) - (b*d*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1 - ℯ^(2*im*acsc(c*x))))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (b*d*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1/x))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - d*(a + b*asech(c*x))*log(1/x) + (im*b*d*sqrt(1 - 1/(c^2*x^2))*PolyLog(2, ℯ^(2*im*acsc(c*x))))/(2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))]
    @test_int [((d + e*x^2)*(a + b*asech(c*x)))/x^3, x, 14, (b*c*d*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(4*x) + (im*b*e*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)^2)/(2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (1/4)*b*c^2*d*asech(c*x) - (d*(a + b*asech(c*x)))/(2*x^2) - (b*e*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1 - ℯ^(2*im*acsc(c*x))))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (b*e*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1/x))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - e*(a + b*asech(c*x))*log(1/x) + (im*b*e*sqrt(1 - 1/(c^2*x^2))*PolyLog(2, ℯ^(2*im*acsc(c*x))))/(2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))]


    @test_int [x^2*(d + e*x^2)^2*(a + b*asech(c*x)), x, 6, -((b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(1680*c^6)) - (b*e*(84*c^2*d + 25*e)*x^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(840*c^4) - (b*e^2*x^5*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(42*c^2) + (1/3)*d^2*x^3*(a + b*asech(c*x)) + (2/5)*d*e*x^5*(a + b*asech(c*x)) + (1/7)*e^2*x^7*(a + b*asech(c*x)) + (b*(280*c^4*d^2 + 252*c^2*d*e + 75*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(1680*c^7)]
    @test_int [x^0*(d + e*x^2)^2*(a + b*asech(c*x)), x, 5, -((b*e*(40*c^2*d + 9*e)*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(120*c^4)) - (b*e^2*x^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(20*c^2) + d^2*x*(a + b*asech(c*x)) + (2/3)*d*e*x^3*(a + b*asech(c*x)) + (1/5)*e^2*x^5*(a + b*asech(c*x)) + (b*(120*c^4*d^2 + 40*c^2*d*e + 9*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(120*c^5)]
    @test_int [((d + e*x^2)^2*(a + b*asech(c*x)))/x^2, x, 5, (b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/x - (b*e^2*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(6*c^2) - (d^2*(a + b*asech(c*x)))/x + 2*d*e*x*(a + b*asech(c*x)) + (1/3)*e^2*x^3*(a + b*asech(c*x)) + (b*e*(12*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/(6*c^3)]
    @test_int [((d + e*x^2)^2*(a + b*asech(c*x)))/x^4, x, 5, (b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(9*x^3) + (2*b*d*(c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(9*x) - (d^2*(a + b*asech(c*x)))/(3*x^3) - (2*d*e*(a + b*asech(c*x)))/x + e^2*x*(a + b*asech(c*x)) + (b*e^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*asin(c*x))/c]
    @test_int [((d + e*x^2)^2*(a + b*asech(c*x)))/x^6, x, 5, (b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(25*x^5) + (2*b*d*(6*c^2*d + 25*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(225*x^3) + (b*(24*c^4*d^2 + 100*c^2*d*e + 225*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(225*x) - (d^2*(a + b*asech(c*x)))/(5*x^5) - (2*d*e*(a + b*asech(c*x)))/(3*x^3) - (e^2*(a + b*asech(c*x)))/x]
    @test_int [((d + e*x^2)^2*(a + b*asech(c*x)))/x^8, x, 6, (b*d^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(49*x^7) + (2*b*d*(15*c^2*d + 49*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(1225*x^5) + (b*(360*c^4*d^2 + 1176*c^2*d*e + 1225*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(11025*x^3) + (2*b*c^2*(360*c^4*d^2 + 1176*c^2*d*e + 1225*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(11025*x) - (d^2*(a + b*asech(c*x)))/(7*x^7) - (2*d*e*(a + b*asech(c*x)))/(5*x^5) - (e^2*(a + b*asech(c*x)))/(3*x^3)]

    @test_int [x^3*(d + e*x^2)^2*(a + b*asech(c*x)), x, 5, -((b*(6*c^4*d^2 + 8*c^2*d*e + 3*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(24*c^8)) + (b*(6*c^4*d^2 + 16*c^2*d*e + 9*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(3/2))/(72*c^8) - (b*e*(8*c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(5/2))/(120*c^8) + (b*e^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(7/2))/(56*c^8) + (1/4)*d^2*x^4*(a + b*asech(c*x)) + (1/3)*d*e*x^6*(a + b*asech(c*x)) + (1/8)*e^2*x^8*(a + b*asech(c*x))]
    @test_int [x^1*(d + e*x^2)^2*(a + b*asech(c*x)), x, 7, -((b*(3*c^4*d^2 + 3*c^2*d*e + e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(6*c^6)) + (b*e*(3*c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(3/2))/(18*c^6) - (b*e^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*(1 - c^2*x^2)^(5/2))/(30*c^6) + ((d + e*x^2)^3*(a + b*asech(c*x)))/(6*e) - (b*d^3*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(6*e)]
    @test_int [((d + e*x^2)^2*(a + b*asech(c*x)))/x^1, x, 13, -((b*e*(6*c^2*d + e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)/(6*c^3)) - (b*e^2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x^3)/(12*c) + (im*b*d^2*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)^2)/(2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + d*e*x^2*(a + b*asech(c*x)) + (1/4)*e^2*x^4*(a + b*asech(c*x)) - (b*d^2*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1 - ℯ^(2*im*acsc(c*x))))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (b*d^2*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1/x))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - d^2*(a + b*asech(c*x))*log(1/x) + (im*b*d^2*sqrt(1 - 1/(c^2*x^2))*PolyLog(2, ℯ^(2*im*acsc(c*x))))/(2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))]
    @test_int [((d + e*x^2)^2*(a + b*asech(c*x)))/x^3, x, 15, (b*c*d^2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(4*x) - (b*e^2*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)/(2*c) + (im*b*d*e*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)^2)/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (1/4)*b*c^2*d^2*asech(c*x) - (d^2*(a + b*asech(c*x)))/(2*x^2) + (1/2)*e^2*x^2*(a + b*asech(c*x)) - (2*b*d*e*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1 - ℯ^(2*im*acsc(c*x))))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (2*b*d*e*sqrt(1 - 1/(c^2*x^2))*acsc(c*x)*log(1/x))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - 2*d*e*(a + b*asech(c*x))*log(1/x) + (im*b*d*e*sqrt(1 - 1/(c^2*x^2))*PolyLog(2, ℯ^(2*im*acsc(c*x))))/(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [(x^2*(a + b*asech(c*x)))/(d + e*x^2), x, 24, (x*(a + b*asech(c*x)))/e - (b*atan(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))))/(c*e) + (sqrt(-d)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^(3/2)) - (sqrt(-d)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^(3/2)) + (sqrt(-d)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^(3/2)) - (sqrt(-d)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^(3/2)) - (b*sqrt(-d)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*e^(3/2)) + (b*sqrt(-d)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^(3/2)) - (b*sqrt(-d)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*e^(3/2)) + (b*sqrt(-d)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^(3/2))]
    @test_int [(x*(a + b*asech(c*x)))/(d + e*x^2), x, 26, -((a + b*asech(c*x))^2/(b*e)) - ((a + b*asech(c*x))*log(1 + ℯ^(-2*asech(c*x))))/e + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e) + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e) + (b*PolyLog(2, -ℯ^(-2*asech(c*x))))/(2*e) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*e) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*e) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e)]
    @test_int [(a + b*asech(c*x))/(d + e*x^2), x, 19, ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*sqrt(-d)*sqrt(e)) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*sqrt(-d)*sqrt(e)) + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*sqrt(-d)*sqrt(e)) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*sqrt(-d)*sqrt(e)) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*sqrt(-d)*sqrt(e)) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*sqrt(-d)*sqrt(e)) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*sqrt(-d)*sqrt(e)) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*sqrt(-d)*sqrt(e))]
    @test_int [(a + b*asech(c*x))/(x*(d + e*x^2)), x, 19, (a + b*asech(c*x))^2/(2*b*d) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*d) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*d) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d)]
    @test_int [(a + b*asech(c*x))/(x^2*(d + e*x^2)), x, 24, (b*c*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/d - a/(d*x) - (b*asech(c*x))/(d*x) + (sqrt(e)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*(-d)^(3/2)) - (sqrt(e)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*(-d)^(3/2)) + (sqrt(e)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*(-d)^(3/2)) - (sqrt(e)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*(-d)^(3/2)) - (b*sqrt(e)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*(-d)^(3/2)) + (b*sqrt(e)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*(-d)^(3/2)) - (b*sqrt(e)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*(-d)^(3/2)) + (b*sqrt(e)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*(-d)^(3/2))]


    @test_int [(x^5*(a + b*asech(c*x)))/(d + e*x^2)^2, x, 32, -((b*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)/(2*c*e^2)) + (d*(a + b*asech(c*x)))/(2*e^2*(e + d/x^2)) + (x^2*(a + b*asech(c*x)))/(2*e^2) + (2*d*(a + b*asech(c*x))^2)/(b*e^3) - (b*d*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(2*e^(5/2)*sqrt(c^2*d + e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (2*d*(a + b*asech(c*x))*log(1 + ℯ^(-2*asech(c*x))))/e^3 - (d*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/e^3 - (d*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/e^3 - (d*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/e^3 - (d*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/e^3 - (b*d*PolyLog(2, -ℯ^(-2*asech(c*x))))/e^3 - (b*d*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/e^3 - (b*d*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/e^3 - (b*d*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/e^3 - (b*d*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/e^3]
    @test_int [(x^3*(a + b*asech(c*x)))/(d + e*x^2)^2, x, 30, -((a + b*asech(c*x))/(2*e*(e + d/x^2))) - (a + b*asech(c*x))^2/(b*e^2) + (b*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(2*e^(3/2)*sqrt(c^2*d + e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - ((a + b*asech(c*x))*log(1 + ℯ^(-2*asech(c*x))))/e^2 + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^2) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^2) + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^2) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^2) + (b*PolyLog(2, -ℯ^(-2*asech(c*x))))/(2*e^2) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*e^2) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^2) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*e^2) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^2)]
    @test_int [(x*(a + b*asech(c*x)))/(d + e*x^2)^2, x, 8, -((a + b*asech(c*x))/(2*e*(d + e*x^2))) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(2*d*e) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh((sqrt(e)*sqrt(1 - c^2*x^2))/sqrt(c^2*d + e)))/(2*d*sqrt(e)*sqrt(c^2*d + e))]
    @test_int [(a + b*asech(c*x))/(x*(d + e*x^2)^2), x, 25, -((e*(a + b*asech(c*x)))/(2*d^2*(e + d/x^2))) + (a + b*asech(c*x))^2/(2*b*d^2) + (b*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(2*d^2*sqrt(c^2*d + e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d^2) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d^2) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d^2) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d^2) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*d^2) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d^2) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*d^2) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d^2)]

    @test_int [(x^4*(a + b*asech(c*x)))/(d + e*x^2)^2, x, 50, -((d*(a + b*asech(c*x)))/(4*e^2*(sqrt(-d)*sqrt(e) - d/x))) + (d*(a + b*asech(c*x)))/(4*e^2*(sqrt(-d)*sqrt(e) + d/x)) + (x*(a + b*asech(c*x)))/e^2 + (b*d*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e^2) + (b*d*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e^2) - (b*atan(sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))))/(c*e^2) + (3*sqrt(-d)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*e^(5/2)) - (3*sqrt(-d)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*e^(5/2)) + (3*sqrt(-d)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*e^(5/2)) - (3*sqrt(-d)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*e^(5/2)) - (3*b*sqrt(-d)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(4*e^(5/2)) + (3*b*sqrt(-d)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*e^(5/2)) - (3*b*sqrt(-d)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(4*e^(5/2)) + (3*b*sqrt(-d)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*e^(5/2))]
    @test_int [(x^2*(a + b*asech(c*x)))/(d + e*x^2)^2, x, 27, (a + b*asech(c*x))/(4*e*(sqrt(-d)*sqrt(e) - d/x)) - (a + b*asech(c*x))/(4*e*(sqrt(-d)*sqrt(e) + d/x)) - (b*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e) - (b*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e) + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*sqrt(-d)*e^(3/2)) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*sqrt(-d)*e^(3/2)) + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*sqrt(-d)*e^(3/2)) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*sqrt(-d)*e^(3/2)) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(4*sqrt(-d)*e^(3/2)) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*sqrt(-d)*e^(3/2)) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(4*sqrt(-d)*e^(3/2)) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*sqrt(-d)*e^(3/2))]
    @test_int [(a + b*asech(c*x))/(d + e*x^2)^2, x, 47, -((a + b*asech(c*x))/(4*d*(sqrt(-d)*sqrt(e) - d/x))) + (a + b*asech(c*x))/(4*d*(sqrt(-d)*sqrt(e) + d/x)) + (b*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*d*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))) + (b*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*d*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*(-d)^(3/2)*sqrt(e)) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*(-d)^(3/2)*sqrt(e)) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*(-d)^(3/2)*sqrt(e)) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*(-d)^(3/2)*sqrt(e)) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(4*(-d)^(3/2)*sqrt(e)) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*(-d)^(3/2)*sqrt(e)) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(4*(-d)^(3/2)*sqrt(e)) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*(-d)^(3/2)*sqrt(e))]
    @test_int [(a + b*asech(c*x))/(x^2*(d + e*x^2)^2), x, 50, (b*c*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/d^2 - a/(d^2*x) - (b*asech(c*x))/(d^2*x) + (e*(a + b*asech(c*x)))/(4*d^2*(sqrt(-d)*sqrt(e) - d/x)) - (e*(a + b*asech(c*x)))/(4*d^2*(sqrt(-d)*sqrt(e) + d/x)) - (b*e*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*d^2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))) - (b*e*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(2*d^2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))) - (3*sqrt(e)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*(-d)^(5/2)) + (3*sqrt(e)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*(-d)^(5/2)) - (3*sqrt(e)*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*(-d)^(5/2)) + (3*sqrt(e)*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*(-d)^(5/2)) + (3*b*sqrt(e)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(4*(-d)^(5/2)) - (3*b*sqrt(e)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(4*(-d)^(5/2)) + (3*b*sqrt(e)*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(4*(-d)^(5/2)) - (3*b*sqrt(e)*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(4*(-d)^(5/2))]


    @test_int [(x^5*(a + b*asech(c*x)))/(d + e*x^2)^3, x, 35, (b*d*(c^2 - 1/x^2))/(8*c*e^2*(c^2*d + e)*(e + d/x^2)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) - (a + b*asech(c*x))/(4*e*(e + d/x^2)^2) - (a + b*asech(c*x))/(2*e^2*(e + d/x^2)) - (a + b*asech(c*x))^2/(b*e^3) + (b*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(2*e^(5/2)*sqrt(c^2*d + e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) + (b*(c^2*d + 2*e)*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(8*e^(5/2)*(c^2*d + e)^(3/2)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - ((a + b*asech(c*x))*log(1 + ℯ^(-2*asech(c*x))))/e^3 + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^3) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^3) + ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^3) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^3) + (b*PolyLog(2, -ℯ^(-2*asech(c*x))))/(2*e^3) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*e^3) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*e^3) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*e^3) + (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*e^3)]
    @test_int [(x^3*(a + b*asech(c*x)))/(d + e*x^2)^3, x, 6, (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(8*e*(c^2*d + e)*(d + e*x^2)) + (x^4*(a + b*asech(c*x)))/(4*d*(d + e*x^2)^2) - (b*(c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh((sqrt(e)*sqrt(1 - c^2*x^2))/sqrt(c^2*d + e)))/(8*d*e^(3/2)*(c^2*d + e)^(3/2))]
    @test_int [(x*(a + b*asech(c*x)))/(d + e*x^2)^3, x, 9, -((b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(8*d*(c^2*d + e)*(d + e*x^2))) - (a + b*asech(c*x))/(4*e*(d + e*x^2)^2) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(1 - c^2*x^2)))/(4*d^2*e) - (b*(3*c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh((sqrt(e)*sqrt(1 - c^2*x^2))/sqrt(c^2*d + e)))/(8*d^2*sqrt(e)*(c^2*d + e)^(3/2))]
    @test_int [(a + b*asech(c*x))/(x*(d + e*x^2)^3), x, 30, -((b*e*(c^2 - 1/x^2))/(8*c*d^2*(c^2*d + e)*(e + d/x^2)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)) + (e^2*(a + b*asech(c*x)))/(4*d^3*(e + d/x^2)^2) - (e*(a + b*asech(c*x)))/(d^3*(e + d/x^2)) + (a + b*asech(c*x))^2/(2*b*d^3) + (b*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(d^3*sqrt(c^2*d + e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - (b*sqrt(e)*(c^2*d + 2*e)*sqrt(-1 + 1/(c^2*x^2))*atanh(sqrt(c^2*d + e)/(c*sqrt(e)*sqrt(-1 + 1/(c^2*x^2))*x)))/(8*d^3*(c^2*d + e)^(3/2)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d^3) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d^3) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d^3) - ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d^3) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(2*d^3) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(2*d^3) - (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(2*d^3) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(2*d^3)]

    @test_int [(x^4*(a + b*asech(c*x)))/(d + e*x^2)^3, x, 35, (b*c*sqrt(-d)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(16*e^(3/2)*(c^2*d + e)*(sqrt(-d)*sqrt(e) - d/x)) + (b*c*sqrt(-d)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(16*e^(3/2)*(c^2*d + e)*(sqrt(-d)*sqrt(e) + d/x)) + (sqrt(-d)*(a + b*asech(c*x)))/(16*e^(3/2)*(sqrt(-d)*sqrt(e) - d/x)^2) + (3*(a + b*asech(c*x)))/(16*e^2*(sqrt(-d)*sqrt(e) - d/x)) - (sqrt(-d)*(a + b*asech(c*x)))/(16*e^(3/2)*(sqrt(-d)*sqrt(e) + d/x)^2) - (3*(a + b*asech(c*x)))/(16*e^2*(sqrt(-d)*sqrt(e) + d/x)) - (3*b*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e^2) - (b*d*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*(c*d - sqrt(-d)*sqrt(e))^(3/2)*(c*d + sqrt(-d)*sqrt(e))^(3/2)*e) - (3*b*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e^2) - (b*d*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*(c*d - sqrt(-d)*sqrt(e))^(3/2)*(c*d + sqrt(-d)*sqrt(e))^(3/2)*e) + (3*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*sqrt(-d)*e^(5/2)) - (3*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*sqrt(-d)*e^(5/2)) + (3*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*sqrt(-d)*e^(5/2)) - (3*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*sqrt(-d)*e^(5/2)) - (3*b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(16*sqrt(-d)*e^(5/2)) + (3*b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*sqrt(-d)*e^(5/2)) - (3*b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(16*sqrt(-d)*e^(5/2)) + (3*b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*sqrt(-d)*e^(5/2))]
    @test_int [(x^2*(a + b*asech(c*x)))/(d + e*x^2)^3, x, 63, (b*c*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(16*sqrt(-d)*sqrt(e)*(c^2*d + e)*(sqrt(-d)*sqrt(e) - d/x)) + (b*c*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(16*sqrt(-d)*sqrt(e)*(c^2*d + e)*(sqrt(-d)*sqrt(e) + d/x)) + (a + b*asech(c*x))/(16*sqrt(-d)*sqrt(e)*(sqrt(-d)*sqrt(e) - d/x)^2) + (a + b*asech(c*x))/(16*d*e*(sqrt(-d)*sqrt(e) - d/x)) - (a + b*asech(c*x))/(16*sqrt(-d)*sqrt(e)*(sqrt(-d)*sqrt(e) + d/x)^2) - (a + b*asech(c*x))/(16*d*e*(sqrt(-d)*sqrt(e) + d/x)) + (b*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*(c*d - sqrt(-d)*sqrt(e))^(3/2)*(c*d + sqrt(-d)*sqrt(e))^(3/2)) - (b*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*d*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e) + (b*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*(c*d - sqrt(-d)*sqrt(e))^(3/2)*(c*d + sqrt(-d)*sqrt(e))^(3/2)) - (b*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*d*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))*e) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*(-d)^(3/2)*e^(3/2)) - ((a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*(-d)^(3/2)*e^(3/2)) + ((a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*(-d)^(3/2)*e^(3/2)) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(16*(-d)^(3/2)*e^(3/2)) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*(-d)^(3/2)*e^(3/2)) + (b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(16*(-d)^(3/2)*e^(3/2)) - (b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*(-d)^(3/2)*e^(3/2))]
    @test_int [(a + b*asech(c*x))/(d + e*x^2)^3, x, 81, (b*c*sqrt(e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(16*(-d)^(3/2)*(c^2*d + e)*(sqrt(-d)*sqrt(e) - d/x)) + (b*c*sqrt(e)*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x)))/(16*(-d)^(3/2)*(c^2*d + e)*(sqrt(-d)*sqrt(e) + d/x)) + (sqrt(e)*(a + b*asech(c*x)))/(16*(-d)^(3/2)*(sqrt(-d)*sqrt(e) - d/x)^2) - (5*(a + b*asech(c*x)))/(16*d^2*(sqrt(-d)*sqrt(e) - d/x)) - (sqrt(e)*(a + b*asech(c*x)))/(16*(-d)^(3/2)*(sqrt(-d)*sqrt(e) + d/x)^2) + (5*(a + b*asech(c*x)))/(16*d^2*(sqrt(-d)*sqrt(e) + d/x)) + (5*b*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*d^2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))) - (b*e*atan((sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*d*(c*d - sqrt(-d)*sqrt(e))^(3/2)*(c*d + sqrt(-d)*sqrt(e))^(3/2)) + (5*b*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*d^2*sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(c*d + sqrt(-d)*sqrt(e))) - (b*e*atan((sqrt(c*d + sqrt(-d)*sqrt(e))*sqrt(1 + 1/(c*x)))/(sqrt(c*d - sqrt(-d)*sqrt(e))*sqrt(-1 + 1/(c*x)))))/(8*d*(c*d - sqrt(-d)*sqrt(e))^(3/2)*(c*d + sqrt(-d)*sqrt(e))^(3/2)) + (3*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*(-d)^(5/2)*sqrt(e)) - (3*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*(-d)^(5/2)*sqrt(e)) + (3*(a + b*asech(c*x))*log(1 - (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*(-d)^(5/2)*sqrt(e)) - (3*(a + b*asech(c*x))*log(1 + (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*(-d)^(5/2)*sqrt(e)) - (3*b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e)))))/(16*(-d)^(5/2)*sqrt(e)) + (3*b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) - sqrt(c^2*d + e))))/(16*(-d)^(5/2)*sqrt(e)) - (3*b*PolyLog(2, -((c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e)))))/(16*(-d)^(5/2)*sqrt(e)) + (3*b*PolyLog(2, (c*sqrt(-d)*ℯ^asech(c*x))/(sqrt(e) + sqrt(c^2*d + e))))/(16*(-d)^(5/2)*sqrt(e))]


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*x^m*(d+e*x^2)^(p/2)*(a+b*asech(c*x))=#


    #= ::Subsubsection::Closed:: =#
    #=p>0=#


    @test_int [x^5*sqrt(d + e*x^2)*(a + b*asech(c*x)), x, If(13>=8, 12, 13), (b*(23*c^4*d^2 + 12*c^2*d*e - 75*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(1680*c^6*e^2) + (b*(29*c^2*d - 25*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(840*c^4*e^2) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(5/2))/(42*c^2*e^2) + (d^2*(d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e^3) - (2*d*(d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*e^3) + ((d + e*x^2)^(7/2)*(a + b*asech(c*x)))/(7*e^3) - (b*(105*c^6*d^3 - 35*c^4*d^2*e + 63*c^2*d*e^2 + 75*e^3)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(1680*c^7*e^(5/2)) - (8*b*d^(7/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(105*e^3)]
    @test_int [x^3*sqrt(d + e*x^2)*(a + b*asech(c*x)), x, If(13>=8, 11, 12), If(13>=8, -((b*(c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(120*c^4*e)) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(20*c^2*e) - (d*(d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*e^2) + (b*(15*c^4*d^2 - 10*c^2*d*e - 9*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(120*c^5*e^(3/2)) + (2*b*d^(5/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(15*e^2), -((b*(c^2*d + 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(120*c^4*e)) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(20*c^2*e) - (d*(d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e^2) + ((d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*e^2) + (b*(15*c^4*d^2 - 10*c^2*d*e - 9*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(120*c^5*e^(3/2)) + (2*b*d^(5/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(15*e^2))]
    @test_int [x*sqrt(d + e*x^2)*(a + b*asech(c*x)), x, 10, -((b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(6*c^2)) + ((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e) - (b*(3*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(6*c^3*sqrt(e)) - (b*d^(3/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(3*e)]
    @test_int [sqrt(d + e*x^2)*(a + b*asech(c*x))/x^1, x, 0, Unintegrable((sqrt(d + e*x^2)*(a + b*asech(c*x)))/x, x)]
    @test_int [sqrt(d + e*x^2)*(a + b*asech(c*x))/x^3, x, 0, Unintegrable((sqrt(d + e*x^2)*(a + b*asech(c*x)))/x^3, x)]

    @test_int [x^2*sqrt(d + e*x^2)*(a + b*asech(c*x)), x, 0, Unintegrable(x^2*sqrt(d + e*x^2)*(a + b*asech(c*x)), x)]
    @test_int [x^0*sqrt(d + e*x^2)*(a + b*asech(c*x)), x, 0, Unintegrable(sqrt(d + e*x^2)*(a + b*asech(c*x)), x)]
    @test_int [sqrt(d + e*x^2)*(a + b*asech(c*x))/x^2, x, 0, Unintegrable((sqrt(d + e*x^2)*(a + b*asech(c*x)))/x^2, x)]
    @test_int [sqrt(d + e*x^2)*(a + b*asech(c*x))/x^4, x, 9, (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(9*x^3) + (2*b*(c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(9*d*x) - ((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*d*x^3) + (2*b*c*(c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(9*d*sqrt(1 + (e*x^2)/d)) - (b*(c^2*d + e)*(2*c^2*d + 3*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(9*c*d*sqrt(d + e*x^2))]
    @test_int [sqrt(d + e*x^2)*(a + b*asech(c*x))/x^6, x, If(13>=8, 10, 26), If(13>=8, (b*(12*c^2*d - e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(225*d*x^3) + (b*(24*c^4*d^2 + 19*c^2*d*e - 31*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(225*d^2*x) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(25*d*x^5) - ((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(15*d^2*x^3) + (b*c*(24*c^4*d^2 + 19*c^2*d*e - 31*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(225*d^2*sqrt(1 + (e*x^2)/d)) - (b*(c^2*d + e)*(24*c^4*d^2 + 7*c^2*d*e - 30*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(225*c*d^2*sqrt(d + e*x^2)), (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(25*x^5) + (b*e*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(45*d*x^3) + (b*(4*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(75*d*x^3) - (2*b*e^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(15*d^2*x) + (b*e*(2*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(45*d^2*x) + (b*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(75*d^2*x) - ((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(5*d*x^5) + (2*e*(d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(15*d^2*x^3) - (2*b*c*e^2*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(15*d^2*sqrt(1 + (e*x^2)/d)) + (b*c*e*(2*c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(45*d^2*sqrt(1 + (e*x^2)/d)) + (b*c*(8*c^4*d^2 + 3*c^2*d*e - 2*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(75*d^2*sqrt(1 + (e*x^2)/d)) - (b*c*(8*c^2*d - e)*(c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(75*d*sqrt(d + e*x^2)) - (2*b*c*e*(c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(45*d*sqrt(d + e*x^2)) + (2*b*e^2*(c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(15*c*d^2*sqrt(d + e*x^2)))]


    @test_int [x^3*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x, 12, (b*(3*c^4*d^2 - 38*c^2*d*e - 25*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(560*c^6*e) - (b*(13*c^2*d + 25*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(840*c^4*e) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(5/2))/(42*c^2*e) - (d*(d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*e^2) + ((d + e*x^2)^(7/2)*(a + b*asech(c*x)))/(7*e^2) + (b*(35*c^6*d^3 - 35*c^4*d^2*e - 63*c^2*d*e^2 - 25*e^3)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(560*c^7*e^(3/2)) + (2*b*d^(7/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(35*e^2)]
    @test_int [x^1*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x, 11, -((b*(7*c^2*d + 3*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(40*c^4)) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(20*c^2) + ((d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*e) - (b*(15*c^4*d^2 + 10*c^2*d*e + 3*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(40*c^5*sqrt(e)) - (b*d^(5/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(5*e)]
    @test_int [(d + e*x^2)^(3/2)*(a + b*asech(c*x))/x^1, x, 0, Unintegrable(((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/x, x)]
    @test_int [(d + e*x^2)^(3/2)*(a + b*asech(c*x))/x^3, x, 0, Unintegrable(((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/x^3, x)]

    @test_int [x^2*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x, 0, Unintegrable(x^2*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x)]
    @test_int [x^0*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x, 0, Unintegrable((d + e*x^2)^(3/2)*(a + b*asech(c*x)), x)]
    @test_int [(d + e*x^2)^(3/2)*(a + b*asech(c*x))/x^2, x, 0, Unintegrable(((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/x^2, x)]
    @test_int [(d + e*x^2)^(3/2)*(a + b*asech(c*x))/x^4, x, 0, Unintegrable(((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/x^4, x)]
    @test_int [(d + e*x^2)^(3/2)*(a + b*asech(c*x))/x^6, x, 10, (4*b*(c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(75*x^3) + (b*(8*c^4*d^2 + 23*c^2*d*e + 23*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(75*d*x) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(25*x^5) - ((d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*d*x^5) + (b*c*(8*c^4*d^2 + 23*c^2*d*e + 23*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(75*d*sqrt(1 + (e*x^2)/d)) - (b*(c^2*d + e)*(8*c^4*d^2 + 19*c^2*d*e + 15*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(75*c*d*sqrt(d + e*x^2))]
    @test_int [(d + e*x^2)^(3/2)*(a + b*asech(c*x))/x^8, x, 11, (b*(120*c^4*d^2 + 159*c^2*d*e - 37*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(3675*d*x^3) + (b*(240*c^6*d^3 + 528*c^4*d^2*e + 193*c^2*d*e^2 - 247*e^3)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(3675*d^2*x) + (b*(30*c^2*d + 11*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(1225*d*x^5) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(5/2))/(49*d*x^7) - ((d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(7*d*x^7) + (2*e*(d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(35*d^2*x^5) + (b*c*(240*c^6*d^3 + 528*c^4*d^2*e + 193*c^2*d*e^2 - 247*e^3)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(3675*d^2*sqrt(1 + (e*x^2)/d)) - (2*b*(c^2*d + e)*(120*c^6*d^3 + 204*c^4*d^2*e + 17*c^2*d*e^2 - 105*e^3)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(3675*c*d^2*sqrt(d + e*x^2))]


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [x^5*(a + b*asech(c*x))/sqrt(d + e*x^2), x, 11, (b*(19*c^2*d - 9*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(120*c^4*e^2) - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*(d + e*x^2)^(3/2))/(20*c^2*e^2) + (d^2*sqrt(d + e*x^2)*(a + b*asech(c*x)))/e^3 - (2*d*(d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e^3) + ((d + e*x^2)^(5/2)*(a + b*asech(c*x)))/(5*e^3) - (b*(45*c^4*d^2 - 10*c^2*d*e + 9*e^2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(120*c^5*e^(5/2)) - (8*b*d^(5/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(15*e^3)]
    @test_int [x^3*(a + b*asech(c*x))/sqrt(d + e*x^2), x, 10, -((b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(6*c^2*e)) - (d*sqrt(d + e*x^2)*(a + b*asech(c*x)))/e^2 + ((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e^2) + (b*(3*c^2*d - e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(6*c^3*e^(3/2)) + (2*b*d^(3/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(3*e^2)]
    @test_int [x^1*(a + b*asech(c*x))/sqrt(d + e*x^2), x, 10, (sqrt(d + e*x^2)*(a + b*asech(c*x)))/e - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(c*sqrt(e)) - (b*sqrt(d)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/e]
    @test_int [(a + b*asech(c*x))/(x^1*sqrt(d + e*x^2)), x, 0, Unintegrable((a + b*asech(c*x))/(x*sqrt(d + e*x^2)), x)]
    @test_int [(a + b*asech(c*x))/(x^3*sqrt(d + e*x^2)), x, 0, Unintegrable((a + b*asech(c*x))/(x^3*sqrt(d + e*x^2)), x)]

    @test_int [x^2*(a + b*asech(c*x))/sqrt(d + e*x^2), x, 0, Unintegrable((x^2*(a + b*asech(c*x)))/sqrt(d + e*x^2), x)]
    @test_int [x^0*(a + b*asech(c*x))/sqrt(d + e*x^2), x, 0, Unintegrable((a + b*asech(c*x))/sqrt(d + e*x^2), x)]
    @test_int [(a + b*asech(c*x))/(x^2*sqrt(d + e*x^2)), x, 9, (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(d*x) - (sqrt(d + e*x^2)*(a + b*asech(c*x)))/(d*x) + (b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(d*sqrt(1 + (e*x^2)/d)) - (b*(c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(c*d*sqrt(d + e*x^2))]
    @test_int [(a + b*asech(c*x))/(x^4*sqrt(d + e*x^2)), x, 9, (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(9*d*x^3) + (b*(2*c^2*d - 5*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(9*d^2*x) - (sqrt(d + e*x^2)*(a + b*asech(c*x)))/(3*d*x^3) + (2*e*sqrt(d + e*x^2)*(a + b*asech(c*x)))/(3*d^2*x) + (b*c*(2*c^2*d - 5*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(9*d^2*sqrt(1 + (e*x^2)/d)) - (2*b*(c^2*d - 3*e)*(c^2*d + e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(9*c*d^2*sqrt(d + e*x^2))]


    @test_int [x^5*(a + b*asech(c*x))/(d + e*x^2)^(3/2), x, 10, -((b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(6*c^2*e^2)) - (d^2*(a + b*asech(c*x)))/(e^3*sqrt(d + e*x^2)) - (2*d*sqrt(d + e*x^2)*(a + b*asech(c*x)))/e^3 + ((d + e*x^2)^(3/2)*(a + b*asech(c*x)))/(3*e^3) + (b*(9*c^2*d - e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(6*c^3*e^(5/2)) + (8*b*d^(3/2)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(3*e^3)]
    @test_int [x^3*(a + b*asech(c*x))/(d + e*x^2)^(3/2), x, 9, (d*(a + b*asech(c*x)))/(e^2*sqrt(d + e*x^2)) + (sqrt(d + e*x^2)*(a + b*asech(c*x)))/e^2 - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(c*e^(3/2)) - (2*b*sqrt(d)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/e^2]
    @test_int [x^1*(a + b*asech(c*x))/(d + e*x^2)^(3/2), x, 5, -((a + b*asech(c*x))/(e*sqrt(d + e*x^2))) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(sqrt(d)*e)]
    @test_int [(a + b*asech(c*x))/(x^1*(d + e*x^2)^(3/2)), x, 0, Unintegrable((a + b*asech(c*x))/(x*(d + e*x^2)^(3/2)), x)]
    @test_int [(a + b*asech(c*x))/(x^3*(d + e*x^2)^(3/2)), x, 0, Unintegrable((a + b*asech(c*x))/(x^3*(d + e*x^2)^(3/2)), x)]

    @test_int [x^4*(a + b*asech(c*x))/(d + e*x^2)^(3/2), x, 0, Unintegrable((x^4*(a + b*asech(c*x)))/(d + e*x^2)^(3/2), x)]
    @test_int [x^2*(a + b*asech(c*x))/(d + e*x^2)^(3/2), x, 0, Unintegrable((x^2*(a + b*asech(c*x)))/(d + e*x^2)^(3/2), x)]
    @test_int [x^0*(a + b*asech(c*x))/(d + e*x^2)^(3/2), x, 4, (x*(a + b*asech(c*x)))/(d*sqrt(d + e*x^2)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(c*d*sqrt(d + e*x^2))]
    @test_int [(a + b*asech(c*x))/(x^2*(d + e*x^2)^(3/2)), x, 8, (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2)*sqrt(d + e*x^2))/(d^2*x) - (a + b*asech(c*x))/(d*x*sqrt(d + e*x^2)) - (2*e*x*(a + b*asech(c*x)))/(d^2*sqrt(d + e*x^2)) + (b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(d^2*sqrt(1 + (e*x^2)/d)) - (b*(c^2*d + 2*e)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(c*d^2*sqrt(d + e*x^2))]


    @test_int [x^5*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 10, -((b*d*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3*e^2*(c^2*d + e)*sqrt(d + e*x^2))) - (d^2*(a + b*asech(c*x)))/(3*e^3*(d + e*x^2)^(3/2)) + (2*d*(a + b*asech(c*x)))/(e^3*sqrt(d + e*x^2)) + (sqrt(d + e*x^2)*(a + b*asech(c*x)))/e^3 - (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atan((sqrt(e)*sqrt(1 - c^2*x^2))/(c*sqrt(d + e*x^2))))/(c*e^(5/2)) - (8*b*sqrt(d)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(3*e^3)]
    @test_int [x^3*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 7, (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3*e*(c^2*d + e)*sqrt(d + e*x^2)) + (d*(a + b*asech(c*x)))/(3*e^2*(d + e*x^2)^(3/2)) - (a + b*asech(c*x))/(e^2*sqrt(d + e*x^2)) + (2*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(3*sqrt(d)*e^2)]
    @test_int [x^1*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 6, -((b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3*d*(c^2*d + e)*sqrt(d + e*x^2))) - (a + b*asech(c*x))/(3*e*(d + e*x^2)^(3/2)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*atanh(sqrt(d + e*x^2)/(sqrt(d)*sqrt(1 - c^2*x^2))))/(3*d^(3/2)*e)]
    @test_int [(a + b*asech(c*x))/(x^1*(d + e*x^2)^(5/2)), x, 0, Unintegrable((a + b*asech(c*x))/(x*(d + e*x^2)^(5/2)), x)]
    @test_int [(a + b*asech(c*x))/(x^3*(d + e*x^2)^(5/2)), x, 0, Unintegrable((a + b*asech(c*x))/(x^3*(d + e*x^2)^(5/2)), x)]

    @test_int [x^6*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 0, Unintegrable((x^6*(a + b*asech(c*x)))/(d + e*x^2)^(5/2), x)]
    @test_int [x^4*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 0, Unintegrable((x^4*(a + b*asech(c*x)))/(d + e*x^2)^(5/2), x)]
    @test_int [x^2*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 8, -((b*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3*d*(c^2*d + e)*sqrt(d + e*x^2))) + (x^3*(a + b*asech(c*x)))/(3*d*(d + e*x^2)^(3/2)) - (b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(3*d*e*(c^2*d + e)*sqrt(1 + (e*x^2)/d)) + (b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(3*c*d*e*sqrt(d + e*x^2))]
    @test_int [x^0*(a + b*asech(c*x))/(d + e*x^2)^(5/2), x, 8, (b*e*x*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(3*d^2*(c^2*d + e)*sqrt(d + e*x^2)) + (x*(a + b*asech(c*x)))/(3*d*(d + e*x^2)^(3/2)) + (2*x*(a + b*asech(c*x)))/(3*d^2*sqrt(d + e*x^2)) + (b*c*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(d + e*x^2)*Elliptic.E(asin(c*x), -(e/(c^2*d))))/(3*d^2*(c^2*d + e)*sqrt(1 + (e*x^2)/d)) + (2*b*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 + (e*x^2)/d)*Elliptic.F(asin(c*x), -(e/(c^2*d))))/(3*c*d^2*sqrt(d + e*x^2))]


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*(f*x)^m*(d+e*x^2)^p*(a+b*asech(c*x))*when*m*symbolic=#


    @test_int [(f*x)^m*(d + e*x^2)^3*(a + b*asech(c*x)), x, 5, If(13>=8, -((b*e*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^6*f*(2 + m)*(3 + m)*(4 + m)*(5 + m)*(6 + m)*(7 + m))) - (b*e^2*(e*(5 + m)^2 + 3*c^2*d*(42 + 13*m + m^2))*(f*x)^(3 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^4*f^3*(4 + m)*(5 + m)*(6 + m)*(7 + m)) - (b*e^3*(f*x)^(5 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^2*f^5*(6 + m)*(7 + m)) + (d^3*(f*x)^(1 + m)*(a + b*asech(c*x)))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*asech(c*x)))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*asech(c*x)))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*asech(c*x)))/(f^7*(7 + m)) + (b*((c^6*d^3*(2 + m)*(4 + m)*(6 + m))/(1 + m) + (e*(1 + m)*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4)))/((3 + m)*(5 + m)*(7 + m)))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*HypergeometricFunctions._₂F₁(1/2, (1 + m)/2, (3 + m)/2, c^2*x^2))/(c^6*f*(1 + m)*(2 + m)*(4 + m)*(6 + m)), -((b*e*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^6*f*(6 + m)*(8 + 6*m + m^2)*(105 + 71*m + 15*m^2 + m^3))) - (b*e^2*(e*(5 + m)^2 + 3*c^2*d*(42 + 13*m + m^2))*(f*x)^(3 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^4*f^3*(4 + m)*(5 + m)*(6 + m)*(7 + m)) - (b*e^3*(f*x)^(5 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^2*f^5*(6 + m)*(7 + m)) + (d^3*(f*x)^(1 + m)*(a + b*asech(c*x)))/(f*(1 + m)) + (3*d^2*e*(f*x)^(3 + m)*(a + b*asech(c*x)))/(f^3*(3 + m)) + (3*d*e^2*(f*x)^(5 + m)*(a + b*asech(c*x)))/(f^5*(5 + m)) + (e^3*(f*x)^(7 + m)*(a + b*asech(c*x)))/(f^7*(7 + m)) + (b*((c^6*d^3*(2 + m)*(4 + m)*(6 + m))/(1 + m) + (e*(1 + m)*(e^2*(15 + 8*m + m^2)^2 + 3*c^2*d*e*(3 + m)^2*(42 + 13*m + m^2) + 3*c^4*d^2*(840 + 638*m + 179*m^2 + 22*m^3 + m^4)))/(105 + 71*m + 15*m^2 + m^3))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*HypergeometricFunctions._₂F₁(1/2, (1 + m)/2, (3 + m)/2, c^2*x^2))/(c^6*f*(1 + m)*(2 + m)*(4 + m)*(6 + m)))]
    @test_int [(f*x)^m*(d + e*x^2)^2*(a + b*asech(c*x)), x, 5, If(13>=8, -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^4*f*(2 + m)*(3 + m)*(4 + m)*(5 + m))) - (b*e^2*(f*x)^(3 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^2*f^3*(4 + m)*(5 + m)) + (d^2*(f*x)^(1 + m)*(a + b*asech(c*x)))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*asech(c*x)))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*asech(c*x)))/(f^5*(5 + m)) + (b*(c^4*d^2*(2 + m)*(3 + m)*(4 + m)*(5 + m) + e*(1 + m)^2*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2)))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*HypergeometricFunctions._₂F₁(1/2, (1 + m)/2, (3 + m)/2, c^2*x^2))/(c^4*f*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)), -((b*e*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^4*f*(4 + m)*(5 + m)*(6 + 5*m + m^2))) - (b*e^2*(f*x)^(3 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^2*f^3*(4 + m)*(5 + m)) + (d^2*(f*x)^(1 + m)*(a + b*asech(c*x)))/(f*(1 + m)) + (2*d*e*(f*x)^(3 + m)*(a + b*asech(c*x)))/(f^3*(3 + m)) + (e^2*(f*x)^(5 + m)*(a + b*asech(c*x)))/(f^5*(5 + m)) + (b*(c^4*d^2*(2 + m)*(3 + m)*(4 + m)*(5 + m) + e*(1 + m)^2*(e*(3 + m)^2 + 2*c^2*d*(20 + 9*m + m^2)))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*HypergeometricFunctions._₂F₁(1/2, (1 + m)/2, (3 + m)/2, c^2*x^2))/(c^4*f*(1 + m)^2*(2 + m)*(3 + m)*(4 + m)*(5 + m)))]
    @test_int [(f*x)^m*(d + e*x^2)*(a + b*asech(c*x)), x, 4, -((b*e*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*sqrt(1 - c^2*x^2))/(c^2*f*(2 + m)*(3 + m))) + (d*(f*x)^(1 + m)*(a + b*asech(c*x)))/(f*(1 + m)) + (e*(f*x)^(3 + m)*(a + b*asech(c*x)))/(f^3*(3 + m)) + (b*(e*(1 + m)^2 + c^2*d*(2 + m)*(3 + m))*(f*x)^(1 + m)*sqrt(1/(1 + c*x))*sqrt(1 + c*x)*HypergeometricFunctions._₂F₁(1/2, (1 + m)/2, (3 + m)/2, c^2*x^2))/(c^2*f*(1 + m)^2*(2 + m)*(3 + m))]
    @test_int [((f*x)^m*(a + b*asech(c*x)))/(d + e*x^2), x, 0, Unintegrable(((f*x)^m*(a + b*asech(c*x)))/(d + e*x^2), x)]
    @test_int [((f*x)^m*(a + b*asech(c*x)))/(d + e*x^2)^2, x, 0, Unintegrable(((f*x)^m*(a + b*asech(c*x)))/(d + e*x^2)^2, x)]


    @test_int [(f*x)^m*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x, 0, Unintegrable((f*x)^m*(d + e*x^2)^(3/2)*(a + b*asech(c*x)), x)]
    @test_int [(f*x)^m*sqrt(d + e*x^2)*(a + b*asech(c*x)), x, 0, Unintegrable((f*x)^m*sqrt(d + e*x^2)*(a + b*asech(c*x)), x)]
    @test_int [((f*x)^m*(a + b*asech(c*x)))/sqrt(d + e*x^2), x, 0, Unintegrable(((f*x)^m*(a + b*asech(c*x)))/sqrt(d + e*x^2), x)]
    @test_int [((f*x)^m*(a + b*asech(c*x)))/(d + e*x^2)^(3/2), x, 0, Unintegrable(((f*x)^m*(a + b*asech(c*x)))/(d + e*x^2)^(3/2), x)]


    #= ::Section::Closed:: =#
    #=Integrands*of*the*form*(f*x)^m*(d+e*x^4)^p*(a+b*asech(c*x))^n=#


    #= ::Subsection::Closed:: =#
    #=Integrands*of*the*form*x^m*(d+e*x^4)^(p/2)*(a+b*asech(c*x))=#


    #= ::Subsubsection:: =#
    #=p>0=#


    #= ::Subsubsection::Closed:: =#
    #=p<0=#


    @test_int [x^11*(a + b*asech(c*x))/sqrt(1 - c^4*x^4), x, 15, -((4*b*sqrt(1 - c^2*x^2)*sqrt(1 + c^2*x^2))/(15*c^13*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)) + (7*b*sqrt(1 - c^2*x^2)*(1 + c^2*x^2)^(3/2))/(90*c^13*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) - (13*b*sqrt(1 - c^2*x^2)*(1 + c^2*x^2)^(5/2))/(150*c^13*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) + (3*b*sqrt(1 - c^2*x^2)*(1 + c^2*x^2)^(7/2))/(70*c^13*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) - (b*sqrt(1 - c^2*x^2)*(1 + c^2*x^2)^(9/2))/(90*c^13*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) - (sqrt(1 - c^4*x^4)*(a + b*asech(c*x)))/(2*c^12) + ((1 - c^4*x^4)^(3/2)*(a + b*asech(c*x)))/(3*c^12) - ((1 - c^4*x^4)^(5/2)*(a + b*asech(c*x)))/(10*c^12) + (4*b*sqrt(1 - c^2*x^2)*atanh(sqrt(1 + c^2*x^2)))/(15*c^13*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)]
    @test_int [x^7*(a + b*asech(c*x))/sqrt(1 - c^4*x^4), x, 12, -((b*sqrt(1 - c^2*x^2)*sqrt(1 + c^2*x^2))/(3*c^9*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)) + (b*sqrt(1 - c^2*x^2)*(1 + c^2*x^2)^(3/2))/(18*c^9*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) - (b*sqrt(1 - c^2*x^2)*(1 + c^2*x^2)^(5/2))/(30*c^9*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x) - (sqrt(1 - c^4*x^4)*(a + b*asech(c*x)))/(2*c^8) + ((1 - c^4*x^4)^(3/2)*(a + b*asech(c*x)))/(6*c^8) + (b*sqrt(1 - c^2*x^2)*atanh(sqrt(1 + c^2*x^2)))/(3*c^9*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)]
    @test_int [x^3*(a + b*asech(c*x))/sqrt(1 - c^4*x^4), x, 7, -((b*sqrt(1 - c^2*x^2)*sqrt(1 + c^2*x^2))/(2*c^5*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)) - (sqrt(1 - c^4*x^4)*(a + b*asech(c*x)))/(2*c^4) + (b*sqrt(1 - c^2*x^2)*atanh(sqrt(1 + c^2*x^2)))/(2*c^5*sqrt(-1 + 1/(c*x))*sqrt(1 + 1/(c*x))*x)]
    @test_int [(a + b*asech(c*x))/(x^1*sqrt(1 - c^4*x^4)), x, 0, Unintegrable((a + b*asech(c*x))/(x*sqrt(1 - c^4*x^4)), x)]
    @test_int [(a + b*asech(c*x))/(x^5*sqrt(1 - c^4*x^4)), x, 0, Unintegrable((a + b*asech(c*x))/(x^5*sqrt(1 - c^4*x^4)), x)]


    #= ::Section:: =#
    #=Integrands*of*the*form*u*(a+b*asech(c*x))^n=#
    end
