include("1.1.1.1 (a+b x)^m.jl")
include("1.1.1.2 (a+b x)^m (c+d x)^n.jl")
include("1.1.1.3 (a+b x)^m (c+d x)^n (e+f x)^p.jl")
include("1.1.1.4 (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q.jl")
include("1.1.1.5 P(x) (a+b x)^m (c+d x)^n.jl")
include("1.1.1.6 P(x) (a+b x)^m (c+d x)^n (e+f x)^p.jl")
include("1.1.1.7 P(x) (a+b x)^m (c+d x)^n (e+f x)^p (g+h x)^q.jl")
